Repository liquibase/liquibase, pull requests merged in 2020-06, with the labels that each got.

#1174 Removing quotes around JAVA_HOME in case JAVA_HOME was originally set with quotes around it LB-224
  liquibase-dist/src/main/archive/liquibase.bat
Labels: StatusDiscovery

#1064 Change namespace for changeAttributes type to be namespace="##other"
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd
Labels: DBAll, RiskLow, StatusActive, Target4.0-beta2, ThemeChangeTypes, TypeEnhancement

#1067 #1066 addNotNullConstraint / dropNotNullConstraint not supported on Firebird
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addLookupTable/firebird.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addNotNullConstraint/firebird.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/dropNotNullConstraint/firebird.sql
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/firebird/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/firebird/rollback/rollbackable.changelog.xml
Labels: DBFirebird, RiskLow, StatusActive, Target4.0-beta2, ThemeChangeTypes, TypeEnhancement

#1180 Added help text for the 'runWith' command line option DAT-4751
  liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml
Labels: StatusDiscovery

#1188 Re-worded sample properties file text LB-227 LB-228
  liquibase-dist/src/main/archive/examples/sql/liquibase.properties
  liquibase-dist/src/main/archive/examples/xml/liquibase.properties
Labels: StatusDiscovery

#1208 Do not show "Rolling back" log message when using LoggingExecutor DAT-4657
  liquibase-core/src/main/java/liquibase/changelog/visitor/RollbackVisitor.java
Labels: StatusDiscovery

#917 Core 3463 fix for validateX attributes of constraintsConfig
  liquibase-core/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-core/src/main/java/liquibase/change/ConstraintsConfig.java
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedColumnChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingColumnChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
  liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/structure/core/Column.java
  liquibase-core/src/test/groovy/liquibase/change/ConstraintsConfigTest.groovy
  liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
Labels: DBAll, RiskLow, StatusActive, Target3.10.1, ThemeInternals

#1187 - Moved old *PackageScanClassResolver logic to liquibase-compat
  liquibase-core/src/main/java/liquibase/Scope.java
  liquibase-core/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-core/src/main/java/liquibase/logging/LogFactory.java
  liquibase-core/src/main/java/liquibase/logging/Logger.java
  liquibase-core/src/main/java/liquibase/logging/core/AbstractLogger.java
  liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
  liquibase-core/src/main/java/liquibase/servicelocator/AssignableToPackageScanFilter.java
  liquibase-core/src/main/java/liquibase/servicelocator/CompositePackageScanFilter.java
  liquibase-core/src/main/java/liquibase/servicelocator/DefaultPackageScanClassResolver.java
  liquibase-core/src/main/java/liquibase/servicelocator/PackageScanClassResolver.java
  liquibase-core/src/main/java/liquibase/servicelocator/PackageScanFilter.java
  liquibase-core/src/main/java/liquibase/servicelocator/ServiceLocator.java
  liquibase-core/src/main/java/liquibase/servicelocator/StandardServiceLocator.java
  liquibase-core/src/main/java/liquibase/servicelocator/WebSpherePackageScanClassResolver.java
  liquibase-core/src/main/java/liquibase/util/StreamUtil.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.servicelocator.ServiceLocator
  liquibase-core/src/test/groovy/liquibase/servicelocator/DefaultPackageScanClassResolverTest.groovy
  liquibase-core/src/test/groovy/liquibase/servicelocator/ServiceLocatorTest.groovy
Labels: StatusDiscovery

#941 [CORE-3520] Add support for ALWAYS generation type with PostgreSQL auto-increment column.
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: DBPostgres, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects, TypeBug

#946 [CORE-3524] Prevent auto-increment column silently failing on Oracle.
  liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: DBOracle, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects, TypeBug

#949 [CORE-3526] TABLE is a reserved keyword in H2database since 1.4.197
  base.pom.xml
  liquibase-core/src/main/java/liquibase/database/core/H2Database.java
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
Labels: DBH2, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects, TypeBug

#963 CORE-3556 No default values for changes' properties
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/core/OutputChange.java
  liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
Labels: DBAll, RiskLow, StatusActive, Target3.10.1, ThemeInternals

#965 CORE-3558 Unique constraint name is ignored when using the addColumn change
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/test/java/liquibase/change/AddColumnChangeTest.java
Labels: DBAll, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects

#970 Fix: Java 1.9+ versions require jaxb as separate dependency
  liquibase-maven-plugin/pom.xml
Labels: DBAll, RiskLow, StatusActive, Target3.10.1, ThemeInternals

#1057 Global help should be displayed if no command.
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: RiskLow, StatusDiscovery

#1185 Changes merged in from Datical branch to fix issue with capturing array data type for Postgres DAT-4453
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: StatusDiscovery

#1183 Corrected syntax errors in start-h2 script LB-193
  liquibase-dist/src/main/archive/examples/start-h2
Labels: StatusDiscovery

#1204 Use QUOTE_ALL_OBJECTS for generateChangelog/diff/diffToChangeLog
  liquibase-core/src/main/java/liquibase/command/core/DiffToChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/GenerateChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataChangeGenerator.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
Labels: StatusDiscovery

#1222 Do not print message about license key when none set DAT-4844
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusDiscovery

#1206 Always include tablespace in snapshot and handle default value use case DAT-4084
  liquibase-core/src/main/java/liquibase/diff/compare/core/TableComparator.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/TableSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/structure/core/Table.java
Labels: StatusDiscovery

#986 XMLSerializer: Correct Map value serialization
  liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-core/src/main/java/liquibase/precondition/CustomPreconditionWrapper.java
  liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
  liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
Labels: DBAll, RiskLow, StatusActive, Target3.10.1, ThemeInternals

#993 Improve ChangeFactory initialization time
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java
Labels: DBAll, RiskLow, StatusActive, Target3.10.1, ThemeInternals

#1096 Fix 1039 sequence statement generation for PostgreSQL <= 9.4
  base.pom.xml
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Labels: DBPostgres, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects

#1120 LiquibaseServletListener.contextInitialized() should not shut Embedded Derby down
  liquibase-core/pom.xml
  liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
  liquibase-core/src/main/java/liquibase/integration/servlet/LiquibaseServletListener.java
  liquibase-core/src/test/java/liquibase/database/core/DerbyDatabaseTest.java
  liquibase-core/src/test/java/liquibase/integration/servlet/LiquibaseServletListenerTest.java
  liquibase-core/src/test/java/liquibase/integration/servlet/TestInitialContextFactory.java
  liquibase-core/src/test/resources/liquibase/integration/servlet/simple-changelog.xml
Labels: DBApacheDerby, RiskLow, StatusActive, Target3.10.1, ThemeInternals

#1059 Add code to allow for multiple column unique constraints on table creation.
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: DBSQLLite, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects
