Repository liquibase/liquibase, pull requests merged in 2020-07, with the labels that each got.

#1235 Handle Postgres resetting SEARCH_PATH after rollback LB-225
  liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
Labels: StatusDiscovery

#1209 Handle other data types in setNull call LB-24
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-core/src/test/java/liquibase/statement/ExecutablePreparedStatementBaseTest.java
Labels: StatusDiscovery

#975 NULL date value in prepared statement requires type in MSSQL
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-core/src/test/java/liquibase/statement/ExecutablePreparedStatementBaseTest.java
Labels: DBMSSQLServer, RiskLow, StatusActive, Target3.10.1, ThemeDBObjects

#1237 Re-added OSGi stuff and Liquibase-Package key/value entries to genera…
  liquibase-core/pom.xml
  liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
  liquibase-dist/pom.xml
Labels: StatusDiscovery

#980 fixed invalid carriage return coming from oracle ojdbc8 12.2.0.1
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
Labels: RiskLow, StatusActive, Target3.10.2

#929 Fix #CORE-3493 Inconsistent resolution of ChangeLogParameters in liqu…
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-core/src/test/java/liquibase/changelog/ChangeLogParametersTest.java
Labels: DBAll, RiskLow, StatusActive, Target3.10.2, ThemeInternals

#1257 Display exception error message when unable to connect to database LB-367
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
Labels: StatusDiscovery

#1250 Add any node types discovered from the runAfter and runBefore types to the Map DAT-4050
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-core/src/test/java/liquibase/diff/output/changelog/DiffToChangeLogTest.java
Labels: StatusDiscovery

#910 CORE-2650 Use Base64-encoding to safely store BLOB data in CSV files
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
Labels: RiskMedium, StatusActive, Target3.10.1, TypeEnhancement

#1263 Added "BEST PRACTICE" message to diffChangeLog/generateChangeLog output
  liquibase-core/src/main/java/liquibase/command/core/DiffToChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/GenerateChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusDiscovery

#1262 Liquibase 3.6.0+ run slowly with unique column constraints
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: StatusDiscovery

#976 Changes databasechangelog sql to use legacy mode
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/ClearDatabaseChangeLogTableGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogLockTableGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InitializeDatabaseChangeLogLockTableGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/LockDatabaseChangeLogGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/RemoveChangeSetRanStatusGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogLockGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/TagDatabaseGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/UnlockDatabaseChangeLogGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java
Labels: RiskHigh, StatusActive, Target3.10.2

#947 [CORE-3525] Add support for java.sql.Types.TIMESTAMP_WITH_TIMEZONE.
  liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java
  liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Labels: RiskHigh, StatusActive, Target3.10.1, part-of-larger-change

#1176 Add MariaDB sequence support to the 3.10.x branch
  liquibase-core/src/main/java/liquibase/database/core/MariaDBDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
Labels: DBMariaDB, RiskLow, StatusActive, Target3.10.2, ThemeDBObjects, TypeBug
