Repository liquibase/liquibase, pull requests merged in 2020-09, with the labels that each got.

#1322 Dat 5143
  liquibase-core/src/main/java/liquibase/configuration/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-core/src/main/java/liquibase/integration/ant/AntTaskLogService.java
  liquibase-core/src/main/java/liquibase/integration/ant/AntTaskLogger.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/logging/LogMessageFilter.java
  liquibase-core/src/main/java/liquibase/logging/LogService.java
  liquibase-core/src/main/java/liquibase/logging/core/AbstractLogService.java
  liquibase-core/src/main/java/liquibase/logging/core/AbstractLogger.java
  liquibase-core/src/main/java/liquibase/logging/core/BufferedLogService.java
  liquibase-core/src/main/java/liquibase/logging/core/BufferedLogger.java
  liquibase-core/src/main/java/liquibase/logging/core/CompositeLogService.java
  liquibase-core/src/main/java/liquibase/logging/core/CompositeLogger.java
  liquibase-core/src/main/java/liquibase/logging/core/DefaultLogMessageFilter.java
  liquibase-core/src/main/java/liquibase/logging/core/JavaLogService.java
  liquibase-core/src/main/java/liquibase/logging/core/JavaLogger.java
Labels: IntegrationCLI, StatusDiscovery

#1350 Help for Hub DAT-4987
  liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml
Labels: StatusDiscovery

#1349 Added registerChangeLog and syncHub to autocomplete scripts DAT-5185
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete_mac.bash
Labels: StatusDiscovery

#1364 Handle non-JSON return content from Hub DAT-5306
  liquibase-core/src/main/java/liquibase/hub/LiquibaseHubRedirectException.java
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
Labels: StatusDiscovery

#1365 Do not send information to Hub for updateSQL DAT-5307
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
Labels: StatusDiscovery

#1010 Potential fix for generated columns on postgres
  liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-core/src/main/java/liquibase/datatype/LiquibaseDataType.java
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/DecimalType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/NumberType.java
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/UnknownType.java
Labels: DBPostgres, IntegrationAny, RiskMedium, StatusConditioning, Target3.10.3, ThemeDBObjects, TypeBug

#1385 Added executedDate to change-events message Added some additional logging DAT-5125
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
  liquibase-core/src/main/java/liquibase/hub/model/OperationChangeEvent.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRegisterChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollback.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseSyncHubMojo.java
Labels: StatusDiscovery

#1392 Update banner to indicate liquibase.com/support
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
Labels: StatusDiscovery

#1390 Do not send generated SQL or changeset body to Hub for changeLogSync DAT-5428
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1391 Caching for performance DAT-5371
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java
  liquibase-core/src/main/java/liquibase/hub/HubService.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/OfflineHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1404 Maven syncHub with a non-unique URL does not return the correct error…
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseHistoryMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRegisterChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetSQL.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateSQL.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseSyncHubMojo.java
Labels: StatusDiscovery

#1258 Reduced the verbosity of logging by moving SQL logging from info to d…
  liquibase-core/src/main/java/liquibase/database/jvm/DerbyConnection.java
  liquibase-core/src/main/java/liquibase/database/jvm/HsqlConnection.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/lockservice/LockServiceExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AbstractExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/test/DatabaseTestContext.java
Labels: DBAll, ImpactLow, IntegrationAny, RiskMedium, Severity3, StatusDiscovery, Target3.10.3, TypeEnhancement

#983 Fixes for loadData to support Postgres enums with java.sql.Types.OTHER
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-core/src/test/java/liquibase/change/LoadDataOtherTest.java
  liquibase-core/src/test/resources/liquibase/change/core/enum-data.csv
  liquibase-integration-tests/src/test/resources/changelogs/enum-data.csv
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/included.changelog.xml
Labels: DBPostgres, IntegrationAny, RiskMedium, StatusConditioning, Target3.10.3, ThemeDBObjects, TypeEnhancement

#1239 Fix xsd, remove surplus space after validateForeignKey
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.7.xsd
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd
Labels: DBAll, ImpactHigh, IntegrationAnt, IntegrationSpringboot, RiskMedium, Severity3, StatusDiscovery, Target3.10.3, ThemeInternals, TypeBug

#1342 Dat 5158
  liquibase-core/src/main/java/liquibase/configuration/HubConfiguration.java
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
  liquibase-core/src/test/groovy/liquibase/hub/core/OnlineHubServiceTest.groovy
  liquibase-core/src/test/java/liquibase/hub/core/MockHttpClient.java
Labels: StatusDiscovery

#912 CORE-3379 escaping postgres questionmark operators to prevent unwante…
  liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java
Labels: DBPostgres, ImpactLow, IntegrationAny, RiskLow, StatusConditioning, Target3.10.3, ThemeDBObjects, TypeEnhancement

#1319 Support DESC primary key in CockroachDB
  .travis/databases.docker-compose.yml
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgres.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/cockroachdb/CockroachDBIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/included.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/renamed.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/rollback/rollbackable.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
Labels: DBCockroachDB, ImpactMedium, IntegrationAny, RiskMedium, Severity3, StatusDiscovery, TypeEnhancement

#1351 Disable transactions for Cockroachdb
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/root.changelog.xml
Labels: DBCockroachDB, StatusDiscovery

#936 SpringLiquibase ResourceAccessor is now overridable
  liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: DBAll, IntegrationSpringboot, RiskMedium, Severity3, StatusConditioning, Target3.10.3, TypeEnhancement

#1396 Capture the log for each change set to send to Hub DAT-5436
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
  liquibase-core/src/test/groovy/liquibase/command/core/SyncHubCommandTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
Labels: StatusDiscovery

#1413 Make count messages be log level FINE DAT-5481
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1140 Fix root paths for Spring Boot fat jar
  liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: DBAll, ImpactMedium, IntegrationSpringboot, RiskMedium, StatusConditioning, Target3.10.3, ThemeUsability, TypeBug

#1332 Update FileSystemResourceAccessor.java
  liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
Labels: ImpactLow, IntegrationMaven, Severity3, StatusDiscovery, Target3.10.3

#945 [CORE-3523] Consistently map Liquibase integer types to Oracle integer types
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java
  liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addColumn/oracle.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createTable/oracle.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/modifyDataType/oracle.sql
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
Labels: DBOracle, IntegrationAny, RiskMedium, StatusConditioning, Target3.10.3, ThemeChangeTypes, TypeBug, part-of-larger-change

#1409 Do not show communication failure message for Hub if no API key DAT-5468
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
Labels: StatusDiscovery

#1410 Upgarde XSD to 4.1 DAT-5442
  base.pom.xml
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd
  liquibase-dist/src/main/archive/examples/xml/blank.changelog.xml
  liquibase-dist/src/main/archive/examples/xml/sample.changelog.xml
Labels: StatusDiscovery

#1418 Revert "[CORE-3523] Consistently map Liquibase integer types to Oracle integer types"
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/MediumIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java
  liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addColumn/oracle.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createTable/oracle.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/modifyDataType/oracle.sql
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
Labels: StatusDiscovery

#781 feat: Maven Liquibase Plugin generateChangeLog mysql sql comment supp…
  liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
Labels: DBMySQL, ImpactLow, IntegrationMaven, RiskHigh, StatusConditioning, Target3.10.3, ThemeChangeTypes, TypeBug

#1397 Dat 5205
  liquibase-core/src/main/java/liquibase/hub/HubService.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/OfflineHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
  liquibase-core/src/main/java/liquibase/integration/IntegrationDetails.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: StatusDiscovery

#1405 If the changelog has not been registered then show a message that says so DAT-5394
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1424 NPE thrown when hubProjectId does not have permissions to a project
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/hub/HubService.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/OfflineHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
Labels: StatusDiscovery

#1421 Show warning message if changelog not registered when hub key exists and mode not off DAT-5522
  liquibase-core/src/main/java/liquibase/command/core/DropAllCommand.java
  liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/test/groovy/liquibase/command/core/DropAllCommandTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java
Labels: StatusDiscovery

#1434 Check for API key before complaining about Hub when doing rollback DAT-5634
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1431 Fix merge issue in OracleDatabase GH-1251
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
Labels: StatusDiscovery
