Repository liquibase/liquibase, pull requests merged in 2020-11, with the labels that each got.

#373 Added option "updateable" to the column tag.
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/change/core/LoadDataColumnConfig.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/InsertStatement.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorMSSQLTest.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorOracleTest.java
Labels: DBAll, IntegrationAny, RiskMedium, StatusDiscovery, Target4.2.0, ThemeChangeTypes, TypeEnhancement

#1427 Update Ant Tasks to use DatabaseFactory rather than create connection itself
  liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java
  liquibase-core/src/main/java/liquibase/integration/ant/AbstractDatabaseDiffTask.java
  liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
  liquibase-core/src/main/java/liquibase/integration/ant/type/DatabaseType.java
  liquibase-core/src/test/groovy/liquibase/change/core/DropAllForeignKeyConstraintsChangeTest.groovy
  liquibase-core/src/test/java/liquibase/database/DatabaseFactoryTest.java
Labels: DBAll, ImpactHigh, IntegrationAnt, RiskLow, StatusDiscovery, Target4.2.0, TypeBug

#1450 Fix #1438 - changeset dbms field serialization
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
Labels: DBAll, IntegrationCLI, RiskMedium, Severity3, StatusConditioning, Target4.1.2, TypeBug, hacktoberfest, hacktoberfest-accepted

#1496 Move banner.txt to new location
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-core/src/main/resources/liquibase/banner.txt
Labels: StatusConditioning, Target4.2.0, hacktoberfest, hacktoberfest-accepted

#1524 Fix xsd, remove surplus space after validateForeignKey
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd
Labels: StatusDiscovery

#1528 Cockroachdb support
  .travis/databases.docker-compose.yml
  liquibase-core/src/main/java/liquibase/change/core/AddPrimaryKeyChange.java
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropUniqueConstraintGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgres.java
  liquibase-core/src/main/java/liquibase/statement/core/AddPrimaryKeyStatement.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.database.Database
  liquibase-core/src/test/java/liquibase/change/ChangeParameterMetaDataTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/cockroachdb/CockroachDBIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/UnlockDatabaseChangeLogExecuteTest.java
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/included.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/renamed.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/rollback/rollbackable.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
Labels: DBCockroachDB, ImpactMedium, IntegrationAny, RiskMedium, Severity3, StatusConditioning, TypeEnhancement

#1425 Give syncHub command ability to use hubProjectId to find connection DAT-5513
  liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/test/groovy/liquibase/command/core/SyncHubCommandTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseSyncHubMojo.java
Labels: StatusDiscovery

#1533 Improved mysql support
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/command/core/SnapshotCommand.java
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
Labels: StatusDiscovery

#1493 Make create project message simpler in RegisterChangeLog DAT-5652
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1522 We do not need to connect to the DB for registerChangeLog even if there is a URL specified LB-737
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusDiscovery

#1497 Send database/driver version information to Hub DAT-5545
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
Labels: StatusDiscovery

#1519 Added text to help Made error handling for Hub HTTP communication be more robust DAT-5856
  liquibase-core/src/main/java/liquibase/command/core/DiffToChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml
Labels: StatusDiscovery

#1532 Handle any whitespace in first line of formatted SQL DAT-5932
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
Labels: StatusDiscovery

#1542 CockroachDatabase: Do not throw exception when connection is not a Jd…
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
Labels: StatusDiscovery

#1403 Fixes #1402 by using a ConcurrentHashMap
  liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
Labels: DBAll, ImpactHigh, IntegrationAny, Severity3, StatusConditioning, Target4.2.2, TypeBug

#931 Fix CORE-3078 bug
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
Labels: DBPostgres, IntegrationAny, RiskMedium, Severity3, StatusActive, Target4.1.2, Target4.2.x, ThemeDBObjects, TypeBug

#1433 Handle exceptions coming from generateSQL DAT-5620
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
Labels: StatusDiscovery

#1440 Make the unexpectedChangeSets command require a changelog LB-375
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusDiscovery

#1548 Fixed UniqueConstraintSnapshotGenerator
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: StatusDiscovery

#1544 Add hub to banner.txt
  liquibase-core/src/main/resources/liquibase/banner.txt
Labels: StatusDiscovery

#1560 DAT-6069 add snyk:test and snyk:monitor mvn goals
  base.pom.xml
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
  liquibase-core/src/test/java/liquibase/verify/change/VerifyChangeClassesTest.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/dropDefaultValue/postgresql.sql
  liquibase-dist/pom.xml
  liquibase-maven-plugin/pom.xml
Labels: StatusDiscovery
