Repository liquibase/liquibase, pull requests merged in 2020-04, with the labels that each got.

#1075 Enable 3.8.x builds on Travis
  .travis.yml
  .travis/databases.docker-compose.yml
  .travis/maven.settings.xml
  .travis/mysql-init.sql
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
Labels: StatusDiscovery

#1033 Enable snapshotByDefault for Data if output directory specified DAT-4129
  liquibase-core/src/main/java/liquibase/configuration/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/structure/core/Data.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java
Labels: RiskLow, StatusActive

#1046 Added Postgres to the list of database which do not need arguments with SMALLINT DAT-4370
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
Labels: RiskLow, StatusDiscovery

#1045 Fix NPE in dependency calculation when objects have no schema
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
Labels: StatusDiscovery

#1049 Support --schemas flag both before and after the "snapshot" command
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: RiskMedium, StatusDiscovery

#1034 Change Liquibase#close to throw LiquibaseException
  liquibase-core/src/main/java/liquibase/Liquibase.java
Labels: RiskLow, Sprint7.2, StatusActive

#1005 CORE-3596 Use LinkedHashMap for a deterministic iteration order in DependencyUtil.java
  liquibase-core/src/main/java/liquibase/util/DependencyUtil.java
Labels: RiskLow, Sprint7.2, StatusActive

#1099 Fix for test break when building with Java > 8
  liquibase-core/src/test/groovy/liquibase/command/core/HistoryCommandTest.groovy
Labels: StatusDiscovery
