Repository liquibase/liquibase, pull requests merged in 2020-08, with the labels that each got.

#1297 DAT-4980 initial harness createTable test
  base.pom.xml
  liquibase-integration-tests/src/test/groovy/liquibase/harness/CreateTable.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/DatabaseTestConnectionUtil.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/FileUtils.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/SnapshotHelpers.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/TestUtils.groovy
  liquibase-integration-tests/src/test/resources/harness/changelogs/createTableChangeLog.xml
  liquibase-integration-tests/src/test/resources/harness/docker/docker-compose.yml
  liquibase-integration-tests/src/test/resources/harness/docker/mysql-init.sql
  liquibase-integration-tests/src/test/resources/harness/docker/postgres-init.sh
  liquibase-integration-tests/src/test/resources/harness/expectedSnapshot/mysql/createTable.json
  liquibase-integration-tests/src/test/resources/harness/expectedSnapshot/postgresql/createTable.json
  liquibase-integration-tests/src/test/resources/harness/expectedSql/mysql/createTable.sql
  liquibase-integration-tests/src/test/resources/harness/expectedSql/postgresql/createTable.sql
  liquibase-integration-tests/src/test/resources/harness/harness.db.properties
Labels: StatusDiscovery

#1314 DAT-5048 update test to take files from path based on DB type + createView and createIndex
  liquibase-integration-tests/src/test/groovy/liquibase/harness/CreateTable.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/MainTestIT.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/config/DatabaseUnderTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/config/DatabaseVersion.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/config/TestConfig.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/config/TestInput.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/DatabaseTestConnectionUtil.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/FileUtils.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/harness/util/TestUtils.groovy
  liquibase-integration-tests/src/test/resources/harness/changelogs/createIndex.xml
  liquibase-integration-tests/src/test/resources/harness/changelogs/createTable.xml
  liquibase-integration-tests/src/test/resources/harness/changelogs/createView.xml
  liquibase-integration-tests/src/test/resources/harness/docker/mysql-init.sql
  liquibase-integration-tests/src/test/resources/harness/docker/postgres-init.sh
  liquibase-integration-tests/src/test/resources/harness/expectedSnapshot/mysql/createIndex.json
  liquibase-integration-tests/src/test/resources/harness/expectedSnapshot/mysql/createView.json
  liquibase-integration-tests/src/test/resources/harness/expectedSnapshot/postgresql/createIndex.json
  liquibase-integration-tests/src/test/resources/harness/expectedSnapshot/postgresql/createView.json
  liquibase-integration-tests/src/test/resources/harness/expectedSql/mysql/createIndex.sql
  liquibase-integration-tests/src/test/resources/harness/expectedSql/mysql/createView.sql
  liquibase-integration-tests/src/test/resources/harness/expectedSql/postgresql/createIndex.sql
  liquibase-integration-tests/src/test/resources/harness/expectedSql/postgresql/createView.sql
  liquibase-integration-tests/src/test/resources/harness/harness.db.properties
  liquibase-integration-tests/src/test/resources/harness/testConfig.yml
Labels: StatusDiscovery

#1306 Improved error messages when hub is not available
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/SyncHubCommand.java
  liquibase-core/src/main/java/liquibase/configuration/HubConfiguration.java
  liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java
  liquibase-core/src/main/java/liquibase/hub/LiquibaseHubSecurityException.java
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusDiscovery

#1308 RegisterChangeLog should fail immediately if changelog is already reg…
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
Labels: StatusDiscovery

#1309 Trailing slash in liquibase.hub.url returns confusing error.
  liquibase-core/src/main/java/liquibase/configuration/ConfigurationProperty.java
  liquibase-core/src/main/java/liquibase/configuration/ConfigurationValueHandler.java
  liquibase-core/src/main/java/liquibase/configuration/HubConfiguration.java
  liquibase-core/src/test/groovy/liquibase/configuration/HubConfigurationTest.groovy
  liquibase-core/src/test/java/liquibase/configuration/LiquibaseConfigurationTest.java
Labels: StatusDiscovery

#1305 Finished implementation for updateCount and updateToTag Hub DAT-4899
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
  liquibase-core/src/main/java/liquibase/hub/model/HubChange.java
  liquibase-core/src/test/resources/META-INF/services/liquibase.executor.Executor
  liquibase-integration-tests/src/test/groovy/liquibase/hub/OnlineHubServiceTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
Labels: DBAll, ImpactMedium, Severity3, StatusDiscovery, TypeEnhancement

#1302 Synchub reports success for bogus values passed to hubEnvironmentId
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: DBAll, ImpactMedium, RiskLow, Severity3, StatusDiscovery, TypeBug

#1333 Do not require URL for registerChangeLog DAT-5092
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusDiscovery

#1348 Make message for not being able to connect to Hub display to the cons…
  liquibase-core/src/main/java/liquibase/hub/core/OnlineHubService.java
Labels: StatusDiscovery

#1346 Generate deployment ID for update to tag DAT-5259
  liquibase-core/src/main/java/liquibase/Liquibase.java
Labels: StatusDiscovery
