Repository liquibase/liquibase, pull requests merged in 2020-10, with the labels that each got.

#1286 Fix usage of AntTaskLogger
  liquibase-core/src/main/java/liquibase/integration/ant/AntTaskLogService.java
  liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
Labels: DBAll, ImpactMedium, IntegrationAnt, Severity3, StatusActive, Target4.0.1, Target4.1.2, TypeBug

#1285 Remove deprecated code in Ant tasks
  liquibase-core/src/main/java/liquibase/integration/ant/AbstractDatabaseDiffTask.java
  liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
  liquibase-core/src/main/java/liquibase/integration/ant/DiffDatabaseToChangeLogTask.java
  liquibase-core/src/main/java/liquibase/integration/ant/GenerateChangeLogTask.java
  liquibase-core/src/test/resources/liquibase/integration/ant/ChangeLogSyncTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DBDocTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseRollbackFutureTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseRollbackTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseUpdateTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseUpdateTestingRollbackTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DiffDatabaseTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DiffDatabaseToChangeLogTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/DropAllTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/GenerateChangeLogTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/MarkNextChangeSetRanTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/TagDatabaseTaskTest.xml
Labels: DBAll, ImpactMedium, IntegrationAnt, RiskMedium, Severity3, StatusActive, Target4.0.1, Target4.1.2, TypeEnhancement

#1502 Fix CockroachDB Tests
  .travis/databases.docker-compose.yml
  liquibase-core/src/main/java/liquibase/change/core/AddPrimaryKeyChange.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropUniqueConstraintGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/AddPrimaryKeyStatement.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/cockroachdb/CockroachDBIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/cockroachdb/rollback/rollbackable.changelog.xml
Labels: StatusDiscovery

#1437 Load a Database object from the diff operation into the current scope DAT-4673
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
  liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
Labels: StatusDiscovery
