Repository liquibase/liquibase, pull requests merged in 2020-03, with the labels that each got.

#1013 LB-6 ⁃ DAT-4104 Default MySQL driver check
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
Labels: Status:Discovery

#1018 Re-enable jacoco
  base.pom.xml
  liquibase-dist/pom.xml
Labels: Status:Discovery

#1032 Loaded changeSet proerties for rollbackOneChangeSetSQL
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetSQL.java
Labels: Status:Discovery

#1041 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Risk:Low, Status:Discovery

#1060 Configure travis on master branch
  .travis.yml
  .travis/databases.docker-compose.yml
  .travis/maven.settings.xml
  .travis/mysql-init.sql
  base.pom.xml
  ci/.github/workflows/maven.yml
  ci/config.yml
  liquibase-cdi/pom.xml
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin.xml
  liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.circleci.properties
  liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
  liquibase-maven-plugin/pom.xml
  pom.xml
Labels: StatusDiscovery

#1061 Fixing build
  ci/.github/workflows/maven.yml
  ci/config.yml
  liquibase-dist/pom.xml
Labels: StatusDiscovery
