Repository liquibase/liquibase, pull requests merged in 2021-06, with the labels that each got.

#1556 Override getResourceAccessor for Maven RegisterChangeLogCommand Fix formatting in file DAT-6038
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRegisterChangeLogMojo.java
Labels: StatusDiscovery

#964 Fix CORE-3455 + CORE-3555 load[Update]Data/column@defaultValue[XXX] was not used
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/AbstractTableChange.java
  liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-core/src/main/java/liquibase/change/ChangeWithColumns.java
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/change/core/LoadDataColumnConfig.java
  liquibase-core/src/main/java/liquibase/change/core/LoadUpdateDataChange.java
  liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/main/resources/liquibase/i18n/liquibase-core.properties
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataColumnConfigTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/LoadUpdateDataChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/exception/ValidationErrorsTests.groovy
  liquibase-core/src/test/groovy/liquibase/serializer/core/string/StringChangeLogSerializerTest.groovy
  liquibase-core/src/test/java/liquibase/snapshot/MockSnapshotGeneratorFactory.java
  liquibase-core/src/test/resources/liquibase/change/core/sample.data.with.emptys.csv
  liquibase-core/src/test/resources/liquibase/change/core/strings.csv
Labels: DBAll, IntegrationCLI, RiskLow, StatusActive, ThemeDBObjects, TypeBug

#1441 Fixed mysql merge columns query
  liquibase-core/src/main/java/liquibase/change/core/MergeColumnChange.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/mergeColumns/mariadb.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/mergeColumns/mysql.sql
Labels: DBMySQL, ImpactMedium, IntegrationCLI, RiskMedium, Severity3, StatusActive, TypeBug

#1843 [LB-704] fixed generating sequences for postgre versions prior to 10
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Labels: DBPostgres, ImpactLow, IntegrationAny, RiskMedium, Severity3, StatusDiscovery, StatusReadyForHandoff, TypeBug
