Repository liquibase/liquibase, pull requests merged in 2021-07, with the labels that each got.

#1869 HubUpdater releases lock even though registration is skipped
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
Labels: InSprint, NoManualTesting, StatusActive, SyncTicket

#1952 Improve ConfigurationValueProvider performance
  liquibase-core/src/main/java/liquibase/configuration/AbstractMapConfigurationValueProvider.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGeneratorPostgres.java
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.snapshot.SnapshotGenerator
  liquibase-core/src/test/groovy/liquibase/configuration/core/MapConfigurationValueProviderTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
Labels: StatusActive, SyncTicket

#1963 Allow empty string for defaultValue attribute
  liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGenerator.java
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
Labels: StatusActive, SyncTicket

#1939 Restore update testing rollback command
  liquibase-core/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy
Labels: StatusActive, SyncTicket

#1943 Reintroduce support for "-D" arguments in CLI
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: DocRequired, StatusActive, SyncTicket

#1883 Preserve "serial" and "bigserial" if liquibase.convertDataTypes=false
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
Labels: StatusActive, SyncTicket

#1784 Added supports method to DatabaseConnection
  liquibase-core/src/main/java/liquibase/database/ConnectionServiceFactory.java
  liquibase-core/src/main/java/liquibase/database/DatabaseConnection.java
  liquibase-core/src/main/java/liquibase/executor/Executor.java
  liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
  liquibase-core/src/test/java/liquibase/database/ConnectionServiceFactoryTest.java
  liquibase-core/src/test/java/liquibase/executor/ExecutorServiceTest.java
  liquibase-core/src/test/java/liquibase/executor/jvm/JdbcExampleExecutor.java
  liquibase-core/src/test/resources/META-INF/services/liquibase.executor.Executor
Labels: BNoUpgradePath, DBMongoDB, ImpactHigh, IntegrationMaven, NoManualTesting, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug

#1593 NullPointerException when typo present in "changeSet" node
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
  liquibase-core/src/test/resources/liquibase/parser/core/yaml/typoChangeLog.yaml
Labels: DBAll, ImpactLow, IntegrationAny, RiskMedium, Severity3, StatusActive, SyncTicket, TypeEnhancement, TypeTestUnit

#1592 Add a validation error to fix #1591
  liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-core/src/test/groovy/liquibase/change/custom/CustomChangeWrapperTest.groovy
Labels: DBAll, ImpactLow, IntegrationAny, Severity3, StatusActive, SyncTicket, TypeBug, TypeTestUnit

#1878 Class cast exception in standard lock service
  liquibase-core/pom.xml
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-core/src/test/java/liquibase/lockservice/StandardLockServiceTest.java
Labels: StatusActive, SyncTicket

#1412 Fixes #1411 by adding a separate query fr DB2 on AS400
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: BNoUpgradePath, DBDB2i, ImpactLow, IntegrationAny, NoManualTesting, RiskLow, Severity3, StatusActive, SyncTicket, TypeBug

#1875 Firebird3Database supports true Boolean, so isNumericBoolean should return false.
  liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/UnlockDatabaseChangeLogExecuteTest.java
Labels: NoManualTesting, StatusActive, SyncTicket

#1471 Fix logicalFilePath not being serialized - Fixes 1234
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
Labels: DBMSSQLServer, ImpactLow, IntegrationMaven, RiskMedium, StatusActive, SyncTicket, TypeBug

#1513 fix #1106: added symbols and Tests
  liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
  liquibase-core/src/test/groovy/liquibase/util/SqlParserTest.groovy
Labels: DBOracle, ImpactLow, IntegrationAny, NoManualTesting, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug

#1563 Fix #1562 invalid update sql generated for hsql
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java
  liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsqlTest.groovy
Labels: DBHSQLDB, IntegrationAny, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug

#1877 No need to escape question marks in Postgresql
  liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java
Labels: StatusActive, SyncTicket

#1885 Do not worry about FileSystemAlreadyExistsException errors
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Labels: NoManualTesting, StatusActive, SyncTicket

#1798 relative bug fix for sql files
  liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy
  liquibase-core/src/test/resources/com/example/my-logic.sql
Labels: DBOracle, ImpactMedium, IntegrationAny, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug
