Repository liquibase/liquibase, pull requests merged in 2021-01, with the labels that each got.

#1612 Updated snakeyaml to 1.27
  base.pom.xml
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangeLogCommand.java
Labels: StatusDiscovery

#1611 Updated headless property messaging
  liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
Labels: StatusDiscovery

#1003 CORE-3594 Automatic dropping of default values on MS SQL
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropColumnGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/DropColumnGeneratorTest.java
Labels: DBMSSQLServer, IntegrationAny, RiskMedium, StatusConditioning, Target4.1.2, Target4.2.x, ThemeDBObjects, TypeBug

#942 Modify SetColumnRemarks support for mysql. The original code does not support mysql modification notes
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-core/src/main/java/liquibase/change/core/SetColumnRemarksChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/SetColumnRemarksStatement.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.0.xsd
  liquibase-core/src/test/java/liquibase/statement/core/SetColumnRemarksStatementTest.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/setColumnRemarks/mariadb.sql
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/setColumnRemarks/mysql.sql
Labels: DBMySQL, IntegrationAny, RiskMedium, StatusConditioning, Target4.2.x, ThemeDBObjects, TypeBug

#1078 Fix HistoryCommandTest to run on systems having a non-US default locale
  liquibase-core/src/test/groovy/liquibase/command/core/HistoryCommandTest.groovy
Labels: DBAll, IntegrationCLI, RiskLow, StatusConditioning, Target4.1.2, Target4.2.x, ThemeInternals, TypeBug

#1629 Include existing dropPrimaryKey.dropIndex attribute in xsd
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd
Labels: DBAll, ImpactLow, IntegrationAny, Reproduced, Severity3, StatusDiscovery, Target4.3.0, TypeBug

#1642 Add deprecated LogFactory.getInstance() to smooth upgrade to 4.x
  liquibase-core/src/main/java/liquibase/logging/LogFactory.java
  liquibase-core/src/test/groovy/liquibase/logging/LogFactoryTest.groovy
Labels: StatusDiscovery
