Repository liquibase/liquibase, pull requests merged in 2021-02, with the labels that each got.

#1653 Hide passwords from generated URLs
  liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-core/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy
Labels: StatusDiscovery

#1665 Improved SpringResourceAccessor
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Labels: DBAll, IntegrationMaven, IntegrationSpringboot, RiskMedium, Severity2, StatusDiscovery, TypeBug

#1664 Support drivers that return a LocalDateTime for dates
  liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
Labels: DBMySQL, ImpactHigh, IntegrationAny, RiskMedium, Severity2, TypeBug

#1448 liquibase.sqlplus.path line in liquibase/examples/xml/liquibase.sqlplus.conf should be commented out
  liquibase-dist/src/main/archive/examples/xml/liquibase.sqlplus.conf
Labels: StatusActive

#1098 usePreparedStatement attribute in loadData element has no effect
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
Labels: DBMSSQLServer, IntegrationMaven, RiskLow, StatusActive, Target4.3.1, ThemeChangeTypes, TypeBug

#1698 Use classpath*: for searching in SpringResourceAccessor
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
Labels: StatusDiscovery

#1688 includeAll not working with some ClassLoaderResourceAccessor
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Labels: DBAll, ImpactMedium, IntegrationAny, RiskMedium, Severity3, StatusDiscovery, TypeBug
