Repository liquibase/liquibase, pull requests merged in 2021-08, with the labels that each got.

#1515 MySQL reserved word update
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
Labels: DBMySQL, ImpactLow, IntegrationMaven, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug

#1791 fix loading clob data into postgres
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
Labels: DBPostgres, ImpactLow, IntegrationCLI, IntegrationSpringboot, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug

#1713 handle empty lines at start of formatted sql
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: DBAll, ImpactLow, IntegrationAny, RiskLow, Severity3, StatusActive, SyncTicket, TypeEnhancement

#1361 Fix synchronization in ChangeLogHistoryServiceFactory.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java
Labels: BNoUpgradePath, DBH2, DBOracle, DBPostgres, ImpactMedium, IntegrationMaven, NoManualTesting, RiskMedium, Severity3, StatusActive, SyncTicket, TypeBug

#1602 Changed from RawSqlStatement to UpdateStatement
  liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
Labels: DBAll, ImpactLow, IntegrationAny, NoManualTesting, Severity3, StatusActive, StatusDiscovery, SyncTicket, TypeBug

#1771 Fix UniqueConstraint snapshot query on db2z
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-core/src/test/java/liquibase/database/core/DB2zDatabaseTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/db2z/DB2zIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/db2z/complete/included.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/db2z/complete/renamed.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/db2z/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/db2z/rollback/rollbackable.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.jenkins.properties
  liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.properties
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, IntegrationMaven, DBDB2Z, NoManualTesting, SyncTicket

#1968 Manage parent directory relative to changelog in IncludeAll
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-core/src/test/groovy/liquibase/resource/ClassLoaderResourceAccessorTest.groovy
  liquibase-core/src/test/groovy/liquibase/resource/FileSystemResourceAccessorTest.groovy
  liquibase-core/src/test/resources/com/example/directory/file-in-directory.txt
Labels: StatusActive, NoManualTesting, SyncTicket

#1768 Ensure that the root scope is initialized correctly regardless of whether a scope manager has been configured yet or not.
  liquibase-core/src/main/java/liquibase/Scope.java
Labels: TypeBug, StatusActive, Severity3, ImpactMedium, IntegrationSpringboot, NoManualTesting, SyncTicket

#1534 [CORE-1254] Fix OSGiResourceAccessor failing due to javax.activation
  liquibase-core/pom.xml
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactMedium, DBAll, IntegrationAny, NoManualTesting, BNoUpgradePath, SyncTicket

#1992 Fix createSequence for h2 when dataType is specified
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Labels: StatusActive, SyncTicket

#1991 Improve synchronization of LockServiceFactory reset
  liquibase-core/src/main/java/liquibase/lockservice/LockServiceFactory.java
  liquibase-core/src/test/java/liquibase/lockservice/LockServiceFactoryTest.java
Labels: StatusActive, NoManualTesting, SyncTicket

#1893 CLI no longer reading defaultsFile from classpath
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-core/src/main/java/liquibase/configuration/core/DefaultsFileValueProvider.java
  liquibase-core/src/test/groovy/liquibase/configuration/core/DefaultsFileValueProviderTest.groovy
Labels: StatusActive, SyncTicket

#1864 Postgresql: Preserve existing search_path when setting the defaultSchemaName
  liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
  liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/CreateProcedureGeneratorTest.groovy
Labels: StatusActive, StatusDiscovery, SyncTicket, ReleaseMajor

#1860 More efficient XML resource loading
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
Labels: StatusActive, SyncTicket

#1880 Fixed postgresql addPrimaryKey cluster handling
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddPrimaryKeyGenerator.java
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
Labels: StatusActive, SyncTicket

#1837 Get Set deleteCascade for serializer mapping
  liquibase-core/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/AddForeignKeyConstraintChangeTest.groovy
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, DBOracle, DBMSSQLServer, IntegrationCLI, SyncTicket

#1845 Add support for changeset ids and authors with spaces in formattedsql changelogs.
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
Labels: TypeEnhancement, StatusActive, StatusDiscovery, Severity4, ImpactLow, DBAll, IntegrationAny, SyncTicket, DocRequired

#1468 Fixes Postgresql bit column support
  liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-core/src/test/java/liquibase/datatype/BooleanTypeTest.java
Labels: TypeBug, StatusActive, Severity3, ImpactLow, DBPostgres, IntegrationMaven, SyncTicket

#1590 [CORE-3028] fixed usage of computed values in prepared insert/update changes
  liquibase-core/src/main/java/liquibase/statement/InsertExecutablePreparedStatement.java
  liquibase-core/src/main/java/liquibase/statement/UpdateExecutablePreparedStatement.java
  liquibase-core/src/test/java/liquibase/statement/InsertExecutablePreparedStatementTest.java
  liquibase-core/src/test/java/liquibase/statement/UpdateExecutablePreparedStatementTest.java
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactMedium, DBAll, DBMariaDB, IntegrationAny, TypeTestUnit, BNoUpgradePath, SyncTicket, ReleaseMajor

#1377 Fail when creating a Scope with a null-parent #1354.
  liquibase-core/src/main/java/liquibase/Scope.java
  liquibase-core/src/test/groovy/liquibase/ScopeTest.groovy
Labels: TypeBug, StatusActive, Severity3, ImpactLow, DBAll, IntegrationAny, NoManualTesting, SyncTicket

#2043 Handle issues with MariaDB/Clustrix DAT-7879
  liquibase-core/src/main/java/liquibase/database/core/MariaDBDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/CachedRow.java
Labels: ReleaseMajor
