Repository liquibase/liquibase, pull requests merged in 2021-12, with the labels that each got.

#2225 Use lowercase sys.synonyms in mssql.
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
Labels: StatusActive, SyncTicket

#2073 Fix load relative file
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, DBAll, DBH2, IntegrationAny, BBroad, SyncTicket

#2066 Directory with dot not recognized correctly when loading data (breaks migration from 3.x to 4.x)
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/resource/ClassLoaderResourceAccessorTest.groovy
Labels: TypeBug, StatusActive, RiskMedium, Severity4, ImpactLow, DBAll, DBH2, IntegrationAny, BBroad, SyncTicket

#2228 Handle the fact that FK names are not always unique.
  liquibase-core/src/main/java/liquibase/diff/compare/core/ForeignKeyComparator.java
Labels: StatusActive, SyncTicket

#2244 Recognize jdbc:edb urls as a distinct EnterpriseDB dialect
  liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.database.Database
  liquibase-core/src/test/java/liquibase/change/ChangeParameterMetaDataTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/UnlockDatabaseChangeLogExecuteTest.java
Labels: StatusActive, SyncTicket

#2081 [2054] fix OSGI support (manifest, class loading)
  liquibase-core/pom.xml
  liquibase-core/src/main/java/liquibase/Scope.java
  liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-core/src/main/java/liquibase/osgi/Activator.java
  liquibase-core/src/main/java/liquibase/util/LiquibaseUtil.java
  liquibase-core/src/main/java/liquibase/util/OsgiUtil.java
Labels: TypeBug, StatusActive, RiskMedium, Severity4, ImpactLow, DBAll, IntegrationCDI, SyncTicket

#2071 1054 add not null constraint causes data too long exception
  liquibase-core/src/main/java/liquibase/change/core/AddNotNullConstraintChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/AddNotNullConstraintChangeTest.groovy
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, DBMySQL, IntegrationMaven, IntegrationSpringboot, IntegrationAny, BKeyPlatform, SyncTicket
