Repository liquibase/liquibase, pull requests merged in 2021-04, with the labels that each got.

#1367 #1366 DateTimeType.java:38 NullPointerException
  liquibase-core/src/main/java/liquibase/datatype/core/DateTimeType.java
Labels: DBAll, ImpactLow, IntegrationAny, Severity3, StatusActive, TypeBug

#1758 Handle possible null objects in the reference or comparison lists LB 1115
  liquibase-core/src/main/java/liquibase/diff/compare/core/IndexComparator.java
Labels: StatusDiscovery

#1733 With diffToChangeLog, insert Columns after the last Table, and before any objects which depend on them LB-1722
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
Labels: StatusDiscovery

#1744 Improve FileSystemResourceAccessor on linux
  liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: StatusDiscovery

#1788 Fix changeLogSync issue when Hub settings exist DAT-6938
  liquibase-core/src/main/java/liquibase/Liquibase.java
Labels: StatusActive

#1800 Adding image for readme.md
  Liquibase.png
Labels: StatusDiscovery

#1796 Migrate Travis to GH Actions
  .github/workflows/build.yml
  .travis.yml.old
  base.pom.xml
  liquibase-cdi/src/test/java/liquibase/integration/cdi/SchemesCDIConfigBuilderTest.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-integration-tests/src/test/resources/jdbc-drivers/all/informix-11.50/ifxjdbc-3.50.JC3.jar
Labels: DBAll, ImpactHigh, IntegrationAny, Severity2, StatusDiscovery, TypeEnhancement

#1802 Update README.md
  README.md
Labels: StatusDiscovery

#1514 Issue-1483: Fixed wrongly generated PKs for PostgreSQL.
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/test/java/liquibase/database/core/PostgresDatabaseTest.java
Labels: DBPostgres, ImpactLow, IntegrationAny, RiskMedium, Severity3, StatusActive, TypeBug
