Repository liquibase/liquibase, pull requests merged in 2021-03, with the labels that each got.

#1650 Fixed the issue that was preventing dropAll from working in Postgres (#1212)
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
Labels: DBPostgres, ImpactMedium, IntegrationAny, RiskMedium, Severity3, StatusActive, TypeBug

#1661 Capture log messages at the current log level and truncate if necessary DAT-6366
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/DropAllCommand.java
  liquibase-core/src/main/java/liquibase/configuration/HubConfiguration.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/main/java/liquibase/hub/listener/HubChangeExecListener.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/logging/core/BufferedLogService.java
  liquibase-core/src/test/groovy/liquibase/logging/core/BufferedLogServiceTest.groovy
Labels: StatusDiscovery

#1138 [1133] Add changelogSyncToTag and changelogSyncToTagSQL commands
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/integration/ant/ChangeLogSyncTask.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/resources/liquibase/i18n/liquibase-commandline-helptext.xml
  liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy
  liquibase-core/src/test/groovy/liquibase/integration/ant/test/LiquibaseTagExistsCondition.groovy
  liquibase-core/src/test/resources/liquibase/integration/ant/ChangeLogSyncTaskTest.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/changelog/simple-changelog.xml
  liquibase-core/src/test/resources/liquibase/integration/ant/test/antlib.xml
  liquibase-core/src/test/resources/liquibase/tagged-changelog.xml
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncSQLMojo.java
Labels: DBAll, IntegrationAny, RiskMedium, StatusActive, Target4.3.1, ThemeCommands

#1724 Default ConsoleUIService.allowPrompt to false LB-1220
  liquibase-core/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/integration/servlet/LiquibaseServletListener.java
  liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
  liquibase-core/src/test/groovy/liquibase/ui/ConsoleUIServiceTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: StatusDiscovery

#1717 Modified 401 message coming back from Hub DAT-6465
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
Labels: StatusDiscovery

#1772 Correctly update the changeLogId in the DatabaseChangeLog object at the end of registration DAT 6842
  liquibase-core/src/main/java/liquibase/changelog/ChangelogRewriter.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeLogRewriterTest.groovy
Labels: StatusDiscovery
