Repository liquibase/liquibase, pull requests merged in 2021-05, with the labels that each got.

#1506 Resolve issues with being able to generate changelogs against DB2 on z/OS
  liquibase-core/src/main/java/liquibase/database/core/Db2zDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: ImpactLow, IntegrationAny, RiskMedium, Severity3, StatusActive, TypeBug

#1213 Added conditional check to make onlyUpdate flag work for Postgres DB LB-316
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgres.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgresTest.java
Labels: DBPostgres, ImpactLow, IntegrationGradle, IntegrationSpringboot, RiskMedium, StatusActive, ThemeInternals, TypeBug

#1844 strip password from jdbc url DAT-6808
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-core/src/main/java/liquibase/util/CollectionUtil.java
  liquibase-core/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy
Labels: DBOracle, ImpactMedium, IntegrationAny, RiskMedium, Severity3, StatusDiscovery, TypeBug

#1853 Expose changeset and resourceAccessor readers
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
Labels: StatusDiscovery
