Repository liquibase/liquibase, pull requests merged in 2021-11, with the labels that each got.

#1941 Fix sqlFile encoding attribute handling
  liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd
Labels: StatusActive, SyncTicket

#1817 Added MSSQLDatabase specific error evaluation when creating lock table
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: TypeBug, StatusActive, RiskHigh, Severity3, ImpactLow, DBMSSQLServer, IntegrationCDI, SyncTicket

#1970 Improve addColumn handling in SQLite
  base.pom.xml
  liquibase-core/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/main/java/liquibase/change/core/DropColumnChange.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/JdbcSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGeneratorSQLite.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CopyRowsGenerator.java
Labels: StatusActive, SyncTicket

#2185 'Validate' exit code should be 1 on error
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: StatusActive, SyncTicket, ReleaseMajor

#2180 Support Mysql Function Indexes
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: StatusActive, SyncTicket

#2167 Fixed --verbose flag setup in unexpected-changesets
  liquibase-core/src/main/java/liquibase/command/core/UnexpectedChangesetsCommandStep.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/unexpectedChangesets.test.groovy
Labels: StatusActive, SyncTicket

#2021 Do not escape the backslash in values stored in the objects.
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataChangeGenerator.java
Labels: StatusActive, SyncTicket

#2020 Improve nested changelog precondition handling
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/precondition/core/PreconditionContainer.java
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy
  liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
Labels: StatusActive, SyncTicket, ReleaseMajor

#2168 YAMLChangelogParser: Fix parsing logic around changeLogId in a Map
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
Labels: StatusActive, SyncTicket

#2189 Fix handling of relativeToChangelogFile with classpath: prefixed changelogs
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: StatusActive, SyncTicket

#1520 Flag to Control Logging of SQL Statements and SQL Execution Output
  liquibase-core/src/main/java/liquibase/configuration/ConfigurationValueConverter.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/integration/ant/AntTaskLogger.java
  liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
  liquibase-core/src/main/java/liquibase/logging/core/BufferedLogger.java
  liquibase-core/src/main/java/liquibase/logging/core/CompositeLogger.java
  liquibase-core/src/main/java/liquibase/logging/core/JavaLogger.java
  liquibase-core/src/main/java/liquibase/sql/SqlConfiguration.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations
  liquibase-core/src/test/groovy/liquibase/configuration/ConfigurationValueConverterTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLogService.java
Labels: StatusActive, SyncTicket, DocRequired

#2216 Fix log message for version missmatch
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
Labels: TypeBug, StatusActive, Severity3, ImpactLow, DBPostgres, IntegrationSpringboot, BKeyPlatform, SyncTicket

#2015 look for jars in local ./liquibase_libs
  liquibase-dist/src/main/archive/liquibase
  liquibase-dist/src/main/archive/liquibase.bat
Labels: StatusActive, SyncTicket

#2215 Improve mysql loadData performance
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
Labels: StatusActive, SyncTicket

#2059 fix support for custom DB2Database implementations
  liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, DBDB2LUW, IntegrationAny, BKeyPlatform, SyncTicket
