Repository liquibase/liquibase, pull requests merged in 2022-03, with the labels that each got.

#2569 Make FormattedSqlChangeLogParser reusable
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
Labels: SafeToBuild

#2377 issue #2375 update statement when onlyUpdate is false;
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java
  liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsqlTest.groovy
Labels: SafeToBuild

#1908 CockroachDB use "serial" datatypes for version < 21.2, "generated by default" for version >= 21.2
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/test/groovy/liquibase/database/core/CockroachDatabaseTest.groovy
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java
Labels: TypeBug, Severity3, ImpactLow, DBCockroachDB, IntegrationAny, SafeToBuild

#2135 Fix #2133 and preserve CORE-2971 (Liquibase endDelimiter does not work after upgrading from 3.10.x to 4.x)
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug, RiskMedium, StatusConditioning, Severity2, ImpactMedium, DBOracle, BNoUpgradePath, BKeyPlatform, BBroad, SyncTicket

#2318 Run automated tests in JDK17 rather than 16
  .github/workflows/build.yml
  liquibase-core/pom.xml
  liquibase-dist/src/main/install4j/liquibase.install4j
  pom.xml
Labels: StatusConditioning, SyncTicket

#2387 Fix date/time loadData handling
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/util/ISODateFormat.java
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/ISODateFormatTest.groovy
  liquibase-core/src/test/resources/liquibase/change/core/sample.data.temporal.csv
Labels: SafeToBuild

#2529 Add uniqueConstraintExists precondition (#1881)
  liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java
  liquibase-core/src/main/java/liquibase/precondition/PreconditionLogic.java
  liquibase-core/src/main/java/liquibase/precondition/core/AndPrecondition.java
  liquibase-core/src/main/java/liquibase/precondition/core/NotPrecondition.java
  liquibase-core/src/main/java/liquibase/precondition/core/OrPrecondition.java
  liquibase-core/src/main/java/liquibase/precondition/core/UniqueConstraintExistsPrecondition.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/util/SqlUtil.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.precondition.Precondition
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.8.xsd
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-next.xsd
  liquibase-core/src/test/java/liquibase/test/DiffResultAssert.java
  liquibase-core/src/test/java/liquibase/test/SnapshotAssert.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/cockroachdb/CockroachDBIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/h2/H2IntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/mariadb/MariaDBIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/mysql/MySQLIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
Labels: IntegrationAny, SafeToBuild

#2538 Add test for TableExistsPrecondition
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java
Labels: DBPostgres, ver4.7.1, SafeToBuild, OSMac

#2666 Fix manifest location in jar during re-version.sh
  .github/util/re-version.sh
  .github/workflows/create-release.yml
Labels: TypeBug

#2691 fix invalid JSON in example-changelog.json (DAT-9893)
  liquibase-core/src/main/resources/liquibase/examples/json/example-changelog.json
Labels: daily_review
