Repository liquibase/liquibase, pull requests merged in 2022-12, with the labels that each got.

#3497 Simplify assert calls and replaced with simpler and equivalent calls.
  liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java
  liquibase-core/src/test/java/liquibase/changelog/ChangeLogIteratorTest.java
  liquibase-core/src/test/java/liquibase/database/core/PostgresDatabaseTest.java
  liquibase-core/src/test/java/liquibase/executor/jvm/JdbcExecutorTest.java
  liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java
  liquibase-core/src/test/java/liquibase/integration/servlet/LiquibaseServletListenerTest.java
  liquibase-core/src/test/java/liquibase/lockservice/LockServiceFactoryTest.java
  liquibase-core/src/test/java/liquibase/precondition/PreconditionFactoryTest.java
  liquibase-core/src/test/java/liquibase/serializer/ChangeLogSerializerFactoryTest.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/SqlGeneratorFactoryTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/MssqlIntegrationTest.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojoTest.java
Labels: SafeToBuild, TypeTest, sprint2022-39

#3518 Avoid ClassCastException when loading LogService from Scope
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Labels: SafeToBuild, sprint2022-40

#3559 Adds exclusions for mariadb newly added waffle dependency.
  liquibase-dist/pom.xml
Labels: sprint2022-40

#3373 Remove unnecessary local variables that add nothing to the comprehensibility of a method.
  liquibase-core/src/main/java/liquibase/command/core/ExecuteSqlCommand.java
  liquibase-core/src/main/java/liquibase/database/core/H2Database.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/AbstractChangeGenerator.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorSQLite.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
Labels: SafeToBuild, autocandidate, sprint2022-38, TypeRefactor

#3379 Allow loading gzipped data files
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/sample.data1.csv.gz
Labels: TypeEnhancement, featureLoadData, SafeToBuild, sprint2022-38

#3374 Use try-with-resources Statement when is possible.
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/dbdoc/HTMLListWriter.java
  liquibase-core/src/main/java/liquibase/dbdoc/HTMLWriter.java
  liquibase-core/src/main/java/liquibase/integration/commandline/ChangeExecListenerUtils.java
  liquibase-core/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGenerator.java
  liquibase-core/src/test/java/liquibase/NoJavaSpecificCodeTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/AbstractLiquibaseMojoTest.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGeneratorSnowflake.java
Labels: SafeToBuild, autocandidate, sprint2022-38, TypeRefactor

#3517 Included SQL to return unique constraints for Sybase
  liquibase-core/src/main/java/liquibase/database/core/SybaseDatabase.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/test/groovy/liquibase/database/core/SybaseDatabaseTest.groovy
Labels: TypeBug, SafeToBuild, autocandidate, sprint2022-39

#3428 Add varbinary and binary support for DB2 - fixes #3408
  liquibase-core/pom.xml
  liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java
  liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
  liquibase-core/src/test/java/liquibase/datatype/core/BlobTypeTest.java
Labels: TypeBug, SafeToBuild, autocandidate, sprint2022-38

#1399 Add support for block comment rollback commands on SQL changesets
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeEnhancement, RiskMedium, Severity3, ImpactHigh, DBAll, IntegrationAny, SafeToBuild, featureRollback, sprint2022-38

#3390 Fix getting default schema issue for firebird
  .github/workflows/build.yml
  liquibase-core/src/main/java/liquibase/database/core/FirebirdDatabase.java
  liquibase-core/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-extension-testing/pom.xml
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/FirebirdTestSystem.java
  liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/firebird/FirebirdIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/firebird/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/firebird/rollback/rollbackable.changelog.xml
  pom.xml
Labels: DBFirebird, defaultSchema, sprint2022-38

#3372 Allow primary key on addColumn for H2
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
Labels: TypeEnhancement, DBH2, SafeToBuild, autocandidate, sprint2022-38

#3362 Fix generatedSQL logic to allow setting up a function as a default value for MySQL version 8
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorMySQL.java
  liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/AddDefaultValueGeneratorMySQLTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Labels: TypeBug, DBMySQL

#3397 #1290: Forbid empty changeSet id and author
  liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
  liquibase-core/src/test/java/liquibase/changelog/visitor/ValidatingVisitorTest.java
Labels: TypeBug, hacktoberfest, SafeToBuild, autocandidate, sprint2022-38

#944 Added support for COMPUTED values inside CSV files for loadData change
  liquibase-core/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-core/src/main/java/liquibase/statement/UpdateExecutablePreparedStatement.java
  liquibase-core/src/test/java/liquibase/statement/ExecutablePreparedStatementBaseMock.java
  liquibase-core/src/test/java/liquibase/statement/ExecutablePreparedStatementBaseTest.java
  liquibase-core/src/test/java/liquibase/statement/InsertExecutablePreparedStatementTest.java
  liquibase-core/src/test/java/liquibase/statement/UpdateExecutablePreparedStatementTest.java
  liquibase-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/computedValueData.csv
  liquibase-integration-tests/src/test/resources/changelogs/common/updatedComputedValueData.csv
Labels: TypeBug, RiskMedium, Severity3, DBAll, ThemeChangeTypes, IntegrationAny, featureLoadData, SafeToBuild, autocandidate, criticalityBuilder, complexityGlobal

#3108 Additional (optional) tableType attribute on the CreateTableChange
  liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/CreateTableStatement.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
Labels: TypeEnhancement, DBSnowflake, ReleaseMajor, SafeToBuild, autocandidate, sprint2022-39

#3244 Include "path" in databasechangelog's description column for all change types with "path" attributes
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/sdk/resource/MockResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/change/AbstractChangeTest.groovy
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/MarkChangeSetRanGeneratorTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/pathChangeLog.xml
Labels: TypeEnhancement, DATABASECHANGELOG, SafeToBuild, sprint2022-38

#3377 #1466: Add ignore:true changeset attribute to Formatted SQL changeLogs
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeEnhancement, hacktoberfest, SafeToBuild, autocandidate, formattedSQL, sprint2022-38
