Repository liquibase/liquibase, pull requests merged in 2022-05, with the labels that each got.

#2554 liquibase checks run maven goal (DAT-8375)
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksShowMojo.java
Labels: SquadPro

#2772 Do not throw a confusing error if a datatype specified as a changelog parameter is not expanded
  liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java
  liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Labels: TypeEnhancement, autocandidate

#2630 Fixed NullPointerException in SecureLogFilter.isLoggable
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/logging/core/DefaultLogMessageFilter.java
  liquibase-core/src/test/java/liquibase/integration/commandline/MainTest.java
Labels: DBPostgres, IntegrationCLI, SafeToBuild, ver4.8.0, autocandidate

#2793 Upgraded jaxb libraries to the newest 2.3.x versions
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin.xml
  liquibase-dist/src/main/maven/release.pom.xml
  liquibase-maven-plugin/pom.xml
  pom.xml
Labels: autocandidate

#2778 Fixed SQLite not correctly snapshotting tables with underscores in the name
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug, DBSQLLite, autocandidate

#2599 Added new liquibase.monitorPerformance setting for CLI
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-core/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: ManualTest, featureMonitoring

#2830 Fixed local XSD lookup
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/LiquibaseEntityResolverTest.groovy
Labels: autocandidate

#2597 Refactor start-h2 logic
  README.md
  liquibase-core/src/main/java/liquibase/command/core/StartH2CommandStep.java
  liquibase-core/src/main/java/liquibase/example/StartH2Main.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-core/src/main/resources/liquibase/examples/start-h2
  liquibase-core/src/main/resources/liquibase/examples/start-h2.bat
  liquibase-dist/src/main/archive/GETTING_STARTED.txt
  liquibase-dist/src/main/archive/examples/start-h2
  liquibase-dist/src/main/archive/examples/start-h2.bat
  liquibase-dist/src/main/assembly/assembly-bin.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/initstartH2.test.groovy
Labels: DBH2, ManualTest

#2836 Support default values in the format `(0)::real`
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/test/groovy/liquibase/snapshot/jvm/ColumnSnapshotGeneratorTest.groovy
Labels: DBPostgres

#2812 Fix handling of defaultSchemaName on Postgresql
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
Labels: TypeBug, DBPostgres, ManualTest, defaultSchema

#2686 Introduce generateStatementsFromRows for extensions
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
Labels: TypeEnhancement, SafeToBuild, autocandidate

#2725 The type of attributes "ordered" and "cycle" should be boolean
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-next.xsd
Labels: ReleaseMajor, SafeToBuild, XSD, TypeDataType, ver4.9.1, autocandidate

#2758 Spring Boot: better support relativeToChangelogfile when ResourceLoaders return FilteredReactiveWebContextResources
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
Labels: DBPostgres, IntegrationSpringboot, daily_review, SafeToBuild, ver4.9.1, FilePath

#2565 Fix ForeignKeyComparator when foreign key table is not known
  liquibase-core/src/main/java/liquibase/diff/compare/core/ForeignKeyComparator.java
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Labels: TypeBug, DBPostgres, IntegrationCLI, SafeToBuild, autocandidate

#2595 Fix BLOBs in loadData for MySQL/MariaDB
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
Labels: TypeBug, DBMariaDB, IntegrationMaven, OSLinux, SafeToBuild, ver4.6.2, ver4.8.0, TypeIncorrectSQL, autocandidate

#2571 Add logic to Derby.getDefaultDriver() to check for availability of different driver classes
  liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
Labels: ManualTest

#2785 Change value modifier to make StandardLockService extendable for future extension
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: Extensions, SafeToBuild, autocandidate, DBKeyspace

#2588 Fix addAutoIncrement startValue and incrementBy support on postgresql
  liquibase-core/src/main/java/liquibase/change/core/AddAutoIncrementChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-next.xsd
Labels: TypeBug, DBPostgres, ReleaseMajor, autocandidate

#2871 Add liquibase.showBanner global configuration setting
  liquibase-core/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-core/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy
Labels: TypeEnhancement, showBanner

#2524 Not possible to provide changelogs from outside classpath
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
Labels: IntegrationMaven, IntegrationSpringboot, SafeToBuild, ver4.2.0, autocandidate

#2781 Fix #2780: AddColumnChange with schema and NOT NULL constraint fails
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
Labels: DBH2, IntegrationSpringboot, OSWindows, SafeToBuild, ver4.9.1, autocandidate
