Repository liquibase/liquibase, pull requests merged in 2022-04, with the labels that each got.

#2684 Make SnapshotCommandStep use the code from InternalSnapshotCommand directly DAT-9624
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-core/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java
  liquibase-core/src/main/java/liquibase/command/AbstractDatabaseCommandStep.java
  liquibase-core/src/main/java/liquibase/command/CommandResultsBuilder.java
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
  liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/resource/CompositeResourceAccessor.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshot.test.groovy
Labels: daily_review

#2667 Run build & test against JDK 18
  .github/workflows/build.yml
Labels: ignore-release-notes, autocandidate

#2763 Correctly handle null class package names in the logging system
  liquibase-core/src/main/java/liquibase/logging/core/JavaLogService.java
  liquibase-core/src/test/groovy/liquibase/logging/core/JavaLogServiceTest.groovy
Labels: TypeBug, autocandidate

#2767 Fix EnterpriseDB database recognition
  liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java
  liquibase-core/src/test/groovy/liquibase/database/core/EnterpriseDBDatabaseTest.groovy
Labels: dbEDB, autocandidate

#2636 Fix start failure with Nullpointed exception when Environment contains empty string Key (fix Issue 2631)
  liquibase-cli/src/main/java/liquibase/integration/commandline/CommandLineArgumentValueProvider.java
  liquibase-core/src/main/java/liquibase/configuration/AbstractMapConfigurationValueProvider.java
  liquibase-core/src/test/groovy/liquibase/configuration/core/MapConfigurationValueProviderTest.groovy
Labels: TypeBug, DBHSQLDB, IntegrationMaven, SafeToBuild, ver4.8.0, OSMac, autocandidate

#2752 Fix createTable on Mysql not preserving primary key information when remarks also defined on the column
  liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-core/src/main/java/liquibase/statement/core/CreateTableStatement.java
Labels: TypeBug, autocandidate

#2789 Upgrade mariadb driver to 3.0.4
  liquibase-dist/pom.xml
  pom.xml
Labels: breaking-change, autocandidate

#2791 Upgraded oracle driver to 21.5.0.0
  liquibase-dist/pom.xml
  pom.xml
Labels: breaking-change, autocandidate

#2790 Upgraded mssql driver to 10.2.0
  liquibase-dist/pom.xml
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/MSSQLTestSystem.java
  pom.xml
Labels: breaking-change, autocandidate

#2797 Bump hsqldb from 2.4.0 to 2.5.2
  pom.xml
Labels: dependencies, autocandidate

#2801 Update .snyk
  .snyk
Labels: ignore-release-notes
