Repository liquibase/liquibase, pull requests merged in 2022-10, with the labels that each got.

#2134 fix: Use default localhost finder for MacOs - fix #2098
  liquibase-core/src/main/java/liquibase/util/NetUtil.java
  liquibase-core/src/test/groovy/liquibase/util/NetUtilTest.groovy
Labels: TypeEnhancement, Severity4, ImpactLow, DBAll, IntegrationAnt, SyncTicket, SafeToBuild, performance

#3264 Allow renameColumn on newer SQLite versions
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java
  liquibase-integration-tests/src/test/resources/changelogs/sqlite/complete/root.changelog.xml
Labels: TypeEnhancement, DBSQLLite, autocandidate

#3359 Upgrade snakeyaml maven reference from 1.32 to 1.33
  liquibase-dist/src/main/maven/release.pom.xml
Labels: dependencies, autocandidate
