Repository liquibase/liquibase, pull requests merged in 2022-07, with the labels that each got.

#1906 Use "numeric" (without parameters) data type in PostgreSQL
  liquibase-core/src/main/java/liquibase/datatype/core/NumberType.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/NumberTypeTest.groovy
Labels: TypeBug, Severity4, ImpactLow, DBOracle, DBPostgres, IntegrationAny, SafeToBuild, autocandidate, enabler

#3019 Force "json" resultset formats in Snowflake when running Java 17+
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/util/SystemUtil.java
  liquibase-core/src/test/groovy/liquibase/util/SystemUtilTest.groovy
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
Labels: DBSnowflake

#3016 warn if XSD version does not match build version in validate command (DAT-9874)
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/LiquibaseEntityResolverTest.groovy
Labels: XSD

#3037 Fixed Formatted SQL "property" parsing
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug, daily_review, autocandidate, formattedSQL, sprint2022-29

#3033 Improve connection exception by including underlying driver exception trace
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
Labels: TypeEnhancement, SafeToBuild, errorReporting, enabler, cloudGCP, sprint2022-29

#3009 Ensure Postgresql search_path entries are quoted correctly
  liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
Labels: TypeBug, DBPostgres, DBCockroachDB, DBRedshift, sprint2022-29

#3059 Fixed test failing in different timezones
  liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
Labels: TypeEnhancement, TypeTestUnit, SafeToBuild, autocandidate

#3026 Fixed autoIncrement incrementBy/startWith support in MySQL, H2, HSQLDB, and MariaDB
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/H2Database.java
  liquibase-core/src/main/java/liquibase/database/core/HsqlDatabase.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddAutoIncrementGeneratorMySQL.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: DBMySQL, DBH2, DBMariaDB, DBHSQLDB, autocandidate, ver4.10.0, sprint2022-29

#2990 Add Closeable/AutoCloseable on Database & interface
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/database/Database.java
  liquibase-core/src/main/java/liquibase/database/DatabaseConnection.java
  liquibase-core/src/main/java/liquibase/database/OfflineConnection.java
  liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
  liquibase-core/src/test/java/liquibase/database/AbstractJdbcDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/ConnectionServiceFactoryTest.java
  liquibase-core/src/test/java/liquibase/database/core/AbstractDb2DatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/DB2DatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/DB2zDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/DerbyDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/MSSQLDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/MySQLDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/OracleDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/PostgresDatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/UnsupportedDatabaseTest.java
Labels: TypeEnhancement, daily_review, SafeToBuild, autocandidate

#3057 Added liquibase.changelogParseMode setting
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java
  liquibase-core/src/main/java/liquibase/precondition/PreconditionLogic.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
  liquibase-core/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
  liquibase-core/src/test/groovy/liquibase/precondition/core/PreconditionContainerTest.groovy
  liquibase-core/src/test/resources/liquibase/registered-changelog.json
  liquibase-core/src/test/resources/liquibase/registered-changelog.yml
  liquibase-core/src/test/resources/liquibase/simple.json
  liquibase-core/src/test/resources/liquibase/test-changelog.json
  liquibase-core/src/test/resources/liquibase/test-changelog.yml
Labels: DocRequired, CodeDistro, marketingRequired, sprint2022-29

#3050 Split liquibase-core and liquibase-commercial jar files
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-core/src/main/resources/liquibase/examples/start-h2.bat
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/README.txt
  liquibase-dist/src/main/archive/liquibase
  liquibase-dist/src/main/archive/liquibase.bat
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
  liquibase-dist/src/main/assembly/assembly-bin-pro.xml
  liquibase-dist/src/main/assembly/assembly-bin.xml
  liquibase-integration-tests/setup/build.xml
  liquibase-integration-tests/setup/oracle/build.xml
  liquibase-integration-tests/src/test/resources/commandline/README.txt
  liquibase-integration-tests/src/test/resources/commandline/liquibase.h2.properties
  liquibase-integration-tests/src/test/resources/commandline/liquibase.mariadb.properties
  liquibase-integration-tests/src/test/resources/commandline/liquibase.mssql.properties
  liquibase-integration-tests/src/test/resources/commandline/liquibase.mysql.properties
  liquibase-integration-tests/src/test/resources/commandline/liquibase.oracle.properties
  liquibase-integration-tests/src/test/resources/commandline/liquibase.postgres.properties
  liquibase-maven-plugin/pom.xml
  liquibase-maven-plugin/src/main/maven/liquibase-deployment-pom.xslt
  liquibase-maven-plugin/src/main/maven/release.pom.xml
Labels: DocRequired, ReleaseMajor, CodeDistro, enabler, marketingRequired

#1971 Update Derby reserved words
  liquibase-core/src/main/java/liquibase/database/core/DerbyDatabase.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addLookupTable/derby.sql
Labels: TypeEnhancement, RiskMedium, Severity4, ImpactLow, DBApacheDerby, IntegrationSpringboot, SafeToBuild, autocandidate, sprint2022-29, sprint2022-30

#3045 Output "may loose settings" warning on mysql/mariadb for more impacted change types
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-core/src/main/java/liquibase/exception/Warnings.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/ModifyDataTypeGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java
Labels: TypeEnhancement, DBMariaDB

#3063 Improved "include" fix performance: optimized normalizePath method
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: SafeToBuild, autocandidate

#2239 Removed DatabaseInfoAttributes in XSD
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: TypeEnhancement, IntegrationMaven, SafeToBuild, XSD, ignore-release-notes, autocandidate

#1589 Do not split SQL on delimiters within BEGIN/END blocks
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
Labels: TypeEnhancement, RiskMedium, Severity3, ImpactMedium, DBAll, IntegrationAny, autocandidate, field

#2892 Set max fractional timestamp digits to 12 for all DB2 editions (fix #2880)
  liquibase-core/src/main/java/liquibase/database/core/AbstractDb2Database.java
  liquibase-core/src/main/java/liquibase/database/core/Db2zDatabase.java
  liquibase-core/src/test/java/liquibase/database/core/DB2DatabaseTest.java
  liquibase-core/src/test/java/liquibase/database/core/DB2zDatabaseTest.java
Labels: TypeBug, DBDB2LUW, DBDB2Z, DBDB2i, daily_review, SafeToBuild, autocandidate, ver4.11.0, sprint2022-30

#2712 Fix query for snapshotting views on DB2/Z
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorDB2.java
Labels: IntegrationCLI, DBDB2Z, OSWindows, SafeToBuild, featureDiff, ver4.8.0, autocandidate

#2765 Fix for bug 2711: Error when calling a procedure with parameters on DB2Z
  liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/statement/core/RawCompoundStatement.java
Labels: IntegrationCLI, DBDB2Z, OSWindows, SafeToBuild, ver4.8.0, autocandidate

#3078 Improve CLI error messages
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeEnhancement, IntegrationCLI, daily_review, errorReporting
