Repository liquibase/liquibase, pull requests merged in 2022-11, with the labels that each got.

#3396 Resets changelog cache upon acquiring lock
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: DBPostgres

#3324 Defines "-- rollback empty" as the way to specify "no rollback needed".
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/rollbackable.changelog.sql
Labels: DocRequired, autocandidate, sprint2022-34

#3366 Fix create index on Postgresql and MSSQL using wrong column names when generating a changelog
  liquibase-core/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
Labels: TypeBug, DBPostgres, DBMSSQLServer, featureGenerateChangelog

#3309 Fixed input string handling in CompareControl constructor
  liquibase-core/src/main/java/liquibase/diff/compare/CompareControl.java
  liquibase-core/src/test/groovy/liquibase/diff/compare/CompareControlTest.groovy
Labels: autocandidate, sprint2022-35

#3301 Add 'ifExists' parameter to the dropView statement
  liquibase-core/src/main/java/liquibase/change/core/DropViewChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropViewGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/DropViewStatement.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Labels: DocRequired, ReleaseMajor, SafeToBuild, autocandidate, KReview

#3347 Fix getResourceAccessor logic to avoid setting changeLogDirectory when searchPath has already set
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojoTest.java
Labels: autocandidate

#3381 Ensures that Postgresql works with blob types bytea and oid (large objects)
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/testBlob.changelog.xml
Labels: autocandidate

#3274 Improve int/tinyint/smallint/bigint handling in H2
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/BigIntTypeTest.groovy
  liquibase-core/src/test/groovy/liquibase/datatype/core/IntTypeTest.groovy
  liquibase-core/src/test/groovy/liquibase/datatype/core/SmallIntTypeTest.groovy
  liquibase-core/src/test/groovy/liquibase/datatype/core/TinyIntTypeTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
Labels: TypeBug, DBH2, autocandidate

#665 Improved Sybase ASE Support
  liquibase-core/src/main/java/liquibase/database/core/SybaseDatabase.java
  liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/main/java/liquibase/datatype/core/TinyIntType.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
  liquibase-core/src/main/java/liquibase/util/SqlUtil.java
  liquibase-core/src/test/groovy/liquibase/database/core/SybaseDatabaseTest.groovy
  liquibase-core/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Labels: DBSybase, SafeToBuild, autocandidate

#3398 Do not write output files for computed columns when executing dbDoc. Fixes #1088
  liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java
  liquibase-core/src/test/java/liquibase/changelog/visitor/DBDocVisitorTest.java
Labels: sprint2022-37, sprint2022-38

#3335 Sequence owned by a table field must be included in database snapshot
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
Labels: DBPostgres, featureSnapshot, autocandidate

#3329 Fixes snapshot of case-sensitive views
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
Labels: DBAll, autocandidate, sprint2022-34

#3355 Fix include/includeAll to correct track relativeToChangelog=true paths using ./ or ../
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeBug, autocandidate, sprint2022-37, sprint2022-38

#3479 Fix int test diff changelog test
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogTest.groovy
Labels: sprint2022-38

#3316 Improved readability in the createCDILiquibaseConfig method.
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesCDIConfigBuilder.java
Labels: SafeToBuild, autocandidate

#3361 Fix Postgresql autoIncrement Information in snapshot
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnAutoIncrementService.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: DBPostgres, sprint2022-37, sprint2022-38

#3426 Treat "," as "or" when parsing context expressions. Fixes #1103
  liquibase-core/src/main/java/liquibase/util/ExpressionMatcher.java
  liquibase-core/src/test/groovy/liquibase/util/ExpressionMatcherTest.groovy
Labels: TypeBug, SafeToBuild, sprint2022-38

#898 CORE-1127: Filter by context when doing a rollback.
  liquibase-core/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/h2/H2IntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/rollback.different.contexts.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/rollback.sql.changelog.xml
Labels: TypeEnhancement, RiskHigh, ImpactHigh, DBAll, ThemeChangeTypes, IntegrationMaven, SafeToBuild, featureRollback, featureContext

#3385 Implement tagExists Maven command (Fix issue 1063)
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseTagExistsMojo.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/LiquibaseTagExistsMojoTest.java
Labels: TypeEnhancement, IntegrationMaven, SafeToBuild, autocandidate, sprint2022-38

#3342 Fixes transaction handling within changesets on DB2 on z/OS
  liquibase-core/src/main/java/liquibase/database/core/Db2zDatabase.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: SafeToBuild, autocandidate

#2155 Improve dropAllForeignKeyConstraints performance
  liquibase-core/src/main/java/liquibase/change/core/DropAllForeignKeyConstraintsChange.java
Labels: TypeEnhancement, RiskMedium, Severity4, ImpactLow, DBPostgres, DBAll, IntegrationAny, SafeToBuild, featureSnapshot, autocandidate, performance, complexityLocal, criticalityBuilder

#3506 Fixes behaviour of includeAll by keeping the trailing slash on the path
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeBug, autocandidate, sprint2022-38

#3499 Restore FileSystemResourceAccessor and add tests.
  liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/resource/FileSystemResourceAccessorTest.groovy
Labels: sprint2022-38

#3480 Fix incorrect error message when rollback is not supported for for json,yml and ,xml changelogs
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
Labels: sprint2022-38

#3375 Simplify if statements to a single assignment. Avoid extra works.
  liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-core/src/main/java/liquibase/change/core/DropPrimaryKeyChange.java
  liquibase-core/src/main/java/liquibase/change/core/MergeColumnChange.java
  liquibase-core/src/main/java/liquibase/configuration/AbstractMapConfigurationValueProvider.java
  liquibase-core/src/main/java/liquibase/configuration/core/DefaultsFileValueProvider.java
  liquibase-core/src/main/java/liquibase/database/DatabaseList.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/ColumnComparator.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/TableComparator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedColumnChangeGenerator.java
  liquibase-core/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-core/src/main/java/liquibase/snapshot/CachedRow.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/PrimaryKeySnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateIndexGeneratorFirebird.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
  liquibase-core/src/main/java/liquibase/structure/core/Schema.java
  liquibase-core/src/main/java/liquibase/structure/core/StoredDatabaseLogic.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/TestFilter.java
Labels: SafeToBuild, autocandidate, sprint2022-38, TypeRefactor

#3452 Release liquibase-nochangeloglock extension with the others
  .github/workflows/release-extensions.yml
Labels: TypeEnhancement, ignore-release-notes, autocandidate, sprint2022-38
