Repository liquibase/liquibase, pull requests merged in 2022-09, with the labels that each got.

#1386 Add rollback changeset reference for SQL changelogs
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeEnhancement, ImpactLow, DBAll, IntegrationAny, SafeToBuild, formattedSQL, featureRollback, featureTags

#3210 Add schemas and includeSchema parameters to maven generateChangeLog
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseGenerateChangeLogMojo.java
Labels: IntegrationMaven

#3263 Upgrade snakeyaml from 1.27 to 1.31 fixing CVE-2022-25857
  liquibase-dist/src/main/maven/release.pom.xml
Labels: dependencies, daily_review, SafeToBuild, CVE, autocandidate

#1044 AlterSequence: include NOORDER clause ordered="false" is specified
  liquibase-core/src/main/java/liquibase/change/core/AlterSequenceChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java
Labels: TypeEnhancement, RiskLow, ThemeDBObjects, DBAll, IntegrationAny, SafeToBuild

#3279 DAT-11591: use complete path of resource when generating load data statements
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
Labels: path, ResourceAccessor

#3102 Upper case result columns only for case-insensitive databases
  liquibase-core/src/main/java/liquibase/executor/jvm/ColumnMapRowMapper.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
Labels: DocRequired, Extensions, SafeToBuild, autocandidate, breaking-change-dev

#3227 Add year and copyright owner to license
  LICENSE.txt
Labels: autocandidate

#3233 Postgresql: Fix for case when current search_path is an empty string
  liquibase-core/src/main/java/liquibase/database/core/DatabaseUtils.java
Labels: DBPostgres, SafeToBuild, autocandidate

#921 Fix missing catalog on add column rollback
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/test/java/liquibase/change/AddColumnChangeTest.java
Labels: TypeBug, RiskLow, Severity3, ImpactLow, DBAll, ThemeChangeTypes, IntegrationAny, SafeToBuild, autocandidate, featureRollback

#3135 Fix an error which can occur if getAutoCommit is called on a closed connection
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
Labels: TypeBug, Severity3, SafeToBuild, autocandidate, IntegrationTomcat, complexityLocal, criticalityBlocker

#2136 Adjust assembly plugin configuration to allow MacOS builds (fix #2065)
  liquibase-dist/pom.xml
Labels: TypeBug, Severity3, ImpactLow, DBAll, IntegrationMaven, IntegrationAny, SafeToBuild, autocandidate, complexityLocal, criticalityBuilder, criticalityBlocker

#3220 apply sqlVisitors to CompoundStatements on DB2z
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: TypeBug, Severity2, DBDB2Z, SafeToBuild, autocandidate, DBVUnverified

#2238 Improved message when precondition onFail : MARK_RAN is set
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
Labels: TypeBug, Severity3, IntegrationMaven, Logging, OSWindows, SafeToBuild, autocandidate, complexityLocal, criticalityBuilder

#3152 Add default catalog condition to SequenceSnapshotGenerator for Oracle
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-core/src/test/groovy/liquibase/snapshot/jvm/SequenceSnapshotGeneratorTest.groovy
Labels: Severity3, DBOracle, SafeToBuild, featureSnapshot, autocandidate, complexityLocal, criticalityBlocker

#1831 Fixed issue with h2 loadUpdateData not correctly handling values with the string " values " in the inserted data
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorH2.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorH2Test.java
Labels: TypeBug, RiskMedium, Severity3, ImpactLow, DBH2, IntegrationAny, SafeToBuild, autocandidate, complexityLocal, criticalityBuilder

#2997 chore: Set permissions for GitHub actions
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/snyk.yml
Labels: TypeEnhancement, Severity3, SafeToBuild, autocandidate, complexityLocal, criticalityBuilder

#3130 Create liquibase_autocomplete.zsh
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete.zsh
Labels: TypeEnhancement, SafeToBuild, autocandidate

#3234 Fix the smallserial issue not being parsed as a SmallInt type for Postgres
  liquibase-core/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-core/src/test/groovy/liquibase/change/core/CreateTableChangeTest.groovy
Labels: DBPostgres, autocandidate

#3266 Upgraded installer to use JDK 17.0.4.1
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: autocandidate

#3273 Fix double with precision type error for H2
  liquibase-core/src/main/java/liquibase/datatype/core/DoubleType.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/DoubleTypeTest.groovy
Labels: TypeBug, DBH2, autocandidate

#1500 Firebird: fix createIndex missing space around "computed"
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateIndexGeneratorFirebird.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateIndexGeneratorFirebirdTest.java
Labels: TypeBug, Severity3, DBFirebird, IntegrationAny, SafeToBuild, autocandidate, complexityLocal, criticalityBlocker

#2327 Test Race Condititons During Liquibase Locking
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java
  liquibase-core/src/main/java/liquibase/hub/HubUpdater.java
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
Labels: TypeBug, Severity3, DATABASECHANGELOGLOCK, SafeToBuild, autocandidate, complexityLocal, criticalityBuilder

#3124 Use configuration to get 'altTablespace', 'altSchema' and 'altCatalog…
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
Labels: TypeBug, Severity3, SafeToBuild, autocandidate, complexityLocal, criticalityBlocker

#3225 Add missing generator for parameterized SQL statements
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/RawParameterizedSqlGenerator.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Labels: Severity4, Extensions, DBNeo4j, autocandidate, enabler, criticalityBuilder

#3305 Fixed createView handling of replaceIfExists=true when the string "replace" exists in the view definition
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
  liquibase-core/src/test/groovy/liquibase/sqlgenerator/core/CreateViewGeneratorTest.groovy
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateViewGeneratorTest.java
Labels: autocandidate

#3246 Fix generateChangeLog and diffChangeLog logic to avoid including default schema name when it should not
  liquibase-core/src/main/java/liquibase/command/core/InternalDiffChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalGenerateChangelogCommandStep.java
Labels: TypeBug, DBPostgres, autocandidate, includeSchema
