Repository liquibase/liquibase, pull requests merged in 2022-01, with the labels that each got.

#2313 validate token with hub (DAT-8770)
  liquibase-core/src/main/java/liquibase/hub/HubService.java
  liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
  liquibase-core/src/main/java/liquibase/hub/model/ApiKey.java
  liquibase-core/src/main/java/liquibase/hub/model/CoreInitOnboardingResponse.java
Labels: SquadPro

#2263 DAT-8601: Init Project command
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-core/src/main/java/liquibase/configuration/ConfiguredValue.java
  liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
  liquibase-core/src/main/java/liquibase/util/FileUtil.java
  liquibase-core/src/main/resources/liquibase/examples/json/blank-changelog.json
  liquibase-core/src/main/resources/liquibase/examples/json/example-changelog.json
  liquibase-core/src/main/resources/liquibase/examples/json/example-changeset-json.txt
  liquibase-core/src/main/resources/liquibase/examples/json/liquibase.properties
  liquibase-core/src/main/resources/liquibase/examples/sql/blank-changelog.sql
  liquibase-core/src/main/resources/liquibase/examples/sql/example-changelog.sql
  liquibase-core/src/main/resources/liquibase/examples/sql/example-changeset-sql.txt
  liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.properties
  liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlplus.conf
  liquibase-core/src/main/resources/liquibase/examples/start-h2
  liquibase-core/src/main/resources/liquibase/examples/start-h2.bat
  liquibase-core/src/main/resources/liquibase/examples/xml/blank-changelog.xml
  liquibase-core/src/main/resources/liquibase/examples/xml/example-changelog.xml
  liquibase-core/src/main/resources/liquibase/examples/xml/example-changeset-xml.txt
  liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.properties
  liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlplus.conf
  liquibase-core/src/main/resources/liquibase/examples/yaml/blank-changelog.yaml
  liquibase-core/src/main/resources/liquibase/examples/yaml/example-changelog.yaml
  liquibase-core/src/main/resources/liquibase/examples/yaml/example-changeset-yaml.txt
  liquibase-core/src/main/resources/liquibase/examples/yaml/liquibase.properties
  liquibase-core/src/test/groovy/liquibase/ui/ConsoleUIServiceTest.groovy
  liquibase-dist/src/main/assembly/assembly-bin.xml
  liquibase-dist/src/main/install4j/liquibase.install4j
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCleanResources.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCreateDirectoryResources.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCreateTempResources.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/registerChangelog.test.groovy
Labels: SquadPro

#2311 DAT-8945: print a pretty error if the H2 jar cannot be found
  liquibase-core/src/main/java/liquibase/example/StartH2Main.java
Labels: SquadPro

#2332 modify mock hub service to support init hub tests (DAT-8973)
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
Labels: SquadPro

#2261 Mark liquibase-maven-plugin logging configuration as deprecated
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: StatusActive, SyncTicket

#2270 Correctly handle cacheSize in mariadb
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
Labels: StatusActive, DBMariaDB, SyncTicket

#2269 Correctly handle old "liquibase tagExists myTag" style CLI structure
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Labels: StatusActive, SyncTicket

#2293 Mysql: Support additional information "double" datatypes
  liquibase-core/src/main/java/liquibase/datatype/core/DoubleType.java
Labels: StatusActive, SyncTicket

#2188 Include columnDataType in generated setColumnRemarks changesets
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedColumnChangeGenerator.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, DBMySQL, IntegrationAny, BKeyPlatform, SyncTicket

#932 Support MaxDB for sequences
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: TypeBug, StatusActive, RiskLow, ImpactLow, ThemeDBObjects, DBMaxDB, IntegrationAny, SyncTicket

#2300 Rework CommandTests to have cleanup before and after tests DAT-8752
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCleanResources.groovy
Labels: SquadPro

#2333 Enable property parsing in FormattedSqlChangeParser DAT-4793
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: SquadPro

#1932 Output changeset execution to UI like rollback does
  liquibase-core/src/main/java/liquibase/changelog/visitor/RollbackVisitor.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Labels: TypeEnhancement, Severity4, ImpactMedium, DBAll, IntegrationAny, BBroad, SyncTicket

#2356 point users to init project command if they forget a supported argument in any command (DAT-8641)
  liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java
  liquibase-core/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-core/src/main/java/liquibase/command/CommandBuilder.java
  liquibase-core/src/main/java/liquibase/command/CommonArgumentNames.java
  liquibase-core/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncToTagCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncToTagSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ClearChecksumsCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DbDocCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DeactivateChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DropAllCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/FutureRollbackCountSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/FutureRollbackFromTagSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/FutureRollbackSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/HistoryCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalDiffChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalSyncHubCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ListLocksCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/MarkNextChangesetRanCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/MarkNextChangesetRanSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ReleaseLocksCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCountCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCountSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackToDateSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/StatusCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/SyncHubCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/TagCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/TagExistsCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UnexpectedChangesetsCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCountCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCountSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateToTagSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ValidateCommandStep.java
  liquibase-core/src/main/java/liquibase/exception/CommandValidationException.java
  liquibase-core/src/main/java/liquibase/exception/MissingRequiredArgumentException.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy
Labels: SquadPro

#2359 [DAT-8906] Added validation errors for SQLite and DB2z databases
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddAutoIncrementGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropProcedureGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/ModifyDataTypeGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameSequenceGenerator.java
Labels: SquadPro

#2282 [DAT-8744] Drop column sql generator fix for db2z
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropColumnGenerator.java
Labels: Test Harness

#2364 Make EnterpriseDBDatabase detection less broad
  liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java
Labels: StatusActive, SyncTicket

#2335 Remove duplicate databasechangeloglock SQL when running update-sql against a new database
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-core/src/main/java/liquibase/ui/ConsoleUIService.java
Labels: StatusActive, SyncTicket

#2139 UniqueConstraintSnapshotGenerator - Add table name to OracleDB query
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: TypeBug, StatusActive, RiskMedium, Severity3, ImpactLow, DBOracle, IntegrationAny, BKeyPlatform, SyncTicket

#1320 CORE-3326 Numero sign is a symbol in Russian
  liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
Labels: TypeBug, StatusActive, RiskLow, Severity3, ImpactMedium, DBAll, IntegrationCLI, IntegrationAny, SyncTicket

#2374 Allow a custom executor to be specified through a property on existing Executor implementations DAT-7531
  liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlcmd.conf
  liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlplus.conf
  liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlcmd.conf
  liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlplus.conf
  liquibase-extension-examples/src/main/resources/META-INF/services/liquibase.executor.Executor
Labels: SquadPro

#2308 Make ClassLoaderResourceAccessor implement Closable
  liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/resource/ClassLoaderResourceAccessorTest.groovy
Labels: TypeEnhancement, StatusActive, RiskLow, ImpactLow, IntegrationAny, SyncTicket

#2394 improve console output of failing CommandTests (DAT-9038)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: SquadPro
