Repository liquibase/liquibase, pull requests merged in 2022-02, with the labels that each got.

#2436 support registering value provider in command tests (DAT-9153)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupConfigurationValueProvider.java
Labels: SquadPro

#2404 add cause to exception thrown during register changelog command (DAT-9136)
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/exception/ChangeLogAlreadyRegisteredException.java
Labels: SquadPro

#2366 use lowercase sp_rename function in MSSQL (LB-1763)
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameSequenceGenerator.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameSequence/mssql.sql
Labels: SquadPro

#2453 DAT-8992: add start-H2 message to error message in JDBC connection creation
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
Labels: SquadPro

#2367 Added example rollback scripts
  liquibase-core/src/main/resources/liquibase/examples/sql/example-changelog.sql
Labels: TypeEnhancement, DBH2, SyncTicket

#2476 expose more hub properties for use in testing, allow generic expectations in command tests (DAT-9241)
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: SquadPro

#2273 Added new Quality Checks command and subcommands (Mac specifict)
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete_mac.bash
Labels: TypeEnhancement, IntegrationAny

#2429 Don't repackage all org.apache.* classes.
  liquibase-core/pom.xml
Labels: StatusConditioning, SyncTicket

#2397 Log exceptions in CDILiquibase before rethrowing them
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/CDILiquibaseTest.java
Labels: SyncTicket

#2384 Enable FEATURE_SECURE_PROCESSING XML setting by default
  liquibase-core/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
  liquibase-core/src/test/java/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.java
Labels: RiskHigh, SyncTicket, DocRequired

#2516 Fix XML parsing test on Windows
  liquibase-core/src/main/java/liquibase/parser/ChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
Labels: SquadPro

#2512 add run before test to CommandTests and expose more MockHubService properties (DAT-9165)
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: SquadPro

#2122 Use path instead of absolutePath for resources
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeBug, RiskHigh, StatusConditioning, Severity3, ImpactLow, DBAll, IntegrationAny, SyncTicket

#2329 Added additional unicode letter points
  liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
  liquibase-core/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy
Labels: StatusConditioning, SyncTicket

#2222 Add offline mode support for rollbackSQL <tag>
  liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
Labels: TypeBug, StatusActive, Severity3, ImpactLow, DBMSSQLServer, DBAll, IntegrationCLI, BBroad, SyncTicket

#1648 Avoid NullPointerException when customChange has no "class" attribute
  liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-core/src/test/groovy/liquibase/change/custom/CustomChangeWrapperTest.groovy
Labels: TypeEnhancement, StatusConditioning, Severity3, ImpactLow, DBAll, IntegrationAny, SyncTicket, SafeToBuild

#2340 Support adding computed=true columns with no type set
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/AddColumnStatement.java
  liquibase-core/src/main/java/liquibase/statement/core/CreateTableStatement.java
  liquibase-core/src/test/groovy/liquibase/change/core/AddColumnChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/CreateTableChangeTest.groovy
Labels: StatusConditioning, SyncTicket

#2480 DAT-9218 Added limited permission user for SQLPLUS integration tests
  .github/util/ManifestReversion.java
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/release-published.yml
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/CDILiquibaseTest.java
  liquibase-core/pom.xml
  liquibase-core/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/RenameSequenceGenerator.java
  liquibase-core/src/main/resources/liquibase/examples/sql/example-changelog.sql
  liquibase-core/src/main/resources/liquibase/examples/start-h2
  liquibase-core/src/main/resources/liquibase/examples/start-h2.bat
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
  liquibase-core/src/test/java/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameSequence/mssql.sql
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/examples/start-h2
  liquibase-dist/src/main/archive/examples/start-h2.bat
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete_mac.bash
  liquibase-extension-examples/pom.xml
  liquibase-extension-testing/pom.xml
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/MSSQLTestSystem.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/OracleTestSystem.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AbstractExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddColumnExecutorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/RenameColumnExecuteTest.java
  liquibase-maven-plugin/pom.xml
  pom.xml
Labels: SquadPro

#2371 Reworked license not found message
  liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-core/src/main/java/liquibase/parser/core/ParsedNode.java
  liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlcmd.conf
  liquibase-core/src/main/resources/liquibase/examples/sql/liquibase.sqlplus.conf
  liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlcmd.conf
  liquibase-core/src/main/resources/liquibase/examples/xml/liquibase.sqlplus.conf
  liquibase-core/src/main/resources/liquibase/i18n/liquibase-core.properties
  liquibase-core/src/test/java/liquibase/changelog/ChangeLogIteratorTest.java
  liquibase-extension-examples/src/main/resources/META-INF/services/liquibase.executor.Executor
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/OracleTestSystem.java
Labels: SquadPro

#2522 DAT-9033: liquibase checks run maven goal
  liquibase-core/src/main/java/liquibase/checks/config/ChecksFileAccessor.java
  liquibase-core/src/main/java/liquibase/checks/config/FileAccessor.java
  liquibase-core/src/main/java/liquibase/checks/config/FileAccessorDTO.java
  liquibase-core/src/main/java/liquibase/checks/config/FileEncoder.java
  liquibase-core/src/main/java/liquibase/checks/config/InMemoryChecksFileAccessor.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
Labels: SquadPro

#2351 Fix for Github issue dealing with duplicate property keys
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-core/src/test/java/liquibase/changelog/ChangeLogParametersTest.java
Labels: StatusConditioning, SyncTicket

#2372 Use "GENERATED BY DEFAULT AS IDENTITY" for h2 2.0+
  liquibase-core/src/main/java/liquibase/database/core/H2Database.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
  liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addAutoIncrement/h2.sql
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java
Labels: StatusConditioning, SyncTicket

#2326 DAT-8615: init hub command
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-core/src/main/java/liquibase/exception/ChangeLogAlreadyRegisteredException.java
  liquibase-core/src/main/java/liquibase/hub/HubService.java
  liquibase-core/src/main/java/liquibase/hub/HubServiceFactory.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
  liquibase-core/src/main/java/liquibase/hub/model/ApiKey.java
  liquibase-core/src/main/java/liquibase/hub/model/CoreInitOnboardingResponse.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupConfigurationValueProvider.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
Labels: SquadPro

#2272 Added Quality Checks commands and subcommands
  liquibase-dist/src/main/archive/lib/liquibase_autocomplete.sh
Labels: TypeEnhancement, IntegrationAny, SyncTicket, quality_checks

#2434 Add validate goal to maven-liquibase-plugin
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseValidate.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/LiquibaseValidateMojoTest.java
  liquibase-maven-plugin/src/test/resources/validate/plugin_config.xml
Labels: TypeEnhancement, IntegrationMaven, SafeToBuild

#2330 Correctly catch potentially null value
  liquibase-core/src/main/java/liquibase/diff/DiffGeneratorFactory.java
Labels: TypeBug, Severity5, IntegrationAny

#1894 [LB-1373] fixed precision for time type for PostgreSQL
  liquibase-core/src/main/java/liquibase/datatype/core/TimeType.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/TimeTypeTest.groovy
Labels: TypeBug, StatusActive, Severity3, ImpactMedium, DBPostgres, IntegrationAny, BKeyPlatform, SyncTicket

#2521 DAT-9325: add label, context, and comment to example-changelog.sql
  liquibase-core/src/main/resources/liquibase/examples/json/example-changelog.json
  liquibase-core/src/main/resources/liquibase/examples/sql/example-changelog.sql
  liquibase-core/src/main/resources/liquibase/examples/xml/example-changelog.xml
  liquibase-core/src/main/resources/liquibase/examples/yaml/example-changelog.yaml
Labels: SquadPro

#2545 Added new command tests method to compare two files DAT-9094
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcSnapshotSerializerTest.groovy
Labels: SquadPro

#2556 CockroachDatabase: Limit calls to version()
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
Labels: SafeToBuild
