Repository liquibase/liquibase, pull requests merged in 2022-08, with the labels that each got.

#3118 Improved handling of endDelimiter="/"
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
Labels: TypeBug, autocandidate, field

#3104 Upgrade installer to ship with jdk 17.0.4+8
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: java, sprint2022-30

#3093 Improve failure message of RowCountPrecondition to preserve expected row count
  liquibase-core/src/main/java/liquibase/precondition/core/RowCountPrecondition.java
  liquibase-core/src/main/java/liquibase/precondition/core/TableIsEmptyPrecondition.java
Labels: SafeToBuild, errorReporting

#3119 Added duplicateFileMode setting for maven plugin
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
Labels: TypeEnhancement, IntegrationMaven, DocRequired, sprint2022-30

#3070 Fix addColumn on mysql when including a "value" attribute
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
Labels: TypeBug, DBMySQL, TypeIncorrectSQL, sprint2022-31

#3047 Add support for `AS <dataType>` clause for H2 since version 2.0
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
Labels: TypeEnhancement, DBH2, SafeToBuild, autocandidate

#3098 [CORE-3202] Fix NUMBER not compatible with H2
  liquibase-core/src/main/java/liquibase/datatype/core/NumberType.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/NumberTypeTest.groovy
Labels: TypeBug, DBH2, BKeyPlatform, SafeToBuild, autocandidate

#3095 SpringResourceAccessor: fix issue with incorrect match pattern for files from classPath root
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-core/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
Labels: TypeBug, Severity2, IntegrationSpringboot, daily_review, SafeToBuild, autocandidate, path, ResourceAccessor, complexityLocal, criticalityBlocker

#2087 Make liquibase.snapshot.ResultSetCache an extensible class.
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
Labels: TypeBug, RiskMedium, Severity3, Severity4, ImpactLow, IntegrationCLI, Extensions, DBHana, SafeToBuild, ver4.5.0, autocandidate, enabler, complexityLocal, criticalityBlocker

#1324 Add support for \u2116 symbol win1251 cyrillic symbol of number
  liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
Labels: TypeBug, RiskMedium, Severity3, DBOracle, IntegrationMaven, SafeToBuild, autocandidate

#1842 Tidy ExecutorService code, remove superfluous map access (Issue 1841)
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
Labels: TypeEnhancement, RiskMedium, Severity4, ImpactLow, DBAll, IntegrationAny, SafeToBuild, autocandidate

#3150 fix order of enum values on MySQL 8
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, Severity3, DBMySQL, SafeToBuild, autocandidate, complexityLocal, criticalityBlocker

#3189 Removed invalid warning in Maven
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: autocandidate
