Repository liquibase/liquibase, pull requests merged in 2022-06, with the labels that each got.

#2656 Add configuration options for missing property handling
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/changelog/ExpressionExpander.java
  liquibase-core/src/main/java/liquibase/database/core/MockDatabase.java
  liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java
  liquibase-core/src/main/java/liquibase/exception/UnknownChangeLogParameterException.java
  liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeLogParametersTest.groovy
  liquibase-core/src/test/groovy/liquibase/changelog/ExpressionExpanderTest.groovy
  liquibase-core/src/test/java/liquibase/changelog/ChangeLogParametersTest.java
  liquibase-core/src/test/java/liquibase/changelog/ExpressionExpanderTest.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/LiquibaseUpdateMojoExecutionTest.java
Labels: TypeEnhancement, DBOracle, IntegrationCLI, SafeToBuild, ver4.8.0

#2277 Fix for working with Firebird 2 and newer versions. Fixes nullables and boolean type.
  liquibase-core/src/main/java/liquibase/database/core/Firebird3Database.java
  liquibase-core/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.database.Database
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/RenameColumnExecuteTest.java
Labels: TypeBug, Severity4, ImpactMedium, DBFirebird, IntegrationAny, SafeToBuild, autocandidate

#2252 Add ConfiguredValueModifier extension point for plugins
  liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifier.java
  liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java
  liquibase-core/src/main/java/liquibase/configuration/LiquibaseConfiguration.java
  liquibase-core/src/test/groovy/liquibase/configuration/LiquibaseConfigurationTest.groovy
Labels: TypeEnhancement, IntegrationCLI, Extensions, SafeToBuild, autocandidate, enabler

#2771 Updated pull request template
  .github/pull_request_template.md
Labels: ignore-release-notes

#2837 null pointer issue if change changelog object is null
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
Labels: DBOracle, DBPostgres, IntegrationSpringboot, daily_review, SourceForum, OSWindows, SafeToBuild, autocandidate, ver3.7.0

#2886 Introduced "latest" xsd file path
  liquibase-core/src/main/java/liquibase/parser/NamespaceDetails.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/StandardNamespaceDetails.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/main/resources/liquibase/examples/xml/blank-changelog.xml
  liquibase-core/src/main/resources/liquibase/examples/xml/example-changelog.xml
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
Labels: XSD

#2841 [DAT-10294] added Snowflake as standalone module
  liquibase-dist/pom.xml
  liquibase-integration-tests/pom.xml
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddAutoIncrementExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-snowflake/pom.xml
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/TextDataTypeSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/TimestampNTZTypeSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/ResultSetCacheSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SnowflakeResultSetConstraintsExtractor.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/DropProcedureGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/RenameTableGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/RenameViewGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGeneratorSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.database.Database
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.snapshot.SnapshotGenerator
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
  liquibase-snowflake/src/test/java/liquibase/database/core/SnowflakeDatabaseTest.java
  liquibase-snowflake/src/test/java/liquibase/datatype/TimestampNTZTypeTest.java
  pom.xml
Labels: DBSnowflake, daily_review

#605 Use the method setBlob to insert blob data
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
Labels: RiskLow, DBPostgres, SafeToBuild, autocandidate

#2870 Include inherited labels in databasechangelog table
  liquibase-core/src/main/java/liquibase/LabelExpression.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/changelog/filter/LabelChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/MarkChangeSetRanGeneratorTest.java
Labels: ReleaseMajor, DATABASECHANGELOG, featureLabels, field

#2924 Restored OSGi headers
  liquibase-cli/pom.xml
  liquibase-dist/pom.xml
Labels: MANIFEST.MF, OSGi

#2931 Added snowflake driver to CLI
  .github/workflows/release-extensions.yml
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/licenses/oss/README.txt
  liquibase-dist/src/main/assembly/assembly-bin.xml
  pom.xml
Labels: TypeEnhancement, DBSnowflake, IntegrationCLI

#2930 support parsing test definition generated by intellij
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/TestFilter.java
Labels: enabler

#2933 Added showBanner configuration to maven
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: DocRequired, sprint2022-27

#2913 Support prepared statements for query
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/statement/core/RawParameterizedSqlStatement.java
Labels: Extensions, SafeToBuild, autocandidate

#2942 Add additional info in CLI's --version output
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Labels: IntegrationCLI, enabler, sprint2022-27

#2932 Cleanup relative paths preventing sql files being found by the class loader
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
Labels: SafeToBuild, autocandidate, classpath

#2585 Fix missing attributes in serialization
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
  liquibase-core/src/test/java/liquibase/serializer/core/json/JsonChangeLogSerializerTest.java
  liquibase-core/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
  liquibase-core/src/test/java/liquibase/serializer/core/yaml/YamlChangeLogSerializerTest.java
Labels: DBMySQL, DBH2, IntegrationCLI, ver4.7.1, OSWindows, SafeToBuild, autocandidate

#2949 Improved parsing of single-quoted strings
  liquibase-core/pom.xml
  liquibase-core/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
  liquibase-core/src/test/groovy/liquibase/util/SqlParserTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy
  liquibase-extension-examples/pom.xml
Labels: autocandidate, SQparser

#2985 Formatted SQL files with uppercase in the liquibase attributes (DAT-10531)
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: formattedSQL

#2984 Fixed issue with parameter expression parsing
  liquibase-core/src/main/java/liquibase/changelog/ExpressionExpander.java
  liquibase-core/src/test/groovy/liquibase/changelog/ExpressionExpanderTest.groovy
Labels: autocandidate

#2943 Fixed before/after/at column arguments in addColumn
  liquibase-core/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGeneratorDefaultClauseBeforeNotNull.java
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/hsqldb/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/root.changelog.xml
Labels: ReleaseMajor, breaking-change, sprint2022-27

#2895 [DAT-10093] added schema escaping to getColumns call to jdbc metadata classes
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotTest.groovy
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
Labels: TypeBug, DBSnowflake, autocandidate, ver4.11.0

#3006 Added new liquibase.duplicateFileMode setting
  liquibase-core/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/resource/AbstractResourceAccessor.java
  liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java
  liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-core/src/test/groovy/liquibase/resource/FileSystemResourceAccessorTest.groovy
Labels: TypeEnhancement, DocRequired, marketingRequired

#3008 Update README.txt
  liquibase-dist/src/main/archive/licenses/oss/README.txt
Labels: CodeDistro

#3010 Update README.txt
  liquibase-dist/src/main/archive/licenses/commercial/README.txt
Labels: enabler
