Repository liquibase/liquibase, pull requests merged in 2023-04, with the labels that each got.

#3911 Fix DB-Doc generation of Unique Constraints for Sybase ASE database.
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: TypeBug, SafeToBuild

#3973 TEST - maven-javadoc-plugin version upgrade to 3.5.0
  pom.xml
Labels: ManualTest, sprint2023-48

#4062 Lowers Snakeyaml log level for warning stack traces
  liquibase-core/src/main/java/liquibase/util/SnakeYamlUtil.java
Labels: sprint2023-48

#3857 * Remove unused parameters and local variables
  liquibase-core/src/main/java/liquibase/datatype/core/BlobType.java
  liquibase-core/src/main/java/liquibase/dbdoc/TableWriter.java
  liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
  liquibase-core/src/main/java/liquibase/integration/servlet/GenericServletListener.java
  liquibase-core/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGeneratorInformix.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
  liquibase-extension-examples/src/main/java/liquibase/executor/jvm/ExampleExecutor.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#4000 Appends the table type to the statement using it.
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
Labels: sprint2023-47

#4001 Release liquibase-cdi-jakarta to maven repositories
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/release-published.yml
Labels: TypeEnhancement, RiskLow, SafeToBuild

#4075 [DAT-6629] Refactoring of rollbackToDate[SQL] command.
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackToDateSqlCommandStep.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDate.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDateSql.test.groovy
Labels: sprint2023-48

#3959 Fixes UnsupportedOperationException thrown in SpringResourceAccessor in Spring Boot 3 Native Image
  liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-core/src/test/java/liquibase/integration/spring/SpringResourceAccessorTest.java
Labels: TypeBug, SafeToBuild, sprint2023-48

#4088 Fix logging.
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
Labels: sprint2023-48

#4044 Implement Strict global configuration support to control whether non-empty author attribute is allowed or not
  liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-core/src/main/java/liquibase/configuration/core/EnvironmentValueProvider.java
  liquibase-core/src/test/groovy/liquibase/changelog/visitor/ValidatingVisitorTest.groovy
  liquibase-core/src/test/java/liquibase/changelog/visitor/ValidatingVisitorTest.java
Labels: sprint2023-47

#4077 [DAT-6626] Refactoring of rollbackCount[SQL] commands
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCountCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCountSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java
  liquibase-core/src/test/resources/liquibase/integration/ant/DatabaseRollbackTaskTest.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackCount.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackCountSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDateSql.test.groovy
Labels: sprint2023-48

#3794 Read Snowflake views definitions with the Snowflake-specific query
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Labels: TypeBug, SafeToBuild, sprint2023-47

#4008 Fixed #3745 error generation intType when using autoIncrement=true with H2 V2
  liquibase-core/src/main/java/liquibase/datatype/core/IntType.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/IntTypeTest.groovy
Labels: TypeBug, SafeToBuild, sprint2023-48

#4126 Add missing parameter changeLogFile to update command when running from Main
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Labels: criticalityBlocker

#4143 Bump Spring version to 5.3.27
  pom.xml
Labels: sprint2023-49

#4113 Bump maven-surefire-plugin from 2.22.2 to 3.0.0
  .github/workflows/build.yml
  pom.xml
Labels: SafeToBuild, sprint2023-48
