Repository liquibase/liquibase, pull requests merged in 2023-11, with the labels that each got.

#5123 override dependency providing command steps, get liquibase table names from factory (DAT-15985)
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/LiquibaseTableNames.java
  liquibase-standard/src/main/java/liquibase/database/LiquibaseTableNamesFactory.java
  liquibase-standard/src/main/java/liquibase/database/StandardLiquibaseTableNames.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeEnhancement

#5143 load services using ServiceLocator if allInstances is empty
  liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
Labels: TypeBug, SafeToBuild

#4584 Allow changing default UI service + change String default UI service allowing log level control
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/ui/UIServiceEnum.java
Labels: TypeEnhancement, DocNeeded

#4893 Quality Checks Packages (DAT-15553)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCreateTempResources.groovy
  liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifier.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.checks-package.yaml
Labels: TypeEnhancement

#5154 add new checks package file to expected-distribution-contents.txt
  liquibase-dist/expected-distribution-contents.txt
Labels: skipReleaseNotes

#5153 removing build-azure jar
  .github/workflows/create-release.yml
Labels: TypeTechDebt, skipReleaseNotes

#5134 Makes sure that precondition onErrorMessage and onFailMessage are logged when an error happens
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/main/java/liquibase/exception/ValidationFailedException.java
Labels: TypeBug

#5141 Fix Liquibase changeset relative path check
  liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java
  liquibase-standard/src/test/java/liquibase/changelog/RanChangeSetTest.java
Labels: TypeBug

#5080 Fix tests DAT-16053
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/structure/core/Column.java
Labels: TypeBug

#5159 Remove slf4j from installer dependencies
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: skipReleaseNotes

#5099 Apply SQL visitors to prepared SQL
  liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-standard/src/test/java/liquibase/statement/InsertExecutablePreparedStatementTest.java
Labels: TypeBug, SafeToBuild

#5148 Implement global end delimiter prioritized flag DAT-16166
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/ModifyChangeSets.java
  liquibase-standard/src/main/java/liquibase/changeset/ChangeSetService.java
  liquibase-standard/src/main/java/liquibase/changeset/ChangeSetServiceFactory.java
  liquibase-standard/src/main/java/liquibase/changeset/StandardChangeSetService.java
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/changelog/StandardChangeSetServiceTest.groovy
Labels: TypeEnhancement

#4577 SQL Anywhere: Recompile all views after last change of update
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java
Labels: TypeEnhancement, SafeToBuild, DBSQLAnywhere, sprint2023-57

#5163 DAT-4562 Yum/RPM-based Linux distribution
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5165 Do not warn when env var matches argument alias (DAT-16117)
  liquibase-standard/src/main/java/liquibase/configuration/core/EnvironmentValueProvider.java
  liquibase-standard/src/test/groovy/liquibase/configuration/core/EnvironmentValueProviderTest.groovy
Labels: TypeBug

#5174 remove azure-uber jar script
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5176 Go back to an installer version that supports windows and mac
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: skipReleaseNotes

#5178 Changelog for Liquibase 4.25.0
  changelog.txt
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.25.xsd
Labels: skipReleaseNotes

#5179 DAT-16230
  .github/util/re-version.sh
  .github/workflows/build.yml
Labels: skipReleaseNotes

#5200 Fix readme txt version
  .github/util/re-version.sh
Labels: skipReleaseNotes

#5146 changes in support of history table logging of rollback command (DAT-15798)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/VersionUtils.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/command/CommandFailedException.java
  liquibase-standard/src/main/java/liquibase/exception/ExitCodeException.java
  liquibase-standard/src/main/java/liquibase/exception/UnexpectedLiquibaseException.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ExceptionUtil.java
  liquibase-standard/src/main/java/liquibase/util/ValueHandlerUtil.java
Labels: skipReleaseNotes

#5206 chore(release-published.yml): update pom.xml versions to match the cu…
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5209 fix sed command for 4.25.0 release
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5203 additions to ChangeLogSyncListener (and others) in support of populating history table (DAT-15973)
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeLogSyncListener.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeLogSyncVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
Labels: skipReleaseNotes

#5213 fix copying issues
  .github/util/re-version.sh
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5214 Fix sed command double quotes
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5215 Update create-release.yml
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5191 Update sync-release-master-branch.yml
  .github/workflows/sync-release-master-branch.yml
Labels: skipReleaseNotes

#5218 Merge release to master
  .github/util/re-version.sh
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5196 DAT-16175
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/create-release.yml
Labels: TypeEnhancement

#5222 fix indentation create-release.yml
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5183 add preRun method to AbstractUpdateCommandStep (DAT-15639)
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: skipReleaseNotes

#5150 Fixes problematic V8 checksums for pro CreateFunctionChange
  liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
Labels: TypeBug, PRAssociated

#5157 DAT-13450
  liquibase-extension-examples/pom.xml
  liquibase-extension-examples/src/main/java/liquibase/executor/jvm/ExampleExecutor.java
  liquibase-extension-examples/src/main/resources/META-INF/services/liquibase.executor.Executor
  pom.xml
Labels: TypeEnhancement, TypeTechDebt, skipReleaseNotes

#5167 Added tag attribute to update report parameters DAT-15640
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
Labels: TypeEnhancement

#5245 DAT-16300 WPEngine :: Update index.html with the released version of OSS xsd
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5248 call prerun method earlier (DAT-16308)
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: skipReleaseNotes

#5253 Update commercial licenses
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/src/main/archive/licenses/commercial/README.txt
  liquibase-dist/src/main/archive/licenses/commercial/bsd-3-clause.txt
  liquibase-dist/src/main/archive/licenses/commercial/mit.txt
Labels: skipReleaseNotes

#5232 Show a better message if a boolean configuration argument has bad input DAT-16276
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfigurationDefinition.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfigurationValueUtils.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValue.java
  liquibase-standard/src/main/java/liquibase/util/ValueHandlerUtil.java
Labels: TypeEnhancement

#5235 Fix calculateCheckSum issue when using Liquibase API method
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/command/CalculateChecksumCommandStepTest.groovy
Labels: TypeBug

#5249 Fixed query for actual data type for column
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug

#5166 Exclude QUEUE tables from snapshoting
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug, TypeEnhancement

#5073 Run tests using Java 21
  .github/workflows/build.yml
  pom.xml
Labels: skipReleaseNotes

#5265 fix exception misspelling
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
Labels: skipReleaseNotes

#5156 Decode encoded URLs from Spring resources
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-standard/src/test/groovy/liquibase/integration/spring/SpringResourceAccessorTest.groovy
  liquibase-standard/src/test/resources/liquibase/database/test-changelog with-space-in-filename.yml
Labels: TypeBug, SafeToBuild

#5131 Allows to set older checksum versions for testing purposes
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/ChecksumVersion.java
  liquibase-standard/src/main/java/liquibase/Scope.java
Labels: TypeEnhancement

#5224 changes in support of recording dropAll in history table (DAT-16148)
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/LiquibaseTableNamesFactory.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
Labels: skipReleaseNotes

#5108 Improve SQL parsing of character literals (quoted strings)
  liquibase-standard/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
  liquibase-standard/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy
Labels: TypeBug, SafeToBuild
