Repository liquibase/liquibase, pull requests merged in 2023-07, with the labels that each got.

#4407 improve error message when no sql generators can be found (DAT-14688)
  liquibase-standard/src/main/java/liquibase/sqlgenerator/SqlGeneratorFactory.java
Labels: TypeEnhancement

#4425 timestamp_column_precision9 should test with 9 and not 6
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Labels: skipReleaseNotes, sprint2023-54

#4307 Fixes #3661
  liquibase-standard/src/main/java/liquibase/datatype/core/BigIntType.java
  liquibase-standard/src/test/java/liquibase/datatype/BigIntTypeTest.java
Labels: TypeBug, SafeToBuild, sprint2023-53

#4162 Allow whitespace within a foreign key statement
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
Labels: TypeEnhancement, RiskLow, SafeToBuild

#4444 Improvements after 4230
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/plugin/Plugin.java
Labels: TypeBug, RiskLow

#4422 Fixed #3971: "SAP SQL Anywhere 17.0.11: Liquibase incorrectly reports that TIMESTAMP requested precision is longer than TIMESTAMP supported precision"
  liquibase-integration-tests/src/test/resources/changelogs/asany/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java
  liquibase-standard/src/main/java/liquibase/datatype/core/TimestampType.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, SafeToBuild, sprint2023-54

#4375 switch contexts argument to contextFilter (DAT-13423)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSync.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncToTag.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncToTagSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dbDoc.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/futureRollbackCountSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/futureRollbackFromTagSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/futureRollbackSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/markNextChangesetRan.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/markNextChangesetRanSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollback.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackCount.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackCountSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDate.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackToDateSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/status.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/unexpectedChangesets.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCountSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTagSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/validate.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCountCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCountSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeEnhancement

#4471 fix version package-version-ids
  .github/workflows/cleanup-branch-builds.yml
Labels: skipReleaseNotes

#4317 Reworked rollback to tag logic to look for use first occurrence of tag DAT-13057
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/RollbackIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/rollback/rollback-to-tag-changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollback.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackSql.test.groovy
  liquibase-standard/src/main/java/liquibase/TagVersionEnum.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/AfterTagChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/RollbackSqlCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/change/ChangeDefinitionTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/filter/AfterTagChangeSetFilterTest.java
Labels: TypeEnhancement

#4328 Fix postgres tests (DAT-14694)
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/DbDocPostgresIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: TypeBug, skipReleaseNotes

#4452 Fix checksum upgrade changes preventing useless updates and using AbstractChangeLogHistoryService for extensions compatibility
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Labels: TypeBug, ImpactHigh, performance, APIBreakingChanges

#4478 Revert "Fix checksum upgrade changes preventing useless updates and using AbstractChangeLogHistoryService for extensions compatibility"
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Labels: skipReleaseNotes

#4321 DAT-6585 Apt-based Linux package
  .github/workflows/create-release.yml
  .github/workflows/installer-build-check.yml
  .github/workflows/release-published.yml
  liquibase-dist/pom.xml
  liquibase-dist/src/deb/control/postinst
  liquibase-dist/src/main/archive/liquibase-env.sh
Labels: TypeEnhancement, enhancement

#4472 Update cleanup-branch-builds.yml
  .github/workflows/cleanup-branch-builds.yml
Labels: skipReleaseNotes

#4516 DAT-15470
  .github/workflows/build.yml
  pom.xml
Labels: TypeBug

#4517 resolve comment in build.yml file
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4524 DAT-15470
  .github/workflows/build.yml
  pom.xml
Labels: skipReleaseNotes

#4504 [DAT-15369] Rollback snowflake driver to 3.13.32 due to build failures.
  liquibase-dist/pom.xml
  pom.xml
Labels: PRAssociated, skipReleaseNotes

#4508 [DAT-15383] Fix checksum upgrade changes preventing useless updates and using AbstractChangeLogHistoryService for extensions compatibility
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Labels: TypeBug

#4518 exclude certain command tests from executing on certain platforms
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: skipReleaseNotes

#4470 [DAT-15327] Fix dropAll clean up behavior.
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
Labels: TypeBug, sprint2023-55

#4490 fix format argument for history command (DAT-13382)
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeBug

#4497 bump LICENSE.txt year to 2023 (DAT-13059)
  LICENSE.txt
Labels: skipReleaseNotes

#4496 throw validation error on missing sqlFile (DAT-14920)
  liquibase-standard/src/main/java/liquibase/change/core/SQLFileChange.java
  liquibase-standard/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java
  liquibase-standard/src/test/resources/my/path/file.sql
Labels: TypeBug

#4485 DAT-14929: include rows affected in update command console output
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCountCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
  liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
Labels: TypeEnhancement

#4495 Do not throw exception when runWith is empty string (DAT-14316)
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/empty.runWith.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: TypeBug

#4483 Add ability to set labels and contexts in included changelogs DAT-15202
  liquibase-standard/src/main/java/liquibase/LabelExpression.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement

#4362 docs file fixes, link updates
  README.md
  liquibase-dist/src/main/archive/GETTING_STARTED.txt
  liquibase-dist/src/main/archive/README.txt
  liquibase-standard/src/main/java/liquibase/Contexts.java
  liquibase-standard/src/main/java/liquibase/LabelExpression.java
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/servlet/GenericServletListener.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
  liquibase-standard/src/test/groovy/liquibase/parser/core/xml/LiquibaseEntityResolverTest.groovy
Labels: TypeBug, autocandidate

#4089 Fix formatted SQL parse error when property has context, labels and global attributes
  liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug, RiskMedium, SafeToBuild

#4197 Consume CORE and PRO packages from GitHub Package Manager (DAT-14615)
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/build.yml
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
  liquibase-extension-testing/pom.xml
  liquibase-maven-plugin/pom.xml
  liquibase-maven-plugin/src/main/maven/release.pom.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/osgi/Activator.java
  liquibase-standard/src/main/java/liquibase/osgi/ContainerChecker.java
  pom.xml
Labels: TypeEnhancement

#4545 fix local dev builds
  liquibase-dist/pom.xml
  pom.xml
Labels: skipReleaseNotes

#4550 switch deploy.repositoryId to match other name changes (DAT-14615)
  .github/workflows/build-branch.yml
  liquibase-dist/pom.xml
  liquibase-maven-plugin/pom.xml
Labels: skipReleaseNotes

#4551 set server-id to liquibase in other workflow files (DAT-14615)
  .github/workflows/build-main.yml
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#4555 test functional tests with recent commits reverted
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/release-published.yml
  liquibase-dist/pom.xml
  liquibase-maven-plugin/pom.xml
  pom.xml
Labels: skipReleaseNotes

#4564 remove useless check
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4561 DAT-14615: revert maven plugin pom to old version
  liquibase-maven-plugin/pom.xml
  liquibase-maven-plugin/src/main/maven/release.pom.xml
Labels: skipReleaseNotes

#4563 Revert "test functional tests with recent commits reverted (#4555)" (DAT-14615)
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/release-published.yml
  liquibase-dist/pom.xml
  pom.xml
Labels: skipReleaseNotes

#4499 Fixed #4489: SQL Anywhere incorrectly reports VARCHAR(n CHAR) as VARCHAR(n)
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, SafeToBuild, DBSQLAnywhere

#4544 DAT-15470
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4540 [DAT-15489] Fixes changelog-sync-to-tag ignores the tag if it is already in database after 4.23.0
  liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
Labels: TypeBug

#4572 Revert "DAT-15470"
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4580 move repositories block into profile activated only on GHA (DAT-14615)
  liquibase-dist/pom.xml
  pom.xml
Labels: skipReleaseNotes

#4569 DAT-15545
  .github/workflows/build.yml
Labels: TypeBug
