Repository liquibase/liquibase, pull requests merged in 2023-09, with the labels that each got.

#4798 Fix poor performance of listunrunchangesets
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug, autocandidate

#4683 Fixed: #4682 - MSSQL: Doesn't support (n CHAR) syntax, but only (n) syntax
  liquibase-standard/src/main/java/liquibase/datatype/core/CharType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/VarcharType.java
  liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Labels: TypeBug, SafeToBuild, DBSQLAnywhere, sprint2023-58

#4589 Fixes JdbcExecutor's uses of RawParameterizedSqlStatement
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: TypeBug, SafeToBuild, autocandidate

#4841 Update README link to contribution docs
  README.md
Labels: TypeBug

#4805 include tag in history tabular output (DAT-15244)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/InternalHistoryCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/command/InternalHistoryCommandStepTest.groovy
Labels: TypeEnhancement

#4726 Allow update command to handle additional properties that are passed on the command line DAT-15769
  liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeBug

#4845 Fix liquibase.bat java home handling under Windows
  liquibase-dist/src/main/archive/liquibase.bat
Labels: TypeBug

#4648 Fixed: SQL Anywhere reports fancy precision with LONG NVARCHAR
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, SafeToBuild, autocandidate, DBSQLAnywhere, sprint2023-58

#4697 Replacing special constants specific to SQL Anywhere by commonly supported JDBC Escape Functions
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeEnhancement, SafeToBuild, autocandidate, DBSQLAnywhere

#4838 Bump groovy.version from 2.5.22 to 2.5.23
  pom.xml
Labels: sdou

#4670 Fixed: Fails to detect LONG VARCHAR as CLOB and LONG BINARY as BLOB
  liquibase-standard/src/main/java/liquibase/datatype/DataTypeFactory.java
  liquibase-standard/src/main/java/liquibase/datatype/core/BlobType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/ClobType.java
  liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Labels: TypeBug, SafeToBuild, autocandidate, DBSQLAnywhere, sprint2023-58

#4852 Separate sections of the branch name with a hyphen for dependabot PR's (DAT-15548)
  .github/dependabot.yml
Labels: skipReleaseNotes

#4812 More consistent message when included file is empty DAT-15551
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
  liquibase-standard/src/test/groovy/liquibase/parser/core/xml/AbstractChangeLogParserTest.groovy
Labels: TypeBug

#4827 Handle XML data types for DB2 DAT-12878
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/util/JdbcUtil.java
Labels: TypeBug

#4574 Implement showSummaryOutput parameter
  liquibase-integration-tests/src/test/groovy/liquibase/util/ShowSummaryUtilCommandTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/UpdateSummaryOutputEnum.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
  liquibase-standard/src/test/groovy/liquibase/command/TestAbstractCliWrapperCommandStepTest.groovy
Labels: TypeEnhancement, SafeToBuild, sprint2023-57

#4874 DAT-15857 - Fix for checksum upgrade in runWith change sets
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy
Labels: TypeBug

#4870 Tweaked exception message for invalid formatted SQL file
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug

#4887 Release notes for 4.23.2
  changelog.txt
Labels: skipReleaseNotes

#4846 do not attempt to recreate DBCL when it is specified with mixed case (DAT-15570)
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeBug

#4858 add API to ConfiguredValueModifier that allows overriding a String (DAT-15801)
  liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifier.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java
Labels: skipReleaseNotes

#4859 Fix regression in recognizing formatted SQL file DAT-15865
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
Labels: TypeBug

#4854 Fix LabelExpression constructors when using array or collection
  liquibase-standard/src/main/java/liquibase/ContextExpression.java
  liquibase-standard/src/main/java/liquibase/LabelExpression.java
  liquibase-standard/src/test/groovy/liquibase/ContextExpressionTest.groovy
  liquibase-standard/src/test/groovy/liquibase/LabelExpressionTest.groovy
Labels: TypeBug

#4899 using workflow_run
  .github/workflows/build-branch.yml
Labels: skipReleaseNotes

#4901 Revert "using workflow_run"
  .github/workflows/build-branch.yml
Labels: skipReleaseNotes

#4895 update example custom log data files (DAT-15796)
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.customlogdata.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.customlogdata.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.customlogdata.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.customlogdata.yaml
Labels: skipReleaseNotes

#4729 DAT-15603 Attach Azure jar to liquibase release artifacts
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/create-release.yml
Labels: TypeEnhancement

#4906 remove labelled trigger from build.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4909 Rollbacks Oracle Driver to LTS series 19.x
  liquibase-dist/pom.xml
  pom.xml
Labels: TypeBug

#4862 DAT-15821 :: OperationOutcomeErrorMsg field added to Operation Info
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
Labels: TypeBug

#4902 obfuscate user/pass in urls entered in MDC (DAT-15860)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeBug

#4705 DAT-15338 Refactor connection string patterns to allow extensions to extend they
  liquibase-standard/src/main/java/liquibase/database/jvm/ConnectionPatterns.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnectionPatterns.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.database.jvm.ConnectionPatterns
Labels: TypeBug

#4923 DAT-15922 add fossa license checking action
  .github/workflows/fossa.yml
Labels: sdou

#4925 CommandTests: copy files on the fly, not at startup
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: skipReleaseNotes

#4834 Optimise the logic for tableIsEmpty check constraint
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-standard/src/main/java/liquibase/precondition/core/TableIsEmptyPrecondition.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/TableIsEmptyGenerator.java
  liquibase-standard/src/main/java/liquibase/statement/core/TableIsEmptyStatement.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Labels: TypeEnhancement, ManualTest

#4579 Use native oracle BOOLEAN for >=23c | fixes #4576
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/CreateDatabaseChangeLogLockTableExecuteTest.java
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
Labels: TypeEnhancement, DBOracle, SafeToBuild, autocandidate

#4598 SQL Anywhere allows two foreign keys to differ only by name
  liquibase-standard/src/main/java/liquibase/structure/core/ForeignKey.java
Labels: TypeBug, SafeToBuild, DBSQLAnywhere

#4688 MySQL/MariaDB add extra info for date/timestamp columns for the diffChangeLog
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeEnhancement, ManualTest

#4762 Fetch ran change sets before updating check sums
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
Labels: TypeBug, SafeToBuild, sprint2023-58

#4725 Change type of `RowCountPrecondition#expectedRows` from `Integer` to `Long` (#1549)
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-standard/src/main/java/liquibase/precondition/core/RowCountPrecondition.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: TypeBug, XSD, sprint2023-59

#4931 Fix error message validation after conflicting merges
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
Labels: skipReleaseNotes

#4932 Firebird does not support afterColumn - fix tests on master
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Labels: skipReleaseNotes

#4912 add example checks packages files (DAT-15594)
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.checks-package.yaml
Labels: skipReleaseNotes

#4926 Adding properties to the update report template to allow all the update family commands to use reports DAT-15638
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
Labels: TypeEnhancement

#4944 Add firebird specific query to new TableIsEmpty sql generator
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/TableIsEmptyGenerator.java
Labels: skipReleaseNotes

#4900 Enable scoped value to be looked up from Java properties loaded from the command line -D properties DAT-15668
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/Scope.java
Labels: TypeBug

#4921 command tests improvements (DAT-15555)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCreateTempResources.groovy
Labels: skipReleaseNotes

#4937 [DAT-15924] Handle AbstractSQLChange runWith checksum v8 variants
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
Labels: TypeBug

#4799 parameter binding for DB2luw to improve performance and other trifles
  liquibase-snowflake/src/main/java/liquibase/snapshot/ResultSetCacheSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SnowflakeResultSetConstraintsExtractor.java
  liquibase-standard/src/main/java/liquibase/diff/DiffResult.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-standard/src/test/java/liquibase/test/DiffResultAssert.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-60

#4905 Check for duplicate core and commercial JARs DAT-15837
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
Labels: TypeEnhancement

#4956 Fix typo in SqlGeneratorFactory
  liquibase-standard/src/main/java/liquibase/sqlgenerator/SqlGeneratorFactory.java
Labels: TypeBug

#4961 Update create-release.yml
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#4963 Update build-azure-uber-jar.yml
  .github/workflows/build-azure-uber-jar.yml
Labels: skipReleaseNotes

#4965 Update build-azure-uber-jar.yml
  .github/workflows/build-azure-uber-jar.yml
Labels: skipReleaseNotes

#4966 Update build-azure-uber-jar.yml
  .github/workflows/build-azure-uber-jar.yml
Labels: skipReleaseNotes

#4967 reverting changes for uber-jar in create-release
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#4968 Add XSD file for 4.24.0 release
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.24.xsd
Labels: skipReleaseNotes

#4973 fix re-version.sh to accept release from specific branches
  .github/util/re-version.sh
  .github/workflows/create-release.yml
Labels: TypeBug, skipReleaseNotes

#4975 Update create-release.yml change to needs.setup
  .github/workflows/create-release.yml
Labels: TypeBug, skipReleaseNotes

#4976 GitHub action fix re version2
  .github/util/re-version.sh
Labels: TypeBug, skipReleaseNotes

#4977 GitHub action fix re version2
  .github/util/re-version.sh
Labels: TypeBug, skipReleaseNotes

#4979 GitHub action fix re version2
  .github/util/re-version.sh
Labels: TypeBug, skipReleaseNotes

#4993 DatabaseTestSystem: commit only if autocommit is not enabled
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/DatabaseTestSystem.java
Labels: skipReleaseNotes
