Repository liquibase/liquibase, pull requests merged in 2023-06, with the labels that each got.

#4132 runAlways should run regardless of checksum validation
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/test/groovy/liquibase/changelog/visitor/ValidatingVisitorTest.groovy
Labels: TypeBug, SafeToBuild, sprint2023-51

#4022 Fix liquibase.skip in maven plugin when activated in multithreaded build
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement, RiskLow, IntegrationMaven, SafeToBuild, sprint2023-49

#4179 Sybase JDBC: Detecting current and some historic driver versions
  liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java
Labels: TypeEnhancement, RiskLow, SafeToBuild, sprint2023-51, enhancement, newcontributors

#3901 Add errorIfMissingOrEmpty attribute to ChangeLogProperty and ChangeLogInclude classes
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogInclude.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogProperty.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement, RiskLow, ReleaseMajor, SafeToBuild, sprint2023-47

#3363 Add skipOnFileExists maven property for skipping plugin execution when a file exists
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement, RiskLow, IntegrationMaven, ReleaseMajor, SafeToBuild, sprint2023-48

#3813 Replace Statement by PreparedStament allowing the use of parameter markers on DB2z catalogue queries
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/ResultSetCache.java
Labels: TypeEnhancement, RiskLow, ReleaseMajor, SafeToBuild, sprint2023-48

#4023 migrate ChangeLogHistoryServiceFactory to AbstractPluginFactory pattern
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupChangeLogSync.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupChangelogHistory.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupDatabaseStructure.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupRollbackCount.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupRunChangelog.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/LiquibaseTestIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AbstractExecuteTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/change/core/TagDatabaseChange.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java
  liquibase-standard/src/main/java/liquibase/changelog/MockChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeLogSyncVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/StatusVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractFutureRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/InternalHistoryCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/ListLocksCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/TagCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/TagExistsCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/OfflineConnection.java
  liquibase-standard/src/main/java/liquibase/database/core/MockDatabase.java
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-standard/src/test/groovy/liquibase/change/core/TagDatabaseChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/command/InternalHistoryCommandStepTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/OfflineChangeLogHistoryServiceTest.java
Labels: TypeEnhancement, RiskLow, SafeToBuild, sprint2023-49

#4380 Fix paths starting with dot dot
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: sprint2023-53, bugfix

#4226 Add binary, varbinary and longvarbinary support for Snowflake #4225
  liquibase-snowflake/src/main/java/liquibase/datatype/core/BinaryTypeSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
  liquibase-snowflake/src/test/java/liquibase/datatype/BinaryTypeSnowflakeTest.java
Labels: TypeEnhancement, RiskLow, SafeToBuild

#4273 Liquibase should not fail when change log has only `databaseChangeLog` tag
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
  liquibase-standard/src/test/resources/liquibase/parser/core/yaml/emptyChangeLog.yaml
Labels: TypeBug, SafeToBuild, sprint2023-52

#3578 Issue 3562 - Required expression operator for context and label filters
  liquibase-standard/src/main/java/liquibase/ContextExpression.java
  liquibase-standard/src/main/java/liquibase/LabelExpression.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/ContextChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/LabelChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/util/ExpressionMatcher.java
  liquibase-standard/src/test/groovy/liquibase/util/ExpressionMatcherTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/filter/ContextChangeSetFilterTest.java
  liquibase-standard/src/test/java/liquibase/changelog/filter/LabelChangeSetFilterTest.java
Labels: TypeEnhancement, RiskMedium, SafeToBuild

#4408 exclude label
  .github/release-drafter.yml
Labels: skipReleaseNotes

#4419 Creates XSD for 4.23.0 release
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.23.xsd
Labels: skipReleaseNotes

#4421 Adding changelog for 4.23.0 release
  changelog.txt
Labels: skipReleaseNotes

#4409 DAT-15030
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/workflows/label-pr.yml
  .github/workflows/release-drafter.yml
Labels: TypeEnhancement

#4427 Fix update fast check behavior
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeBug, sprint2023-54

#4438 Fix manual trigger job ${version}
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#4439 Fix cleanup branches dat branches
  .github/dependabot.yml
  .github/workflows/cleanup-branch-builds.yml
  .github/workflows/cleanup-master-builds.yml
Labels: skipReleaseNotes

#4228 #4227 fix for BOOLEAN with precision like BOOLEAN(1)
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
Labels: TypeBug, SafeToBuild, sprint2023-52

#4450 Fix deploymentId not populating after locking
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeBug, TypeTest

#4417 Fixes issue #4415: "Wrong DDL syntax CREATE SEQUENCE ... AS ..."
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Labels: TypeBug, SafeToBuild, sprint2023-54

#4414 Fixes issue #4413: Undocumented IT requirement: Username "liquibase"
  liquibase-integration-tests/src/test/resources/changelogs/asany/complete/root.changelog.xml
Labels: TypeBug, SafeToBuild, sprint2023-54

#4219 Fixed CommandLineUtilsTest for german locale
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-standard/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/csv/CSVReaderTest.groovy
Labels: TypeTest, sprint2023-53

#4458 Fix mssql integration test timeout
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/MssqlMergeIntegrationTest.groovy
Labels: TypeBug, skipReleaseNotes

#4420 add additional MDC properties to update and diff mojos (DAT-14672)
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/PreCompareCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
Labels: TypeEnhancement

#4454 Fix changelogsync no longer generating deployment id.
  liquibase-integration-tests/src/test/groovy/liquibase/command/ChangelogSyncIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
Labels: TypeBug
