Repository liquibase/liquibase, pull requests merged in 2023-03, with the labels that each got.

#3775 DAT-6606, DAT-6607 (DAT-6623 too) and DAT-6613
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/AbstractDatabaseConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/CommandDefinition.java
  liquibase-core/src/main/java/liquibase/command/CommandFactory.java
  liquibase-core/src/main/java/liquibase/command/CommandResultsBuilder.java
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
  liquibase-core/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DiffCommand.java
  liquibase-core/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DiffToChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/GenerateChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalDiffChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalDiffCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalGenerateChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/DiffOutputControlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/PreCompareCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/providers/ReferenceDatabase.java
  liquibase-core/src/main/java/liquibase/integration/ant/GenerateChangeLogTask.java
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-core/src/test/groovy/liquibase/command/CommandFactoryTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogDb2CommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLCommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLCommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
Labels: sprint2023-44

#3616 Fix CheckSum generation issues + improvements
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-core/src/main/java/liquibase/change/CheckSum.java
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/sql/visitor/AbstractSqlVisitor.java
  liquibase-core/src/test/groovy/liquibase/change/AbstractChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/changelog/filter/ShouldRunChangeSetFilterTest.groovy
  liquibase-core/src/test/groovy/liquibase/hub/model/HubChangeTest.groovy
  liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java
  liquibase-core/src/test/java/liquibase/change/CheckSumTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy
Labels: PRAssociated, ReleaseMajor, sprint2022-40, sprint2022-41

#3595 Issue 3584: Add support for relativeToChangelogFile for ChangeLogProperty class/property attribute
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogProperty.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-core/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement, ReleaseMajor, SafeToBuild, XSD, sprint2023-42

#3892 Revert "Fix CheckSum generation issues + CURRENT_CHECKSUM_ALGORITHM_VERSION updated from 8 to 9."
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-core/src/main/java/liquibase/change/CheckSum.java
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/sql/visitor/AbstractSqlVisitor.java
  liquibase-core/src/test/groovy/liquibase/change/AbstractChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy
  liquibase-core/src/test/groovy/liquibase/changelog/filter/ShouldRunChangeSetFilterTest.groovy
  liquibase-core/src/test/groovy/liquibase/hub/model/HubChangeTest.groovy
  liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java
  liquibase-core/src/test/java/liquibase/change/CheckSumTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy
Labels: sprint2023-46

#3904 Safely call snakeyaml methods that have been changed in last versions.
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlParser.java
  liquibase-core/src/main/java/liquibase/util/SnakeYamlUtil.java
Labels: sprint2023-46

#3859 DAT-6603 & DAT-6604 - ChangelogSync family to CommandStep refactoring
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/CommandBuilder.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncToTagCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/ChangelogSyncToTagSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/HubHandler.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/OutputWriterCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/io/WriterOutputStream.java
  liquibase-core/src/main/java/liquibase/util/LoggingExecutorTextUtil.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-core/src/test/groovy/liquibase/command/CommandFactoryTest.groovy
  liquibase-core/src/test/resources/liquibase/integration/ant/ChangeLogSyncTaskTest.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSync.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncToTag.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/changelogSyncToTagSql.test.groovy
Labels: refactor, sprint2023-45

#3840 Improved concurrency support in ReflectionSerializer
  liquibase-core/src/main/java/liquibase/serializer/ReflectionSerializer.java
Labels: TypeBug, SafeToBuild, sprint2023-46

#3656 Make Pattern instance variables and avoid re calculating each time.
  liquibase-core/src/main/java/liquibase/change/CheckSum.java
  liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangelogRewriter.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
  liquibase-core/src/main/java/liquibase/configuration/ConfigurationDefinition.java
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/database/OfflineConnection.java
  liquibase-core/src/main/java/liquibase/database/core/CockroachDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/H2Database.java
  liquibase-core/src/main/java/liquibase/database/core/InformixDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/Ingres9Database.java
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-core/src/main/java/liquibase/datatype/core/TimeType.java
  liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/StandardNamespaceDetails.java
  liquibase-core/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-core/src/main/java/liquibase/structure/AbstractDatabaseObject.java
  liquibase-core/src/main/java/liquibase/util/SqlUtil.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystem.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-43

#3712 Java 8 improvements
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesCDIConfigBuilder.java
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/ExpectedChangesVisitor.java
  liquibase-core/src/main/java/liquibase/command/core/RegisterChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/configuration/ConfigurationProperty.java
  liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-core/src/main/java/liquibase/diff/DiffGeneratorFactory.java
  liquibase-core/src/main/java/liquibase/diff/compare/DatabaseObjectComparatorFactory.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/IndexComparator.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/PrimaryKeyComparator.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/UniqueConstraintComparator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedForeignKeyChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedIndexChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedViewChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingForeignKeyChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingViewChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/report/DiffToReport.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/lockservice/LockServiceFactory.java
  liquibase-core/src/main/java/liquibase/parser/SnapshotParserFactory.java
  liquibase-core/src/main/java/liquibase/parser/core/ParsedNode.java
  liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializerFactory.java
  liquibase-core/src/main/java/liquibase/serializer/SnapshotSerializerFactory.java
  liquibase-core/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogLockGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/AddForeignKeyConstraintStatement.java
  liquibase-core/src/main/java/liquibase/statement/core/AddUniqueConstraintStatement.java
  liquibase-core/src/main/java/liquibase/structure/DatabaseObjectCollection.java
  liquibase-core/src/main/java/liquibase/structure/core/ForeignKey.java
  liquibase-core/src/main/java/liquibase/structure/core/PrimaryKey.java
  liquibase-core/src/main/java/liquibase/structure/core/UniqueConstraint.java
  liquibase-core/src/main/java/liquibase/util/StringClauses.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-44

#3893 Snakeyaml 2.0
  liquibase-core/src/main/java/liquibase/util/SnakeYamlUtil.java
  pom.xml
Labels: sprint2023-46

#3707 Map 'double' to SQL type 'DOUBLE PRECISION' for an Oracle database (CORE-3165)
  liquibase-core/src/main/java/liquibase/datatype/core/DoubleType.java
  liquibase-core/src/test/groovy/liquibase/datatype/core/DoubleTypeTest.groovy
Labels: DBOracle, ReleaseMajor, SafeToBuild, sprint2023-44

#3943 Upgrades snakeyaml for installer
  liquibase-dist/src/main/maven/release.pom.xml
Labels: sprint2023-46

#3932 DAT-6617 - Refactor ReleaseLocksCommand
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/ReleaseLocksCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/releaseLocks.test.groovy
Labels: sprint2023-46

#3928 DAT-6614 - Refactor ListLocksCommand
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/ListLocksCommandStep.java
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ListLocksTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/listLocks.test.groovy
Labels: sprint2023-46

#3797 Improve use of generics in code
  liquibase-core/src/main/java/liquibase/AbstractExtensibleObject.java
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-core/src/main/java/liquibase/change/core/DropColumnChange.java
  liquibase-core/src/main/java/liquibase/configuration/AbstractConfigurationContainer.java
  liquibase-core/src/main/java/liquibase/database/core/H2Database.java
  liquibase-core/src/main/java/liquibase/diff/ObjectDifferences.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/DefaultDatabaseObjectComparator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedForeignKeyChangeGenerator.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXHandler.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlSnapshotParser.java
  liquibase-core/src/main/java/liquibase/serializer/AbstractLiquibaseSerializable.java
  liquibase-core/src/main/java/liquibase/serializer/ReflectionSerializer.java
  liquibase-core/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializer.java
  liquibase-core/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java
  liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/RawParameterizedSqlStatement.java
  liquibase-core/src/main/java/liquibase/structure/core/ForeignKey.java
  liquibase-core/src/main/java/liquibase/structure/core/PrimaryKey.java
  liquibase-core/src/main/java/liquibase/structure/core/Relation.java
  liquibase-core/src/main/java/liquibase/structure/core/UniqueConstraint.java
  liquibase-core/src/main/java/liquibase/util/StringClauses.java
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-45

#3900 JVM installer upgraded to version 17.0.6+10
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: sprint2023-46

#3853 Performance Improvement: optimized DatabaseChangeLog.normalizePath()
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: sprint2023-46

#3927 Clear entries from MDC map on scope exit
  liquibase-core/src/main/java/liquibase/Scope.java
Labels: TypeBug, hacktoberfest, SafeToBuild, sprint2023-46, Mdc

#3912 [3910] fix missing OSGI manifest entries for service loaders
  liquibase-core/pom.xml
Labels: SafeToBuild, integerationOSGi, sprint2023-46

#3842 Fixes #3734 MySQL ENUM and SET column type
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogDb2CommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLCommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLCommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/enum.changelog.xml
Labels: TypeBug, SafeToBuild, sprint2023-46

#3926 only set the execType to RERAN, if the changeset was actually executed
  liquibase-core/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
Labels: TypeBug, SafeToBuild, sprint2023-47

#4015 Upgrade spring 5 version
  pom.xml
Labels: sprint2023-47

#3991 DAT-6624 & DAT-6625 - Rollback and RollbackSQL command refactoring
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/RollbackSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCountCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateCountSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateToTagSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/AbstractHelperCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/ChangeExecListenerCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/DiffOutputControlCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/OutputWriterCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/helpers/PreCompareCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollback.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/rollbackSql.test.groovy
Labels: sprint2023-47

#3960 [3906] Don't break Liquibase if a resolveable hostname is not found
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-core/src/main/java/liquibase/util/NetUtil.java
Labels: sprint2023-46, Mdc

#3378 Load XSD files under OSGI
  liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
Labels: TypeBug, SafeToBuild, XSD, integerationOSGi, sprint2022-41, sprint2023-46

#3849 Fixes #3083 MySQL JSON length issue
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLCommandTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
Labels: TypeBug, SafeToBuild, sprint2023-47

#3903 Prevention of NullpointerException (unboxing) in generate-changelog with MS SQL Server
  liquibase-core/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
Labels: TypeBug, SafeToBuild, sprint2023-47

#4046 Lowers message log level.
  liquibase-core/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java
Labels: sprint2023-47

#3640 Remove potentially sensitive information from --monitor-performance
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Labels: TypeBug, SafeToBuild

#4034 Do not ignore DatabaseException for Snowflake
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/invalid.sql.changelog.xml
  liquibase-snowflake/src/main/java/liquibase/executor/jvm/SnowflakeJdbcExecutor.java
Labels: PRAssociated, sprint2023-47
