Repository liquibase/liquibase, pull requests merged in 2023-10, with the labels that each got.

#4986 add test to confirm contents of tar.gz artifact: DAT-15984
  .github/workflows/build.yml
  liquibase-dist/expected-distribution-contents.txt
Labels: skipReleaseNotes

#4904 add empty mdc values to all commands (DAT-15671)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-extension-testing/pom.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/AfterTagChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: TypeEnhancement

#4945 Filter additional credential-like strings in the URL sanitization process DAT-9973
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshotReference.test.groovy
  liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-standard/src/main/java/liquibase/command/CommonArgumentNames.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnectionPatterns.java
  liquibase-standard/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy
Labels: TypeBug

#4928 CodeQL scan issue fixes
  liquibase-standard/src/main/java/liquibase/database/core/Ingres9Database.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug, TypeRefactor

#4992 fix-branch-build BOT_TOKEN issue
  .github/workflows/build-branch.yml
Labels: TypeBug, skipReleaseNotes

#4982 DAT-15880
  .github/workflows/build.yml
Labels: TypeBug

#4970 DAT-15603
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5011 Testing DAT-16016
  .github/workflows/build.yml
Labels: TypeEnhancement

#4997 DAT-16016
  .github/workflows/build.yml
  .github/workflows/release-drafter.yml
Labels: skipReleaseNotes

#5006 Update release-published.yml
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5018 DAT-16016
  .github/release-drafter-master.yml
  .github/release-drafter-release.yml
  .github/workflows/build.yml
  .github/workflows/release-drafter.yml
Labels: TypeEnhancement, skipReleaseNotes

#5014 move findKeyInMapIgnoreCase to CollectionUtil
  liquibase-standard/src/main/java/liquibase/util/CollectionUtil.java
Labels: skipReleaseNotes

#5009 Do not convert if global flag is false DAT-15745
  liquibase-standard/src/main/java/liquibase/datatype/core/ClobType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/TimestampType.java
  liquibase-standard/src/test/java/liquibase/datatype/ClobTypeTest.java
Labels: TypeBug

#5019 [DAT-15756] Fix sonar blocker warnings
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-standard/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/jvm/ConnectionPatterns.java
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-standard/src/test/java/liquibase/lockservice/StandardLockServiceTest.java
Labels: TypeEnhancement, enhancement

#5021 DAT-16029 DevOps: liquibase-pro (and possibly liquibase) sonar scans for PRs are scanning code from master
  .github/workflows/build.yml
Labels: skipReleaseNotes

#5036 DAT-16043 Community contributed PR's are not building
  .github/workflows/build-branch.yml
Labels: TypeBug, SafeToBuild, skipReleaseNotes

#4463 Split calculate-checksum parameter changeSetIdentifier into changeSetPath / changesetId / changeSetAuthor
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeEnhancement, DocRequired, SafeToBuild, BreakingChange, sprint2023-56

#4995 [DAT-16006] Fixing v8 Checksum calculation issue when using sql dbms attribute
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/checksum/create-table.sql
  liquibase-integration-tests/src/test/resources/changelogs/h2/checksum/dbms-filter-changelog.xml
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java
Labels: TypeBug

#4985 Fix liquibase bat
  liquibase-dist/src/main/archive/liquibase.bat
Labels: TypeBug, SafeToBuild

#5012 DAT-15755 - Sonar issues fix
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/H2Database.java
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/PrimaryKeySnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/util/LiquibaseUtil.java
Labels: TypeEnhancement

#4996 Check for other duplicate JAR files in classpath DAT-15963
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
Labels: TypeEnhancement

#5046 DAT-16043 Community contributed PR's are not building
  .github/workflows/build-branch.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4549 generateChangelog creates crippled view definition SQL
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
Labels: TypeBug, SafeToBuild, DBSQLAnywhere

#4919 Add '@Deprecated' annotation to update() methods
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeEnhancement, SafeToBuild

#4959 Remove unnecessary conditions in IndexComparator
  liquibase-standard/src/main/java/liquibase/diff/compare/core/IndexComparator.java
Labels: TypeTechDebt

#4104 Support system properties as a way of providing configuration options to the CLI
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncherSettings.java
Labels: TypeEnhancement, RiskLow, DocRequired, SafeToBuild, sprint2023-51, runFunctionalTests

#5053 add option to show hidden arguments in help output
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: skipReleaseNotes

#5049 allow lowercasing in ToStringFormatter (DAT-15870)
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: skipReleaseNotes

#4301 Simplified expressions, removed redundant expressions, fixed javadocs
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/change/Change.java
  liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropPrimaryKeyChange.java
  liquibase-standard/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-standard/src/main/java/liquibase/change/core/MergeColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/OutputWriterCommandStep.java
  liquibase-standard/src/main/java/liquibase/lockservice/MockLockService.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ChangeSetExecutedPrecondition.java
  liquibase-standard/src/main/java/liquibase/serializer/ReflectionSerializer.java
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/PrimaryKeySnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddAutoIncrementGeneratorMySQL.java
  liquibase-standard/src/main/java/liquibase/statement/BatchDmlExecutablePreparedStatement.java
  liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
  liquibase-standard/src/main/java/liquibase/structure/core/Index.java
Labels: TypeEnhancement, SafeToBuild, TypeTechDebt, sprint2023-53

#5060 Exclude new pro dependencies from lib directory (DAT-15871)
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: skipReleaseNotes

#5064 Handle some potential NPEs Github issue 5063
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/JdbcSnapshotGenerator.java
Labels: TypeBug

#5048 deprecate StringUtil#wrap method (DAT-15868)
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: skipReleaseNotes

#4664 Fixed: #4662 - PostgreSQL: Doesn't support (n CHAR) syntax, but only (n) syntax.
  liquibase-standard/src/main/java/liquibase/datatype/core/CharType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/VarcharType.java
Labels: TypeBug, DocRequired, SafeToBuild, DBSQLAnywhere

#5047 show failed changesets in verbose show-summary output (DAT-15141)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/report/ShowSummaryGenerator.java
  liquibase-standard/src/main/java/liquibase/report/ShowSummaryGeneratorFactory.java
  liquibase-standard/src/main/java/liquibase/report/StandardShowSummaryGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
Labels: TypeEnhancement

#5041 add rollback-to-date report (DAT-15660)
  liquibase-standard/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java
Labels: TypeEnhancement

#4994 execute-sql command logic updated to not display select columns sorted
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ExecuteSqlPostgresIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/executeSql.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
Labels: TypeBug

#5042 Makes picocli dependency optional for core
  liquibase-core/pom.xml
Labels: TypeEnhancement

#5039 Add changelog file path to upToDateFastCheck cache key (#4891)
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: TypeBug

#5054 Handle duplicates of the commercial JAR DAT-16059
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
Labels: TypeBug

#5062 Modify MSSQL query for when obtaining autoincrement column information GH-4719
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnAutoIncrementService.java
Labels: TypeBug

#5075 DAT-16016
  .github/release-drafter-master.yml
  .github/release-drafter-release.yml
  .github/workflows/release-drafter.yml
  .github/workflows/sync-release-master-branch.yml
Labels: TypeEnhancement

#5085 Update build-azure-uber-jar.yml
  .github/workflows/build-azure-uber-jar.yml
Labels: skipReleaseNotes

#5086 Fix build azure uber jars
  .github/workflows/build-azure-uber-jar.yml
Labels: skipReleaseNotes

#4293 Fix DB2 integration tests DAT-13113
  .github/workflows/build.yml
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/DB2TestSystem.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/wrapper/DockerDatabaseWrapper.java
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/db2/rollback/rollbackable.changelog.xml
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/TableIsEmptyGenerator.java
Labels: TypeBug

#5103 Revert "Bump actions/checkout from 3 to 4"
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/create-release.yml
  .github/workflows/fossa.yml
  .github/workflows/installer-build-check.yml
  .github/workflows/release-published.yml
  .github/workflows/sync-release-master-branch.yml
  .github/workflows/url-check.yml
Labels: skipReleaseNotes

#5105 Revert "Revert "Bump actions/checkout from 3 to 4" (#5103)"
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/create-release.yml
  .github/workflows/fossa.yml
  .github/workflows/installer-build-check.yml
  .github/workflows/release-published.yml
  .github/workflows/sync-release-master-branch.yml
  .github/workflows/url-check.yml
Labels: skipReleaseNotes

#5078 Fix Liquibase.rollback scope execution
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeBug

#5107 DAT-16122
  .github/workflows/build.yml
Labels: skipReleaseNotes

#5118 not sure why we were using getCurrentBranchLabel instead of getCurren…
  .github/workflows/build.yml
Labels: skipReleaseNotes

#5119 Update build.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4927 DAT-15922 FOSSA Support
  .github/workflows/fossa.yml
Labels: sdou

#5129 DAT-16123
  liquibase-core/pom.xml
  liquibase-dist/pom.xml
Labels: skipReleaseNotes

#5109 move SqlParser into factory pattern (DAT-15679)
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/parser/LiquibaseSqlParser.java
  liquibase-standard/src/main/java/liquibase/parser/SqlParserFactory.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
  liquibase-standard/src/main/java/liquibase/util/SqlParser.java
  liquibase-standard/src/main/java/liquibase/util/StandardSqlParser.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/test/groovy/liquibase/util/SqlParserTest.groovy
Labels: skipReleaseNotes

#5115 DAT-9019 Automate uploading liquibase. liquibase pro xsd files to liquibase.org wordpress site
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#5113 DAT-15718 Release docker on liquibase release-published
  .github/workflows/release-extensions.yml
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#5138 move file-replacer-maven-plugin definition to maven central
  .github/workflows/build-azure-uber-jar.yml
Labels: skipReleaseNotes

#567 Improve deferrable validation for AddForeignKey constraints generator
  liquibase-standard/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/core/MockDatabase.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
Labels: RiskMedium, SafeToBuild, needs_response, sprint2023-56

#5135 Update installer JDK
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: sdou

#4991 Update MySQL default value handling to allow defaultValueComputed on MySQL 5.7
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorMySQL.java
  liquibase-standard/src/test/groovy/liquibase/sqlgenerator/core/AddDefaultValueGeneratorMySQLTest.groovy
Labels: TypeEnhancement, DBMySQL, DocNeeded, SafeToBuild

#5127 5126 fix extra column info for mariadb database
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, SafeToBuild

#5077 showSummaryOutput property added for update command
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java
Labels: TypeEnhancement

#4801 CreateIndex associatedWith property deserialization issue
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/index.with.associatedwith.changelog.xml
  liquibase-standard/src/main/java/liquibase/change/core/CreateIndexChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/CreateIndexChangeTest.groovy
Labels: TypeBug, SafeToBuild, sprint2023-60

#5087 Handles snapshot of Oracle temporary tables + ignore queue tables
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug, TypeEnhancement
