Repository liquibase/liquibase, pull requests merged in 2023-02, with the labels that each got.

#3662 Consistent ARG-suffix for 'defaultSchemaName'-Parameter
  liquibase-core/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
Labels: SafeToBuild, sprint2023-43

#3670 Remove unnecessary cast expressions.
  liquibase-core/src/main/java/liquibase/command/core/StartH2CommandStep.java
  liquibase-core/src/main/java/liquibase/database/core/MockDatabase.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/ChangedIndexChangeGenerator.java
  liquibase-core/src/main/java/liquibase/osgi/Activator.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-core/src/main/java/liquibase/precondition/core/IndexExistsPrecondition.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddUniqueConstraintGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropUniqueConstraintGenerator.java
  liquibase-core/src/main/java/liquibase/util/SmartMap.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-43

#3588 Performance improvements
  liquibase-core/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParser_RealFile_Test.groovy
  liquibase-integration-tests/src/test/resources/changelogs/common/invalid.xsd.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/validate.test.groovy
Labels: ReleaseMajor, performance, sprint2022-40, sprint2023-42, sprint2023-43

#3541 Support tabular format for history command
  liquibase-core/src/main/java/liquibase/command/core/HistoryCommand.java
  liquibase-core/src/main/java/liquibase/command/core/HistoryCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/HistoryFormat.java
  liquibase-core/src/main/java/liquibase/command/core/InternalHistoryCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/util/TableOutput.java
  liquibase-core/src/test/groovy/liquibase/command/InternalHistoryCommandStepTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/ObjectUtilTest.groovy
  liquibase-core/src/test/groovy/liquibase/util/TableOutputTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
Labels: TypeEnhancement, PRAssociated, ReleaseMajor, SafeToBuild, sprint2023-43

#3677 Removing explicit LiquibaseServletListener references
  liquibase-core/src/main/java/liquibase/integration/servlet/GenericServletListener.java
Labels: TypeBug, SafeToBuild, sprint2023-44

#3752 Add Snowflake structured data types to unmodifiable Data Types
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
Labels: DBSnowflake, SafeToBuild, sprint2023-44

#3691 Fix #3690 primaryKeyExists does not work on DB2z
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug, SafeToBuild, sprint2023-44

#3657 Remove Unnecessary operation/modifier:
  liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/database/PreparedStatementFactory.java
  liquibase-core/src/main/java/liquibase/datatype/DataTypeFactory.java
  liquibase-core/src/main/java/liquibase/hub/core/StandardHubService.java
  liquibase-core/src/main/java/liquibase/integration/ant/DBDocTask.java
  liquibase-core/src/main/java/liquibase/integration/ant/type/DatabaseType.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/logging/core/BufferedLogService.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlSnapshotParser.java
  liquibase-core/src/main/java/liquibase/precondition/ErrorPrecondition.java
  liquibase-core/src/main/java/liquibase/precondition/FailedPrecondition.java
  liquibase-core/src/main/java/liquibase/precondition/core/PreconditionContainer.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java
  liquibase-core/src/main/java/liquibase/snapshot/SnapshotIdService.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java
  liquibase-core/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-43

#3686 Replace old stream creation with java.nio.
  liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-core/src/main/java/liquibase/configuration/core/DefaultsFileValueProvider.java
  liquibase-core/src/main/java/liquibase/integration/commandline/ChangeExecListenerUtils.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-core/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
  liquibase-core/src/main/java/liquibase/util/FileUtil.java
  liquibase-core/src/test/java/liquibase/integration/commandline/ChangeExecListenerUtilsTest.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupModifyProperties.groovy
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/util/DownloadUtil.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseFlowMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/plugins/AbstractLiquibaseMojoTest.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-44

#3628 Do not duplicate clearCheckSums logic
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy
Labels: TypeBug, SafeToBuild, checksum, sprint2023-44

#3709 Fixing #3708 - AddColumn fix for H2 version 1.4.200
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-core/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
Labels: SafeToBuild, sprint2023-44

#3756 Added default values to private Scope constructor
  liquibase-core/src/main/java/liquibase/Scope.java
Labels: TypeBug, SafeToBuild, sprint2023-44

#3799 Improved concurrency support by using ConcurrentHashMaps
  liquibase-core/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java
  liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializerFactory.java
  liquibase-core/src/main/java/liquibase/serializer/SnapshotSerializerFactory.java
  liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnAutoIncrementService.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/structure/DatabaseObjectCollection.java
  liquibase-core/src/main/java/liquibase/structure/core/Catalog.java
  liquibase-core/src/main/java/liquibase/structure/core/Schema.java
  liquibase-core/src/main/java/liquibase/util/ObjectUtil.java
Labels: SafeToBuild, sprint2023-44

#3717 fixing lookahead for lastline comment method
  liquibase-core/src/main/java/liquibase/util/StringUtil.java
  liquibase-core/src/test/groovy/liquibase/util/StringUtilTest.groovy
Labels: SafeToBuild, sprint2023-44

#3790 Do not calculate checksum when loading changelogs
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
Labels: performance, sprint2023-44

#3783 Fix failing EnvironmentValueProviderTest
  liquibase-core/src/test/groovy/liquibase/configuration/core/EnvironmentValueProviderTest.groovy
Labels: sprint2023-45

#3632 Update SnakeYAML usage - do not call deprecated methods
  liquibase-core/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-core/src/main/java/liquibase/parser/core/yaml/YamlParser.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/LiquibaseSdkConfigurationValueProvider.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-43

#3727 Avoid global mutable state of Non-final fields in enumeration types.
  liquibase-core/src/main/java/liquibase/change/ChangeStatus.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/precondition/core/PreconditionContainer.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-45

#3716 Use constants instead of arrays with known lengths of zero
  liquibase-core/src/main/java/liquibase/change/core/DropAllForeignKeyConstraintsChange.java
  liquibase-core/src/main/java/liquibase/change/core/DropColumnChange.java
  liquibase-core/src/main/java/liquibase/change/core/EmptyChange.java
  liquibase-core/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/change/core/LoadUpdateDataChange.java
  liquibase-core/src/main/java/liquibase/change/core/MergeColumnChange.java
  liquibase-core/src/main/java/liquibase/change/core/RenameSequenceChange.java
  liquibase-core/src/main/java/liquibase/change/core/RenameTableChange.java
  liquibase-core/src/main/java/liquibase/change/core/TagDatabaseChange.java
  liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
Labels: TypeEnhancement, java, SafeToBuild, sprint2023-44

#3736 Simplify lambda expressions when possible
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-core/src/main/java/liquibase/command/core/StartH2CommandStep.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/DropDefaultValueGenerator.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-45

#3868 DAT-13659 Fix nullpointers on table output
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/util/TableOutput.java
Labels: sprint2023-45
