Repository liquibase/liquibase, pull requests merged in 2023-08, with the labels that each got.

#4583 DAT-15545
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
Labels: TypeBug

#4581 DAT-15208 :: Changeset object added back to "Update command completed successfully" JSON
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: TypeBug, sprint2023-56

#4533 decode URL encoded path in DirectoryPathHandler (DAT-15154)
  liquibase-standard/src/main/java/liquibase/resource/DirectoryPathHandler.java
Labels: TypeBug

#4416 Normalize path using static function for Strings rather than Path.nor…
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeBug, ManualTest, SafeToBuild, sprint2023-55

#4308 Fix issue #3317 - StringIndexOutOfBoundsException if date is set to 1970-01-01
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/test/java/liquibase/changelog/OfflineChangeLogHistoryServiceTest.java
Labels: TypeBug, SafeToBuild, sprint2023-53

#4353 Add support for valueSequenceNext in Snowflake
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
  liquibase-snowflake/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorSnowflakeTest.java
Labels: TypeBug, PRAssociated, SafeToBuild, sprint2023-53

#4599 run tests on any branch
  .github/workflows/build-branch.yml
Labels: TypeEnhancement

#4587 DAT-15545
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/build.yml
Labels: TypeBug

#4604 DAT-15545
  .github/workflows/build-main.yml
Labels: skipReleaseNotes

#4606 DAT-15545-modifications
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
Labels: skipReleaseNotes

#4539 DAT-15417 PR for setLabels/setContexts build
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
Labels: TypeEnhancement

#4506 Add command line args to scope DAT-15396
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-dist/pom.xml
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  pom.xml
Labels: TypeEnhancement

#4602 DAT-15548 Build process is not working for branchs containing "/" on their names
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/build.yml
Labels: TypeBug

#4612 deprecate snyk in favor of github advanced security
  .github/workflows/snyk.yml
Labels: sdou

#4614 Fix merge conflict
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4615 DAT-15622 Attach Artifacts To Draft Release workflow fails because artifact name has been chnaged
  .github/util/re-version.sh
Labels: TypeBug

#4476 [DAT-15258] Makes sure that plugins that implements change are supporting the current database.
  liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
  liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
Labels: TypeEnhancement

#4622 DAT-15622
  .github/workflows/create-release.yml
Labels: TypeBug

#4623 DAT-15622
  .github/util/re-version.sh
Labels: TypeBug

#4624 DAT-15622
  .github/util/re-version.sh
  .github/workflows/create-release.yml
Labels: TypeBug

#4627 DAT-15622
  .github/util/re-version.sh
Labels: TypeBug

#4629 DAT-15622
  .github/util/re-version.sh
Labels: skipReleaseNotes

#4630 DAT-15622
  .github/util/re-version.sh
Labels: skipReleaseNotes

#4626 Updated changelog with 4.23.1 changes
  changelog.txt
Labels: skipReleaseNotes

#4631 Fix re-version.sh
  .github/util/re-version.sh
Labels: skipReleaseNotes

#4632 Fix re-version.sh again
  .github/util/re-version.sh
Labels: skipReleaseNotes

#4633 DAT-15622
  .github/workflows/create-release.yml
Labels: TypeEnhancement

#4637 GitHub action dat 15622 build installer
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  liquibase-dist/pom.xml
Labels: TypeBug

#4638 chore(build.yml): remove copying of liquibase-*.deb artifact to impro…
  .github/workflows/build.yml
Labels: TypeBug

#4640 GitHub action dat 15622 build installer
  .github/util/re-version.sh
Labels: TypeBug

#4649 chore(re-version.sh): remove reversion of deb package creation code
  .github/util/re-version.sh
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
Labels: TypeBug

#4652 Remove liquibase-env.sh from installer and zip as it is only used by deb package.
  liquibase-dist/pom.xml
  liquibase-dist/src/main/deb/liquibase-env.sh
Labels: skipReleaseNotes

#4654 Correctly escape spaces in table name when it is used in a query DAT-11529
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
Labels: TypeBug

#4619 DAT-15599
  .github/workflows/build.yml
Labels: TypeBug, TypeEnhancement, skipReleaseNotes

#4628 DAT -15524 Clear-Checksums implementation using command scope
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/clearChecksums.test.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/command/core/ClearChecksumsCommandStep.java
Labels: TypeEnhancement, TypeRefactor, sprint2023-57

#4672 DAT-15602
  .github/workflows/archive workflows/build-branch.yml
  .github/workflows/build-branch.yml
  .github/workflows/build.yml
Labels: TypeBug

#4673 Revert "DAT-15602"
  .github/workflows/archive workflows/build-branch.yml
  .github/workflows/build-branch.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4671 add Lombok (DAT-12612)
  liquibase-standard/pom.xml
Labels: skipReleaseNotes

#4605 custom log data key-value pairs are injected multiple times per operation (DAT-15572)
  liquibase-standard/src/main/java/liquibase/util/ValueHandlerUtil.java
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.customlogdata.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.customlogdata.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.customlogdata.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.customlogdata.yaml
Labels: TypeEnhancement

#4625 Handle leading spaces in formatted SQL changelog DAT-15221
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/ChangeLogParserFactory.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug

#4675 DAT-15602
  .github/workflows/archive workflows/build-branch.yml
  .github/workflows/build-branch.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4611 [DAT-15439] Fix adding redundant semicolon character for generateChangelog for MSSQL
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
Labels: TypeBug

#4686 Revert "DAT-15602 (#4675)"
  .github/workflows/archive workflows/build-branch.yml
  .github/workflows/build-branch.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4585 DAT-15470
  .github/workflows/build.yml
Labels: TypeBug

#4659 DAT-15646 DevOps - Reusable Debian Package Creation Workflow Migration
  .github/workflows/build.yml
  .github/workflows/release-published.yml
  liquibase-dist/pom.xml
  liquibase-dist/src/deb/control/control
  liquibase-dist/src/deb/control/postinst
Labels: TypeEnhancement

#4690 Revert "DAT-15470"
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4687 DAT-15602
  .github/workflows/build-branch.yml
  .github/workflows/build-main.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4693 Update build.yml to use @master for call-build-branch
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4689 Make operation start time be UTC DAT-15593
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
Labels: TypeBug

#4680 Allow both include and includeAll to appear in modifyChangeSets tag
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: TypeEnhancement

#4660 Add labels/contexts arguments to diffChangelog and generateChangelog change sets DAT-14793
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
Labels: TypeEnhancement

#4700 Revert "Allow both include and includeAll to appear in modifyChangeSets tag"
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: skipReleaseNotes

#4618 DAT-15604
  .github/workflows/build-main.yml
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4707 DAT-15602
  .github/workflows/build-branch.yml
Labels: skipReleaseNotes

#4534 Fix database test system external driver load.
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/DatabaseTestSystem.java
Labels: TypeBug, autocandidate, TypeTest

#4515 Fixed: LONG VARCHAR DEFAULT NULL instead of LONG VARCHAR DEFAULT 'NULL'
  liquibase-standard/src/main/java/liquibase/util/SqlUtil.java
Labels: TypeBug, ManualTest, SafeToBuild

#4148 maven-plugin: Support increasing maven log level
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLog.java
Labels: TypeEnhancement, RiskMedium, SafeToBuild, sprint2023-52

#4715 DAT-15602
  .github/workflows/build-branch.yml
Labels: skipReleaseNotes

#4387 Use more parameter markers for DB2z catalogue queries
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGeneratorSnowflake.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-standard/src/test/groovy/liquibase/snapshot/jvm/SequenceSnapshotGeneratorTest.groovy
Labels: TypeEnhancement, DBDB2Z, SafeToBuild, sprint2023-54

#4480 not to use class field for thread safe.
  liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy
Labels: TypeBug, SafeToBuild

#4724 Add alias for log level FINE in maven
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLog.java
Labels: skipReleaseNotes

#4735 disable the concurrency check on master branch
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4736 do not archive test results by default
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4738 Revert "disable the concurrency check on master branch"
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4733 fix flaky UpgradeChecksumVersionIntegrationTest
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
Labels: skipReleaseNotes

#4709 Fix Regression in 4.23.1 where Log table is created multiple times for H2 and HSQLDB
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: TypeBug

#4740 removing workflow_run on Build Branch SNAPSHOT
  .github/workflows/build.yml
Labels: skipReleaseNotes

#4681 simplify build-main file
  .github/workflows/build-main.yml
Labels: skipReleaseNotes

#4751 Adding more log level aliases.
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenLog.java
Labels: skipReleaseNotes

#4402 New Feature: Add an endsWithFilter attribute to includeAll
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIncludeAll.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/resource/AbstractPathResourceAccessor.java
  liquibase-standard/src/main/java/liquibase/resource/ResourceAccessor.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement, RiskMedium, ReleaseMajor, SafeToBuild, XSD, sprint2023-54

#4701 DAT-15110
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: skipReleaseNotes

#4507 Fixing Issue #4429: SQL Anywhere: generateChangeLog fails when column's default value is an expression (e. g. Unexpected error running Liquibase: Unknown boolean value: if "mycol" is null then 0 else 1 endif)
  liquibase-integration-tests/src/test/java/liquibase/dbtest/asany/SybaseASAIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/asany/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java
  liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: TypeBug, RiskMedium, SafeToBuild, DBSQLAnywhere

#4658 Upgrade installer version to 17.0.8+7
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: TypeEnhancement, ManualTest

#4653 Allow DatabaseChangelog object to be passed as a parameter to DatabaseChangelogCommandStep
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeBug

#4591 Added changelog parameters to rollback commands
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeBug, SafeToBuild, autocandidate, sprint2023-56

#4609 fix standardlockservice when changelog-lock-wait-time-in-minutes is set to 0 and lock does not exist in database
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: TypeBug, ManualTest, SafeToBuild, autocandidate

#4520 Fixed: SQL Anywhere reports fancy precision with DOUBLE, SMALLINT and TINYINT
  liquibase-standard/src/main/java/liquibase/datatype/core/DoubleType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/SmallIntType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/TinyIntType.java
Labels: TypeBug, SafeToBuild, autocandidate, DBSQLAnywhere, sprint2023-57

#4537 SQL Anywhere: Switching off view definition checks to allow creation of dependent views even if dependency does not yet exist.
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
  liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createView/asany.sql
Labels: TypeEnhancement, SafeToBuild

#4541 remove dependency on javax.activation
  liquibase-standard/pom.xml
Labels: TypeBug, autocandidate

#4404 enable REPLACE OR EXISTS for procedures on DB2
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
Labels: TypeBug, DBDB2Z, SafeToBuild, sprint2023-54

#4651 Fixing issue #4650
  liquibase-standard/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SetViewRemarksGenerator.java
Labels: TypeBug, SafeToBuild, DBSQLAnywhere, sprint2023-58

#4461 support concurrent build in maven plugin
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/ThreadLocalScopeManager.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractOutputWriterCommandStep.java
  liquibase-standard/src/main/java/liquibase/resource/ZipResourceAccessor.java
  liquibase-standard/src/test/groovy/liquibase/change/StandardChangeTest.groovy
  liquibase-standard/src/test/java/liquibase/TestScopeManager.java
  liquibase-standard/src/test/java/liquibase/integration/ant/AbstractAntTaskTest.java
  liquibase-standard/src/test/java/liquibase/verify/change/VerifyChangeClassesTest.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-56

#4782 DAT-15790 add security reports
  .github/workflows/codeql.yml
  .github/workflows/ghas-report.yml
Labels: sdou

#3978 Introducing removeChangeSetProperty feature
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
  liquibase-standard/src/main/java/liquibase/change/Change.java
  liquibase-standard/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/visitor/AbstractChangeVisitor.java
  liquibase-standard/src/main/java/liquibase/change/visitor/AddColumnChangeVisitor.java
  liquibase-standard/src/main/java/liquibase/change/visitor/ChangeVisitor.java
  liquibase-standard/src/main/java/liquibase/change/visitor/ChangeVisitorFactory.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/change/core/AddColumnChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/change/visitor/AddColumnChangeVisitorTest.groovy
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement, RiskMedium, ReleaseMajor, SafeToBuild, XSD, sprint2023-53

#4352 Adding support to parameters referenceLiquibaseCatalogName and referenceLiquibaseSchemaName.
  liquibase-integration-tests/src/test/groovy/liquibase/command/diff/DiffIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/snapshotReference.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-52

#4772 Make sure that the correct argument name is displayed in help for commands with aliases DAT-15681
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
Labels: TypeBug

#4791 Bump whelk-io/maven-settings-xml-action from 20 to 21
  .github/workflows/build.yml
Labels: sdou

#4692 add update report (DAT-15576)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCountSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTagSql.test.groovy
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
Labels: TypeEnhancement

#4785 change MdcManager API to accept Map<String, Object> instead of Map<String, String> (DAT-15799)
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/changelog/ExpressionExpander.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/MdcManager.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/NoOpMdcManager.java
Labels: APIBreakingChanges

#4792 Bump org.junit.jupiter:junit-jupiter-params from 5.9.3 to 5.10.0
  liquibase-standard/pom.xml
Labels: sdou

#4810 fix installer build GHA
  .github/workflows/installer-build-check.yml
Labels: skipReleaseNotes

#4803 Fix liquibase 4.23.1 won't work on windows if there is no JAVA_HOME system variable set
  liquibase-dist/src/main/archive/liquibase.bat
Labels: TypeBug, ManualTest
