Repository liquibase/liquibase, pull requests merged in 2023-05, with the labels that each got.

#4151 Always use LockService from Factory when running command steps
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/command/UpdateCommandsTest.groovy
  liquibase-standard/src/test/resources/liquibase/update-tests.yml
Labels: sprint2023-49

#4019 Fixed #3487 Provide precision and scale for currency database datatype and H2.
  liquibase-standard/src/main/java/liquibase/datatype/core/CurrencyType.java
  liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
  liquibase-standard/src/test/java/liquibase/datatype/CurrencyTypeTest.java
Labels: TypeBug, DBH2, SafeToBuild

#4092 SnowflakeDatabase allows catalog name in identifiers
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddUniqueConstraintExecutorTest.java
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
Labels: TypeBug, DBSnowflake, SafeToBuild

#4021 Fix search path handle for PostgreSQL with JDBC connection with specified schema
  liquibase-standard/src/main/java/liquibase/database/core/DatabaseUtils.java
Labels: TypeBug, DBPostgres, SafeToBuild, sprint2023-49

#4101 Change the case of sys.extended_properties.
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SetViewRemarksGenerator.java
  liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/setColumnRemarks/mssql.sql
  liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/setTableRemarks/mssql.sql
Labels: TypeBug, DBMSSQLServer, SafeToBuild, sprint2023-49

#4013 Fixed #3722 auto-increment column starting with a custom value no longer works with H2 v1
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/database/core/H2Database.java
Labels: TypeBug, SafeToBuild, sprint2023-48

#4203 Fix addDefaultValue checksum calculation when providing schema name
  liquibase-standard/src/main/java/liquibase/change/core/AddDefaultValueChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/AddDefaultValueChangeTest.groovy
Labels: sprint-50

#4193 DAT-14642 - Prevents Liquibase from incorrectly attempting to redeploy changesets during checksum upgrade
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/ShouldRunChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/command/core/ReleaseLocksCommandStep.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGeneratorTest.java
Labels: sprint-50

#4185 Adding support for Postgresql generated columns.
  liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: sprint-50

#3914 DAT-13285 - Fix CheckSum generation issues + improvement
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCountSql.test.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/change/CheckSum.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-standard/src/main/java/liquibase/change/core/SQLFileChange.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/PropertyExpandingStream.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/DbmsChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/ShouldRunChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/command/core/ReleaseLocksCommandStep.java
  liquibase-standard/src/main/java/liquibase/sql/visitor/AbstractSqlVisitor.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGenerator.java
  liquibase-standard/src/test/groovy/liquibase/change/AbstractChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/change/core/CreateViewChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/change/core/SQLFileChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/changelog/filter/ShouldRunChangeSetFilterTest.groovy
  liquibase-standard/src/test/groovy/liquibase/hub/model/HubChangeTest.groovy
  liquibase-standard/src/test/java/liquibase/change/AbstractSQLChangeTest.java
  liquibase-standard/src/test/java/liquibase/change/CheckSumTest.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/UpdateChangeSetChecksumGeneratorTest.java
Labels: sprint2023-46, sprint2023-48

#4171 [DAT-6608] Refactors DropAll command as CommandStep
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dropAll.test.groovy
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommand.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/InternalDropAllCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-standard/src/main/resources/META-INF/services/liquibase.command.LiquibaseCommand
Labels: sprint2023-49

#4178 SQL Anywhere was never owned by Siebel, but only by SAP, Sybase, Powersoft, Watcom.
  liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java
Labels: SafeToBuild, sprint2023-49

#3836 Remove not using imported classes and packages in the source file.
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/util/DownloadUtil.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/DropProcedureGeneratorSnowflake.java
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/RanChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/ChangeExecListenerUtils.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnAutoIncrementService.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/util/TableOutput.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#3720 Replace if statements with switch statements.
  liquibase-standard/src/main/java/liquibase/configuration/ConfigurationValueConverter.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#3666 Delete unused comment code.
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/DerbyTestSystem.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/HsqlTestSystem.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SybaseDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/UnsupportedDatabase.java
  liquibase-standard/src/main/java/liquibase/diff/DiffResult.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/ChangeGeneratorChain.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingColumnChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/UnexpectedColumnChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/UnexpectedIndexChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/diff/output/report/DiffToReport.java
  liquibase-standard/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-standard/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
  liquibase-standard/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java
  liquibase-standard/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorPostgres.java
  liquibase-standard/src/main/java/liquibase/statement/core/InsertSetStatement.java
  liquibase-standard/src/main/java/liquibase/structure/core/Index.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#4137 GitHub action concurrency
  .github/workflows/build.yml
Labels: sprint2023-49

#4248 Fix installer README message
  liquibase-dist/src/main/archive/README.txt
Labels: sprint-50

#4157 Fix "Running Changeset: " logs written directly to stdout instead of using the maven logger
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUi.java
Labels: TypeBug, SafeToBuild, sprint2023-51

#3841 Improve Javadoc.
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataColumnConfig.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomTaskChange.java
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/PreparedStatementFactory.java
  liquibase-standard/src/main/java/liquibase/database/core/DB2Database.java
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SQLiteDatabase.java
  liquibase-standard/src/main/java/liquibase/executor/AbstractExecutor.java
  liquibase-standard/src/main/java/liquibase/executor/ExecutorService.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/PreparedStatementCallback.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/RowCallbackHandler.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/SqlTypeValue.java
  liquibase-standard/src/main/java/liquibase/hub/core/StandardHubService.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/parser/core/ParsedNode.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-standard/src/main/java/liquibase/snapshot/CachedRow.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGenerator.java
  liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatement.java
  liquibase-standard/src/main/java/liquibase/structure/AbstractDatabaseObject.java
  liquibase-standard/src/main/java/liquibase/structure/core/Column.java
  liquibase-standard/src/main/java/liquibase/util/OsgiUtil.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#3741 Remove fields that are not used or unreachable from the entry points.
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-standard/src/main/java/liquibase/precondition/core/SequenceExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/SqlPrecondition.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogLockGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ISODateFormat.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#3768 Fix javadoc references, links and spaces.
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDIBootstrap.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibaseConfig.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesCDIConfigBuilder.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesTreeBuilder.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/Liquibase.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/LiquibaseSchema.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/LiquibaseType.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/exceptions/CyclicDependencyException.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/exceptions/DependencyNotFoundException.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/CDITestProducer.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/SchemesCDIConfigBuilderTest.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/SchemesTreeBuilderTest.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
  liquibase-standard/src/main/java/liquibase/ExtensibleObject.java
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/change/Change.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChange.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/ChangeSetFilterResult.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/AbstractChangeExecListener.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/LoggingChangeExecListener.java
  liquibase-standard/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/database/core/FirebirdDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-standard/src/main/java/liquibase/diff/output/StandardObjectChangeFilter.java
  liquibase-standard/src/main/java/liquibase/exception/SetupException.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/RowMapperNotNullConstraintsResultSetExtractor.java
  liquibase-standard/src/main/java/liquibase/hub/HubServiceFactory.java
  liquibase-standard/src/main/java/liquibase/integration/IntegrationDetails.java
  liquibase-standard/src/main/java/liquibase/integration/servlet/GenericServletWrapper.java
  liquibase-standard/src/main/java/liquibase/logging/LogService.java
  liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
  liquibase-standard/src/main/java/liquibase/servicelocator/ServiceLocator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ExpressionMatcher.java
  liquibase-standard/src/main/java/liquibase/util/FilenameUtil.java
  liquibase-standard/src/main/java/liquibase/util/NetUtil.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#3990 Implement "author" command argument for diffChangelog command
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
  liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeEnhancement, RiskLow, SafeToBuild, sprint2023-48

#3721 Code cleanup: avoid re-calling methods
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-standard/src/main/java/liquibase/datatype/core/BlobType.java
  liquibase-standard/src/main/java/liquibase/integration/ant/AntResourceAccessor.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#3837 Replace with Collections.singletonList(), Collections.emptyList(), or…
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystem.java
  liquibase-standard/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-standard/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddLookupTableChange.java
  liquibase-standard/src/main/java/liquibase/change/core/MergeColumnChange.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/StatusVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/SnapshotCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UnexpectedChangesetsCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/core/MariaDBDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SQLiteDatabase.java
  liquibase-standard/src/main/java/liquibase/dbdoc/TableWriter.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangedColumnChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotControl.java
  liquibase-standard/src/main/java/liquibase/statement/core/CreateTableStatement.java
Labels: SafeToBuild, TypeTechDebt, sprint2023-48

#4099 add support for the TRAN keyword (T-SQL)
  liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/transaction.test.sql
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeBug, DBMSSQLServer, SafeToBuild, sprint-50

#4119 Switch to distribute jars generated by Java 11 allowing Jakarta cdi 4 upgrade
  .github/workflows/build.yml
  liquibase-cdi-jakarta/pom.xml
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/CDIBootstrap.java
Labels: sprint2023-49

#3680 Add serialVersionUID to classes that implement Serializable.
  liquibase-standard/src/main/java/liquibase/command/CommandFailedException.java
  liquibase-standard/src/main/java/liquibase/exception/CommandValidationException.java
  liquibase-standard/src/main/java/liquibase/exception/MissingRequiredArgumentException.java
  liquibase-standard/src/main/java/liquibase/exception/UnknownChangeLogParameterException.java
  liquibase-standard/src/main/java/liquibase/exception/UnknownConfigurationType.java
  liquibase-standard/src/main/java/liquibase/hub/HubServiceFactory.java
  liquibase-standard/src/main/java/liquibase/hub/core/HttpClient.java
  liquibase-standard/src/main/java/liquibase/hub/core/StandardHubService.java
  liquibase-standard/src/main/java/liquibase/integration/servlet/LiquibaseJakartaStatusServlet.java
  liquibase-standard/src/main/java/liquibase/integration/servlet/LiquibaseStatusServlet.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/XSDLookUpException.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-44

#4110 Add support for Unicode roman numerals.
  liquibase-standard/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
Labels: TypeEnhancement, SafeToBuild, sprint2023-50
