Repository liquibase/liquibase, pull requests merged in 2023-01, with the labels that each got.

#3528 Use 'Integer.compare' instead
  liquibase-core/src/main/java/liquibase/changelog/ChangeLogHistoryServiceFactory.java
  liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java
  liquibase-core/src/main/java/liquibase/diff/compare/DatabaseObjectComparatorComparator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/ChangeGeneratorComparator.java
  liquibase-core/src/main/java/liquibase/lockservice/LockServiceFactory.java
  liquibase-core/src/main/java/liquibase/parser/NamespaceDetailsFactory.java
  liquibase-core/src/main/java/liquibase/parser/SnapshotParserFactory.java
  liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorComparator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/SqlGeneratorComparator.java
  liquibase-core/src/test/java/liquibase/verify/change/VerifyChangeClassesTest.java
Labels: SafeToBuild, TypeRefactor, sprint2022-41

#3527 Simplify 'Map' operations.
  liquibase-core/src/main/java/liquibase/serializer/ChangeLogSerializerFactory.java
  liquibase-core/src/main/java/liquibase/serializer/SnapshotSerializerFactory.java
  liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/structure/DatabaseObjectCollection.java
  liquibase-core/src/main/java/liquibase/structure/core/Catalog.java
  liquibase-core/src/main/java/liquibase/structure/core/Schema.java
  liquibase-core/src/main/java/liquibase/util/ObjectUtil.java
Labels: SafeToBuild, autocandidate, sprint2022-41

#3533 Prevent Executors collision due to hash used as a Map's key part
  liquibase-core/src/main/java/liquibase/executor/ExecutorService.java
Labels: SafeToBuild, sprint2022-40

#3576 Breaks out of LockService.init loop after validations are completed
  liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: sprint2022-40

#3571 Remove unnecessary semicolon.
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesCDIConfigBuilder.java
  liquibase-core/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-core/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingDataExternalFileChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/UnexpectedTableChangeGenerator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/UnexpectedViewChangeGenerator.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/io/EmptyLineAndCommentSkippingInputStream.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddPrimaryKeyGenerator.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/core/AddUniqueConstraintGenerator.java
  liquibase-core/src/main/java/liquibase/util/FileUtil.java
  liquibase-core/src/main/java/liquibase/util/MD5Util.java
  liquibase-core/src/main/java/liquibase/util/xml/DefaultXmlWriter.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChangeLogSyncToTagSQLMojo.java
Labels: TypeEnhancement, SafeToBuild, sprint2022-41

#3558 Missing Override annotations.
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesCDIConfigBuilder.java
  liquibase-core/src/main/java/liquibase/AbstractExtensibleObject.java
  liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-core/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-core/src/main/java/liquibase/changelog/filter/IgnoreChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DiffToChangeLogCommand.java
  liquibase-core/src/main/java/liquibase/database/core/AbstractDb2Database.java
  liquibase-core/src/main/java/liquibase/executor/AbstractExecutor.java
  liquibase-core/src/main/java/liquibase/hub/core/MockHubService.java
  liquibase-core/src/main/java/liquibase/hub/model/Connection.java
  liquibase-core/src/main/java/liquibase/resource/DirectoryPathHandler.java
  liquibase-core/src/main/java/liquibase/resource/ZipPathHandler.java
  liquibase-core/src/main/java/liquibase/sdk/resource/MockResource.java
  liquibase-core/src/main/java/liquibase/serializer/AbstractLiquibaseSerializable.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlChangeLogSerializer.java
  liquibase-core/src/main/java/liquibase/serializer/core/yaml/YamlSnapshotSerializer.java
  liquibase-core/src/main/java/liquibase/sql/visitor/AbstractSqlVisitor.java
  liquibase-core/src/main/java/liquibase/structure/core/Relation.java
  liquibase-core/src/main/java/liquibase/structure/core/Table.java
  liquibase-core/src/main/java/liquibase/util/csv/CSVWriter.java
Labels: SafeToBuild, autocandidate, sprint2022-41

#3547 Prevents redundant loop iterations. Early loop exit in 'if' condition.
  liquibase-core/src/main/java/liquibase/change/core/DropColumnChange.java
  liquibase-core/src/main/java/liquibase/integration/servlet/GenericServletListener.java
Labels: SafeToBuild, sprint2022-41

#3570 DAT 6635 - Implement TagCommand
  liquibase-core/src/main/java/liquibase/Beta.java
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/CleanUpCommandStep.java
  liquibase-core/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-core/src/main/java/liquibase/command/CommandBuilder.java
  liquibase-core/src/main/java/liquibase/command/CommandFactory.java
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
  liquibase-core/src/main/java/liquibase/command/core/DbUrlConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/TagCommandStep.java
  liquibase-core/src/main/java/liquibase/database/Database.java
  liquibase-core/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-core/src/test/java/liquibase/command/core/MockCommandStep.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/tag.test.groovy
Labels: PRAssociated, sprint2022-40

#3440 Upgrades installer JDK version for next release.
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: SafeToBuild, sprint2022-37

#3637 Postgresql - Fallback to default schema name in SequenceSnapshotGenerator when this is null
  liquibase-core/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-core/src/test/groovy/liquibase/snapshot/jvm/SequenceSnapshotGeneratorTest.groovy
Labels: DBPostgres, SafeToBuild, autocandidate, sprint2022-41

#1834 Add support for multiple schemas to dbDoc command
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java
  liquibase-core/src/main/java/liquibase/command/core/DbDocCommandStep.java
  liquibase-core/src/main/java/liquibase/dbdoc/HTMLListWriter.java
  liquibase-core/src/main/java/liquibase/dbdoc/HTMLWriter.java
  liquibase-core/src/main/java/liquibase/dbdoc/TableWriter.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/resources/liquibase/dbdoc/stylesheet.css
  liquibase-core/src/test/java/liquibase/changelog/visitor/DBDocVisitorTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dbDoc.test.groovy
Labels: TypeEnhancement, RiskMedium, Severity4, ImpactLow, DBAll, IntegrationAny, SafeToBuild, criticalityBuilder, complexityGlobal, sprint2022-41

#3553 No need redundant conditions.
  liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-core/src/main/java/liquibase/change/core/StopChange.java
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-core/src/main/java/liquibase/diff/ObjectDifferences.java
  liquibase-core/src/main/java/liquibase/diff/compare/core/DefaultDatabaseObjectComparator.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/AbstractChangeGenerator.java
  liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGeneratorH2.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/TableSnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/statement/core/CommentStatement.java
  liquibase-core/src/main/java/liquibase/structure/AbstractDatabaseObject.java
  liquibase-core/src/main/java/liquibase/util/JdbcUtil.java
Labels: SafeToBuild, autocandidate, sprint2022-41

#3591 Replace expressions with type arguments with diamond type <>.
  liquibase-core/src/main/java/liquibase/ContextExpression.java
  liquibase-core/src/main/java/liquibase/Contexts.java
  liquibase-core/src/main/java/liquibase/Scope.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java
  liquibase-core/src/main/java/liquibase/configuration/ConfigurationDefinition.java
  liquibase-core/src/main/java/liquibase/database/DatabaseList.java
  liquibase-core/src/main/java/liquibase/database/OfflineConnection.java
  liquibase-core/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-core/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-core/src/main/java/liquibase/diff/compare/CompareControl.java
  liquibase-core/src/main/java/liquibase/diff/compare/DatabaseObjectComparatorFactory.java
  liquibase-core/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-core/src/main/java/liquibase/executor/AbstractExecutor.java
  liquibase-core/src/main/java/liquibase/executor/LoggingExecutor.java
  liquibase-core/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-core/src/main/java/liquibase/executor/jvm/RowMapperNotNullConstraintsResultSetExtractor.java
  liquibase-core/src/main/java/liquibase/sdk/resource/MockResourceAccessor.java
  liquibase-core/src/main/java/liquibase/snapshot/DatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-core/src/main/java/liquibase/statement/core/CreateTableStatement.java
  liquibase-core/src/main/java/liquibase/structure/core/ForeignKey.java
  liquibase-core/src/main/java/liquibase/structure/core/Table.java
  liquibase-core/src/main/java/liquibase/util/CollectionUtil.java
  liquibase-core/src/main/java/liquibase/util/SmartMap.java
  liquibase-core/src/main/java/liquibase/util/StringClauses.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRegisterChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneChangeSetSQL.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseRollbackOneUpdateSQL.java
Labels: SafeToBuild, autocandidate, sprint2023-42

#3586 Fix typos.
  liquibase-core/src/main/java/liquibase/CatalogAndSchema.java
  liquibase-core/src/main/java/liquibase/ExtensibleObject.java
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/change/Change.java
  liquibase-core/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-core/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-core/src/main/java/liquibase/change/DbmsTargetedChange.java
  liquibase-core/src/main/java/liquibase/change/core/AddUniqueConstraintChange.java
  liquibase-core/src/main/java/liquibase/change/core/CreateSequenceChange.java
  liquibase-core/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-core/src/main/java/liquibase/changelog/filter/ChangeSetFilterResult.java
  liquibase-core/src/main/java/liquibase/command/core/UpdateToTagSqlCommandStep.java
  liquibase-core/src/main/java/liquibase/database/core/SybaseASADatabase.java
  liquibase-core/src/main/java/liquibase/diff/compare/CompareControl.java
  liquibase-core/src/main/java/liquibase/executor/jvm/SqlParameter.java
  liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/main/java/liquibase/precondition/core/OrPrecondition.java
  liquibase-core/src/main/java/liquibase/snapshot/SnapshotGenerator.java
  liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
  liquibase-core/src/main/java/liquibase/sqlgenerator/SqlGenerator.java
  liquibase-core/src/main/java/liquibase/statement/SqlStatement.java
  liquibase-core/src/main/java/liquibase/structure/AbstractDatabaseObject.java
  liquibase-extension-examples/src/main/java/liquibase/executor/jvm/ExampleExecutor.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/TestSystemFactory.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTagSql.test.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-42

#3548 Remove duplicate conditions in expressions and branches of if statements. They are used due to oversight.
  liquibase-core/src/main/java/liquibase/diff/ObjectDifferences.java
  liquibase-core/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-42

#3568 Replace constant charset String literal with the predefined StandardC…
  liquibase-core/src/main/java/liquibase/util/BomAwareInputStream.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-42

#3550 Delegate change set equality tests
  liquibase-core/src/main/java/liquibase/changelog/filter/AfterTagChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/changelog/filter/ExecutedAfterChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/changelog/filter/NotRanChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/changelog/filter/RanChangeSetFilter.java
  liquibase-core/src/main/java/liquibase/changelog/filter/ShouldRunChangeSetFilter.java
Labels: TypeEnhancement, SafeToBuild, sprint2022-41

#3667 DAT-6636: Refactor of TagExistsCommandStep and extraction of code to new LockServiceCommandStep
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/AbstractCommandStep.java
  liquibase-core/src/main/java/liquibase/command/CommandBuilder.java
  liquibase-core/src/main/java/liquibase/command/CommandDefinition.java
  liquibase-core/src/main/java/liquibase/command/CommandFactory.java
  liquibase-core/src/main/java/liquibase/command/CommandScope.java
  liquibase-core/src/main/java/liquibase/command/CommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/DbUrlConnectionCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/LockServiceCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/SnapshotCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/TagCommandStep.java
  liquibase-core/src/main/java/liquibase/command/core/TagExistsCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-core/src/main/java/liquibase/sdk/convert/ConvertCommandStep.java
  liquibase-core/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-core/src/test/groovy/liquibase/command/CommandFactoryTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/tagExists.test.groovy
Labels: PRAssociated, sprint2023-42

#3696 Refactors CalculateChecksumCommandStep
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/calculateChecksum.test.groovy
Labels: sprint2023-42

#2190 CORE-3044 avoid locking if no updates pending
  liquibase-core/src/main/java/liquibase/Liquibase.java
  liquibase-core/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
  liquibase-core/src/test/groovy/liquibase/LiquibaseTest.groovy
  liquibase-core/src/test/resources/liquibase/test-changelog-fast-check.xml
Labels: TypeEnhancement, RiskHigh, Severity3, ImpactMedium, DBAll, IntegrationAny, BBroad, SyncTicket, SafeToBuild, sprint2022-41

#3081 Warning in case of missing liquibase files instead of throwing an exception
  liquibase-core/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java
  liquibase-core/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement, SafeToBuild, sprint2022-41, sprint2023-42

#2463 Document new TestSystem functionality
  DEVELOPING.md
Labels: TypeDoc, autocandidate, sprint2022-41

#3597 Update maven-bundle-plugin instructions to export package containing XSD files
  liquibase-core/pom.xml
Labels: SafeToBuild, integerationOSGi, sprint2022-41

#3590 Remove redundant conditions tha covered by a subsequent condition.
  liquibase-core/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
  liquibase-core/src/main/java/liquibase/util/StringClauses.java
Labels: TypeEnhancement, SafeToBuild, sprint2023-42

#3572 fix: snowflake has wrong priority
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGeneratorSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGeneratorSnowflake.java
Labels: DBSnowflake, SafeToBuild, sprint2023-43

#3704 Do not add default schema name to getSchemas method to avoid one sche…
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGeneratorSnowflake.java
Labels: DBSnowflake, SafeToBuild, sprint2023-43

#3703 #3035 add Double data type class to avoid incorrect double(0) databas…
  liquibase-snowflake/src/main/java/liquibase/datatype/core/DoubleDataTypeSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
Labels: DBSnowflake, SafeToBuild, sprint2023-43

#3710 do not support setting column comments on a view in Snowflake (DAT-12530)
  liquibase-core/src/main/java/liquibase/change/AbstractChange.java
  liquibase-core/src/main/java/liquibase/database/Database.java
  liquibase-core/src/main/java/liquibase/exception/DatabaseIncapableOfOperation.java
  liquibase-core/src/main/java/liquibase/exception/StatementNotSupportedOnDatabaseException.java
  liquibase-core/src/main/java/liquibase/exception/ValidationErrors.java
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
  liquibase-snowflake/src/main/java/liquibase/executor/jvm/SnowflakeJdbcExecutor.java
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/SetColumnRemarksGeneratorSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.executor.Executor
Labels: DBSnowflake

#3607 Migrate setup-java action to use Temurin
  .github/workflows/snyk.yml
Labels: SafeToBuild, sprint2023-43

#3699 Fix NullPointerException for case sensitive collations
  liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/MSSQLTestSystem.java
Labels: TypeBug, SafeToBuild, sprint2023-43
