Repository liquibase/liquibase, pull requests merged in 2024-10, with the labels that each got.

#6375 Initialize member variable in method to fix tests
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
Labels: TypeBug

#6380 test: change order of stream closing and file deletion
  liquibase-standard/src/test/groovy/liquibase/changelog/ChangeSetTest.groovy
Labels: skipReleaseNotes

#6330 DAT-18563 :: Unhide tag parameter for UpdateTestingRollback command
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpdateTestingRollbackCommandsIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateTestingRollback.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
Labels: TypeBug, DocNeeded, runFunctional&HarnessTests

#6205 Removed usage of deprecated isEmpty() method
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/VersionUtils.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDatabaseDiff.java
  liquibase-standard/src/main/java/liquibase/change/CheckSum.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/OfflineConnection.java
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-standard/src/main/java/liquibase/datatype/core/ClobType.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGeneratorDefaultClauseBeforeNotNull.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGeneratorInformix.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6287 #6281 fix NPE when default value is null
  liquibase-standard/src/main/java/liquibase/snapshot/CachedRow.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, runFunctional&HarnessTests

#6288 #6264 avoid ignoring the caught exception
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/LiquibaseSdkConfigurationValueProvider.java
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/changelog/ExpressionExpander.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/AbstractDb2Database.java
  liquibase-standard/src/main/java/liquibase/database/core/H2Database.java
  liquibase-standard/src/main/java/liquibase/datatype/core/UUIDType.java
  liquibase-standard/src/main/java/liquibase/exception/DatabaseIncapableOfOperation.java
  liquibase-standard/src/main/java/liquibase/exception/DateParseException.java
  liquibase-standard/src/main/java/liquibase/exception/PreconditionFailedException.java
  liquibase-standard/src/main/java/liquibase/exception/UnknownConfigurationType.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/StatementCreatorUtils.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/ChangeExecListenerUtils.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/precondition/CustomPreconditionWrapper.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorMySQL.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGenerator.java
  liquibase-standard/src/main/java/liquibase/util/JdbcUtil.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/test/java/liquibase/database/core/OfflineDatabaseTest.java
  liquibase-standard/src/test/java/liquibase/executor/jvm/AlternateConnectionExecutor.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorInformixTest.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorMSSQLTest.java
Labels: TypeEnhancement, ThemeUsability

#6332 Adressing issue #6331, small changes to pom.xml files to reduce warnings shown in building
  liquibase-cli/pom.xml
  liquibase-core/pom.xml
  pom.xml
Labels: TypeEnhancement, sdou

#6382 DAT-18743: dry-run: add current_branch_name
  .github/workflows/dry-run-release.yml
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6305 Handle Oracle blank schema names DAT-18199
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/CatalogSnapshotGenerator.java
Labels: TypeBug

#6109 DAT-18191 and DAT-18192 - Fix classpath loading and incorrect configuration for addForeignKeyConstraint
  liquibase-standard/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: TypeBug

#6359 Handle blank change set ID DAT-18687
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug

#6386 specify liquibase integration when running through ant (DAT-18608)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
  liquibase-standard/src/test/groovy/liquibase/analytics/TestAnalyticsWebserver.groovy
  liquibase-standard/src/test/groovy/liquibase/integration/ant/test/AnalyticsWebserverPostBodyIsAnt.groovy
  liquibase-standard/src/test/groovy/liquibase/integration/ant/test/AntTestAnalyticsWebserver.groovy
  liquibase-standard/src/test/resources/liquibase/integration/ant/DropAllTaskTest.xml
  liquibase-standard/src/test/resources/liquibase/integration/ant/test/antlib.xml
Labels: skipReleaseNotes

#6350 allow replaceIfExists in Postgres procedures (DAT-18495)
  liquibase-integration-tests/src/test/groovy/liquibase/command/update/CreateProcedurePostgresTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/update/createProcedureReplaceIfExists.xml
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateProcedureGenerator.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: TypeBug, runFunctional&HarnessTests

#6389 fix CreateProcedureChange not working with mariadb (DAT-18495)
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: skipReleaseNotes, runFunctional&HarnessTests

#6138 Add support for include columns in indexes
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/mssql/MssqlIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/feature.index.include.xml
  liquibase-integration-tests/src/test/resources/changelogs/mssql/rollback/rollbackable.changelog.xml
  liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/ColumnComparator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingIndexChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java
  liquibase-standard/src/main/java/liquibase/structure/core/Column.java
  liquibase-standard/src/main/java/liquibase/structure/core/Index.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/change/ColumnConfigTest.groovy
Labels: TypeEnhancement, DocNeeded, DBMSSQLServer

#5894 do not strip "classpath:" when normalizing the path
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/test/java/liquibase/resource/UrlDrivenResourceAccessor.java
  liquibase-standard/src/test/java/liquibase/resource/UrlDrivenResourceAccessorTest.java
  liquibase-standard/src/test/resources/liquibase/resource/changelog1.yml
  liquibase-standard/src/test/resources/liquibase/resource/changelog2.yml
  liquibase-standard/src/test/resources/liquibase/resource/subresources/child-changelog.yml
  liquibase-standard/src/test/resources/liquibase/resource/subresources/child-changelog1.yml
  liquibase-standard/src/test/resources/liquibase/resource/subresources/child-changelog2.yml
Labels: TypeBug, DocNeeded

#6374 add integrationName hidden parameter (DAT-18607)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: skipReleaseNotes

#6391 Handle Snowflake add NOT NULL constraint DAT-18798
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
Labels: TypeBug

#6392 add isCi and isGithubActions event properties (DAT-18609)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
Labels: skipReleaseNotes

#6366 improve startup performance (DAT-18327)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeEnhancement

#6385 Do not check for nested database objects when using foreignKeyConstraintExists precondition (DAT-18624)
  liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/snapshot/DatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotControl.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeBug, runFunctional&HarnessTests

#6417 Revert "Remove unneeded inclusion of commons-io in liquibase-core pom.xml"
  liquibase-core/pom.xml
Labels: TypeBug

#6419 change production analytics config endpoint URL (DAT-18846)
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
Labels: skipReleaseNotes

#6427 fix: join test classes
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgresThreadingTest.java
Labels: skipReleaseNotes

#6426 fix: restore public method in PreconditionFailedException
  liquibase-standard/src/main/java/liquibase/exception/PreconditionFailedException.java
Labels: skipReleaseNotes

#6411 update licenses (DAT-18710)
  liquibase-dist/expected-distribution-contents-targz.txt
  liquibase-dist/expected-distribution-contents-zip.txt
  liquibase-dist/src/main/archive/licenses/commercial/Liquibase Pro EULA Software License Subscription and Support Agreement.txt
  liquibase-dist/src/main/archive/licenses/oss/README.txt
  liquibase-dist/src/main/archive/licenses/oss/usage-data.txt
Labels: skipReleaseNotes

#6409 Added more logging DAT-18114
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6416 When determining the schema name make sure a value was found (DAT-18673)
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
Labels: TypeBug, runFunctional&HarnessTests

#6407 Add filterable flag to ChangeLogParameter class (DAT-18811)
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/test/groovy/liquibase/changelog/ChangeLogParametersTest.groovy
Labels: TypeBug, runFunctional&HarnessTests

#6429 check that getPriority method is correct for snapshot generators (DAT-18730)
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeEnhancement

#6406 Test assertion code modification DAT-17568
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-standard/src/main/java/liquibase/configuration/LiquibaseConfiguration.java
  liquibase-standard/src/main/java/liquibase/util/ExceptionUtil.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6438 add basic Oracle performance test (DAT-18578)
  liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
Labels: skipReleaseNotes

#6413 DAT-18689: register all failed changesets in the exceptionChangesets
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6402 Add pg_stat_statements and pg_stat_statements_info views to the list of system tables and views to prevent them from being dropped
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-standard/src/test/java/liquibase/database/core/PostgresDatabaseTest.java
Labels: TypeBug

#6435 include a prefix on truly random userIds (DAT-18848)
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsTrackEvent.java
  liquibase-standard/src/main/java/liquibase/analytics/AnonymousSeed.java
Labels: skipReleaseNotes

#6434 add logging when threads time out during analytics processing, make timeout configurable (DAT-18865)
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java
Labels: skipReleaseNotes

#6339 Fixes include/excludeObjects filters for the 'generate-changelog' command specifically for the maven plugin
  liquibase-standard/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
Labels: TypeBug

#6345 refactor: use info log instead of warn when default schema is used
  liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java
Labels: TypeEnhancement

#6446 Allow for scopemanager to be shared between threads created by liquibase (DAT-18871)
  liquibase-standard/src/main/java/liquibase/Scope.java
Labels: TypeBug, runFunctional&HarnessTests

#6414 feat(log): print failed changesets to the default UI
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCountCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
Labels: TypeEnhancement

#6266 fix CustomTaskRollback twice call rollback bug
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-standard/src/test/java/liquibase/change/custom/ExampleCustomTaskChange.java
Labels: TypeBug

#6458 chore: fix expected files in examples directory
  liquibase-dist/expected-distribution-contents-targz.txt
  liquibase-dist/expected-distribution-contents-zip.txt
Labels: skipReleaseNotes

#6432 Adds customizer to discover and react to unknown change sets
  liquibase-standard/src/main/java/liquibase/integration/UnexpectedChangeSetsValidator.java
  liquibase-standard/src/test/groovy/liquibase/integration/UnexpectedChangeSetsValidatorTest.java
Labels: TypeEnhancement

#6463 Fix flakey test (DAT-18921)
  liquibase-standard/src/test/java/liquibase/database/ConnectionServiceFactoryTest.java
Labels: TypeBug

#6410 Modify clob handling
  liquibase-integration-tests/src/test/resources/changelogs/common/names.csv
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.for.clob.types.csv
  liquibase-standard/src/test/resources/liquibase/test-changelog-clob-types.xml
Labels: TypeBug, DocNeeded

#6465 enable analytics for release builds only (DAT-18902)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
  liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
  liquibase-standard/src/main/java/liquibase/util/LiquibaseUtil.java
  liquibase-standard/src/test/groovy/liquibase/analytics/AnalyticsArgsTest.groovy
  liquibase-standard/src/test/groovy/liquibase/integration/ant/test/AnalyticsWebserverPostBodyIsAnt.groovy
  liquibase-standard/src/test/groovy/liquibase/integration/ant/test/AntTestAnalyticsWebserver.groovy
  liquibase-standard/src/test/resources/liquibase/integration/ant/DropAllTaskTest.xml
Labels: skipReleaseNotes

#6471 Add 4.30.0 xsd and update changelog.txt
  changelog.txt
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.30.xsd
Labels: skipReleaseNotes, AI Generated Code

#6474 Only add child events when analytics is enabled (DAT-18943)
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
Labels: TypeBug
