Repository liquibase/liquibase, pull requests merged in 2024-05, with the labels that each got.

#5833 Use Java 8 features
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/SchemesCDIConfigBuilder.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/MavenUtils.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/StatusChangeLogIterator.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/DBDocVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/DB2Database.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/StatementCreatorUtils.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
Labels: TypeEnhancement

#5853 use Apache Commons where possible, instead of homegrown solutions (DAT-17303)
  liquibase-standard/src/main/java/liquibase/util/BooleanUtil.java
  liquibase-standard/src/main/java/liquibase/util/CollectionUtil.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: skipReleaseNotes

#5848 do not allow arguments with default values to be required (DAT-17436)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dropAll.test.groovy
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/command/CommandArgumentDefinitionTest.groovy
Labels: TypeEnhancement

#5842 optimize DBCL checksum query and set fetch size on all statements (DAT-17267)
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/main/java/liquibase/sql/SqlConfiguration.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/SelectFromDatabaseChangeLogGenerator.java
  liquibase-standard/src/main/java/liquibase/statement/core/SelectFromDatabaseChangeLogStatement.java
Labels: TypeBug

#5867 cleanup weekly-integration-tests.yml (DAT-17400)
  .github/workflows/weekly-integration-tests.yml
Labels: skipReleaseNotes

#4240 PD-3241: failOnError syntax
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseUpdateMojo.java
Labels: skipReleaseNotes

#5870 only run drop all if database was used in the test
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
Labels: TypeTest

#5881 Update codeql.yml
  .github/workflows/codeql.yml
Labels: skipReleaseNotes

#5883 Issue 5654 includeall min max depth fixes
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/a.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/b.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/c.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/d.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/e/e.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/e/f/f.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/a/b/c/d/e/f/g/g.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/depthboundincludeall/changelog.xml
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/resource/AbstractPathResourceAccessor.java
  liquibase-standard/src/main/java/liquibase/resource/ResourceAccessor.java
  liquibase-standard/src/main/java/liquibase/sdk/resource/MockResourceAccessor.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeBug

#5781 Fix (MSSQL): default end delimiter applied when there is an endDelimiter applied for a given chanset
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/MssqlMergeIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/create.procedure.changelog.sql
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
Labels: TypeBug

#5891 DAT-17618: Update fossa_ai.yml to use authorize
  .github/workflows/fossa_ai.yml
Labels: skipReleaseNotes

#5869 Update diff summary results in mdc to not be recalculated (DAT-17096)
  liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java
Labels: TypeBug

#5887 Fix ordering of clause for Oracle global temporary tables SQL generation
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingTableChangeGenerator.java
Labels: TypeBug

#5888 normalize paths in DatabaseChangeLog using commons-io (DAT-17592)
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/src/main/archive/licenses/oss/README.txt
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  pom.xml
Labels: TypeBug

#5896 [DAT-17450] Add BigQuery unit tests
  liquibase-bigquery/src/test/java/liquibase/change/BigQueryMergeColumnChangeTest.java
  liquibase-bigquery/src/test/java/liquibase/database/BigQueryDatabaseUnitTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/BignumericDataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/BoolDataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/Float64DataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/GeographyDataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/Int64DataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/NumberDataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/datatype/core/StringDataTypeBigQueryTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddColumnGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddForeignKeyConstraintGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddPrimaryKeyConstraintGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryCreateDatabaseChangeLogLockTableGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryCreateTableGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDeleteGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDropForeignKeyConstraintGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDropPrimaryKeyConstraintGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryInsertOrUpdateGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryModifyDataTypeGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryRenameTableGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryRenameViewGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQuerySetNullableGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryUpdateGeneratorTest.java
Labels: TypeEnhancement

#5783 Fixed issue that unique constraint precondition does not honor schemaName attribute on MySQL
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-standard/src/main/java/liquibase/precondition/core/UniqueConstraintExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
Labels: TypeBug, DBMySQL

#5795 Fixes issue with incorrect schema in column exists precondition when checking using a snapshot
  liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
Labels: TypeBug

#5897 chore: invoke deprecated methods in default supports method for backwards compatibility
  liquibase-standard/src/main/java/liquibase/database/Database.java
Labels: TypeEnhancement

#5899 H2 tests may end up with an incorrect list of the standard DatabaseObject types, so we need to reset the factory
  liquibase-integration-tests/src/test/java/liquibase/dbtest/h2/H2IntegrationTest.java
Labels: TypeTest

#5908 BUGFIX Azure jar wrong suffix
  .github/workflows/create-release.yml
Labels: TypeBug

#5904 Release build branch
  .github/workflows/build.yml
Labels: skipReleaseNotes

#5916 chore:changelog + xsd
  changelog.txt
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.28.xsd
Labels: skipReleaseNotes

#5918 Fix/create release
  .github/workflows/create-release.yml
Labels: skipReleaseNotes, AI Generated Code

#5913 [DAT-17403] resolved priorities for Datatypes and ModifyDatatype generator
  liquibase-bigquery/src/main/java/liquibase/datatype/core/BignumericDataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/datatype/core/BoolDataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/datatype/core/Float64DataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/datatype/core/GeographyDataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/datatype/core/Int64DataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/datatype/core/NumericDataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/datatype/core/StringDataTypeBigQuery.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryModifyDataTypeGenerator.java
  liquibase-bigquery/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
  liquibase-bigquery/src/test/java/liquibase/datatype/core/NumericDataTypeBigQueryTest.java
Labels: TypeBug

#5923 Revert "Update diff summary results in mdc to not be recalculated (DAT-17096) (#5869)" (DAT-17690)
  liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java
Labels: TypeEnhancement

#5927 run command tests during build
  liquibase-integration-tests/pom.xml
Labels: skipReleaseNotes

#5905 [DAT-17502] added FK support
  liquibase-bigquery/src/main/java/liquibase/snapshot/jvm/BigQueryForeignKeySnapshotGenerator.java
  liquibase-bigquery/src/main/java/liquibase/snapshot/jvm/BigQueryUniqueConstraintSnapshotGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryAddForeignKeyConstraintGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryCreateTableGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryDropForeignKeyConstraintGenerator.java
  liquibase-bigquery/src/main/resources/META-INF/services/liquibase.snapshot.SnapshotGenerator
  liquibase-bigquery/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddForeignKeyConstraintGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDropForeignKeyConstraintGeneratorTest.java
Labels: TypeEnhancement

#5926 throw exception from diff-changelog when failure occurs (DAT-17623)
  liquibase-integration-tests/pom.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
Labels: TypeBug

#5937 DAT-17536: Update weekly-integration-tests.yml
  .github/workflows/weekly-integration-tests.yml
Labels: TypeEnhancement, skipReleaseNotes

#5919 fully qualify names for Snowflake unique constraints (DAT-16598)
  liquibase-integration-tests/src/test/groovy/liquibase/command/SnapshotSnowflakeIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGeneratorSnowflake.java
Labels: TypeBug

#5903 [DAT-16377] Verify if supports method is implemented in a change to prevent unexpected behaviors
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/SupportsMethodValidationLevelsEnum.java
  liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
  liquibase-standard/src/main/java/liquibase/util/LiquibaseUtil.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/xml/XMLChangeLogSAXParserTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/LiquibaseUtilTest.groovy
  liquibase-standard/src/test/java/liquibase/change/ChangeFactoryTest.java
  liquibase-standard/src/test/java/liquibase/wrong/BadlyImplementedChange.java
Labels: TypeEnhancement

#5941 Run-Test configuration updated to avoid buidling jakarta.enterprise jakarta.enterprise.cdi api with Java 11
  .github/workflows/run-tests.yml
Labels: sdou

#5939 Adding property to build so that liquibase-scripting shows up in the tarball
  .github/workflows/build.yml
Labels: TypeEnhancement

#5886 [DAT-17501] BigQuerry. Support Primary Key
  liquibase-bigquery/src/main/java/liquibase/snapshot/jvm/BigQueryPrimaryKeySnapshotGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryAddColumnGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryAddPrimaryKeyConstraintGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryCreateTableGenerator.java
  liquibase-bigquery/src/main/java/liquibase/sqlgenerator/BigQueryDropPrimaryKeyConstraintGenerator.java
  liquibase-bigquery/src/main/resources/META-INF/services/liquibase.snapshot.SnapshotGenerator
  liquibase-bigquery/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddColumnGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryAddPrimaryKeyConstraintGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryCreateTableGeneratorTest.java
  liquibase-bigquery/src/test/java/liquibase/sqlgenerator/BigQueryDropPrimaryKeyConstraintGeneratorTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AddColumnExecutorTest.java
Labels: TypeEnhancement

#5922 generated addPrimaryKey changes should not include column direction (DAT-17467)
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogMssqlIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/structure/core/PrimaryKey.java
Labels: TypeBug

#5945 Turn off DB2 integration tests until they can be fixed
  .github/workflows/run-tests.yml
Labels: TypeBug

#5946 Turn off DB2 for sonar
  .github/workflows/run-tests.yml
Labels: TypeBug

#5932 use Commons-IO where possible (DAT-17634)
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Banner.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-standard/src/main/java/liquibase/io/WriterOutputStream.java
  liquibase-standard/src/main/java/liquibase/util/BomAwareInputStream.java
  liquibase-standard/src/main/java/liquibase/util/FileUtil.java
  liquibase-standard/src/main/java/liquibase/util/StreamUtil.java
Labels: skipReleaseNotes

#5955 Add the reverted commit back : Update fossa_ai.yml
  .github/workflows/fossa_ai.yml
Labels: skipReleaseNotes

#5936 fail build if no tests are run (DAT-17643)
  .github/workflows/run-tests.yml
  liquibase-core/pom.xml
  liquibase-integration-tests/pom.xml
  pom.xml
Labels: skipReleaseNotes

#5915 Added connect command to Maven DAT-17411
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseConnectMojo.java
Labels: TypeEnhancement

#901 Microsoft SQL Server doesn't support ORDER in sequences
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
Labels: TypeEnhancement, RiskMedium, ImpactMedium, ThemeDBObjects, DBMSSQLServer, IntegrationAny

#5953 `CheckSum`: add getter for `storedCheckSum`
  liquibase-standard/src/main/java/liquibase/change/CheckSum.java
Labels: TypeEnhancement

#1826 Prevent silent failures when two "databaseChangeLog" tags are present
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
  liquibase-standard/src/test/resources/liquibase/parser/core/yaml/malformedDoubleChangeLog.yaml
Labels: TypeEnhancement, RiskMedium, Severity4, ImpactLow, DBAll, IntegrationAny, featureTags

#5898 Do not log stack trace if isExpected flag is true for CommandFailedException
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Labels: TypeBug

#5962 Partially reverted changes made for preventing having duplicate databasechelog tags
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/yaml/YamlChangeLogParser_RealFile_Test.groovy
Labels: TypeBug

#5967 DAT-17842
  liquibase-dist/src/main/archive/licenses/commercial/README.txt
Labels: skipReleaseNotes
