Repository liquibase/liquibase, pull requests merged in 2024-04, with the labels that each got.

#5729 remove ValueHandlerUtil and improve CLI argument parsing (DAT-15398)
  liquibase-integration-tests/src/test/groovy/liquibase/util/ValueHandlerUtilTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-standard/src/main/java/liquibase/command/core/DiffChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfigurationValueUtils.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/ValueHandlerUtil.java
  liquibase-standard/src/test/groovy/liquibase/util/ObjectUtilTest.groovy
Labels: breakingChanges

#5749 add junit-vintage engine to execute junit 4 tests (DAT-10403)
  liquibase-extension-testing/pom.xml
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/BaseLiquibaseExtensionTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-standard/pom.xml
  liquibase-standard/src/test/groovy/liquibase/change/AbstractChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/DependencyUtilTest.groovy
  pom.xml
Labels: skipReleaseNotes

#5750 make "connect" success message generation more generic by moving into Database interface (DAT-16602)
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
Labels: skipReleaseNotes

#5580 Support to generate a ChangeSetStatus with setting all its attributes when a changeset will be skipped
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandStepIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/update.changelog.yaml
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSetStatus.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/StatusVisitor.java
Labels: TypeBug

#5687 fix: addColumn changes are not respecting Datatypes definitions
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingColumnChangeGenerator.java
Labels: TypeBug

#5747 dynamically update copyright year in license.txt (DAT-17336)
  LICENSE.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: skipReleaseNotes

#5532 Record current Liquibase version on a RERUN changeset (#5529)
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
Labels: TypeEnhancement, behavior_change

#5658 User lombok Getter and Setter.
  liquibase-standard/src/main/java/liquibase/CatalogAndSchema.java
  liquibase-standard/src/main/java/liquibase/change/AddColumnConfig.java
  liquibase-standard/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-standard/src/main/java/liquibase/change/visitor/AddColumnChangeVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogInclude.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIncludeAll.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogProperty.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/integration/ant/AbstractChangeLogBasedTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/AbstractDatabaseDiffTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/ChangeLogSyncTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/ChangeLogSyncToTagTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/type/ChangeLogOutputFile.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Banner.java
  liquibase-standard/src/main/java/liquibase/logging/core/BufferedLogService.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/ChangesetsRolledback.java
  liquibase-standard/src/main/java/liquibase/osgi/Activator.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ChangeLogPropertyDefinedPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ChangeSetExecutedPrecondition.java
  liquibase-standard/src/main/java/liquibase/serializer/ChangeLogSerializerFactory.java
  liquibase-standard/src/main/java/liquibase/sql/CallableSql.java
  liquibase-standard/src/main/java/liquibase/sql/visitor/AppendSqlVisitor.java
  liquibase-standard/src/main/java/liquibase/statement/AutoIncrementConstraint.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddAutoIncrementStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddColumnStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddDefaultValueStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddForeignKeyConstraintStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddPrimaryKeyStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddUniqueConstraintStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AlterSequenceStatement.java
Labels: TypeEnhancement

#5619 Improve snapshot extensibility for NoSQL databases
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/AbstractExecuteTest.java
  liquibase-snowflake/src/test/java/liquibase/database/core/SnowflakeDatabaseTest.java
  liquibase-standard/src/main/java/liquibase/CatalogAndSchema.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/core/AbstractDb2Database.java
  liquibase-standard/src/main/java/liquibase/database/core/DerbyDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/FirebirdDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/HsqlDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/Ingres9Database.java
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MariaDBDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MockDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SQLiteDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SybaseDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/UnsupportedDatabase.java
  liquibase-standard/src/main/java/liquibase/diff/DiffResult.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/CatalogComparator.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/CommonCatalogSchemaComparator.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/SchemaComparator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingForeignKeyChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/diff/output/report/DiffToReport.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/CommandLineUtils.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java
  liquibase-standard/src/main/java/liquibase/snapshot/DatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/ResultSetCache.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotControl.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/CatalogSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/DataSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ForeignKeySnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/PrimaryKeySnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/TableSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ViewSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/DropSequenceGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameSequenceGenerator.java
  liquibase-standard/src/test/groovy/liquibase/snapshot/SnapshotGeneratorChainTest.groovy
  liquibase-standard/src/test/groovy/liquibase/snapshot/jvm/ViewSnapshotGeneratorTest.groovy
  liquibase-standard/src/test/java/liquibase/diff/output/changelog/DiffToChangeLogTest.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/AlterSequenceGeneratorTest.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateSequenceGeneratorTest.java
Labels: TypeEnhancement, enhancement

#5770 Remove new validation that is causing random fails for integration tests
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
  liquibase-standard/src/test/groovy/liquibase/snapshot/SnapshotGeneratorChainTest.groovy
Labels: skipReleaseNotes

#5771 fix: handles nullpointer
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
Labels: skipReleaseNotes

#5772 Revert class that breaks integration tests
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
  liquibase-standard/src/test/groovy/liquibase/snapshot/SnapshotGeneratorChainTest.groovy
Labels: skipReleaseNotes

#5755 detect duplicate jars that do not have a version (DAT-16044)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseLauncherTest.groovy
Labels: TypeBug

#5727 fixes #5724: compare normalized file paths
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/RanChangeSetTest.java
Labels: TypeBug

#5703 Also replace '@' character in temporary file names DAT-17292
  liquibase-standard/src/main/java/liquibase/util/FilenameUtil.java
  liquibase-standard/src/test/groovy/liquibase/util/FilenameUtilTest.groovy
Labels: TypeBug

#5788 use java-version 17 for sonar scan from branch fix/DAT-17391
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#5777 Prevent error when unlocking the changelog in MySQL affects zero rows and useAffectedRows is true. Fixes #5502
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: TypeEnhancement

#5792 fix: keep indexes list in the order returned by database
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
Labels: TypeBug

#5741 Implement Customizer for SpringLiquibase.
  liquibase-standard/src/main/java/liquibase/integration/spring/Customizer.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/test/java/liquibase/integration/spring/SpringLiquibaseTest.java
Labels: TypeEnhancement, IntegrationSpringboot

#5806 DAT-17457
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#5809 Update run-tests.yml
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#5807 chore: fake coverage test
  liquibase-standard/src/test/java/liquibase/changelog/ChangeLogIncludeAllTest.java
Labels: skipReleaseNotes

#5794 fix calculation of total change sets in update summary (DAT-17262)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
Labels: TypeBug

#5808 Test/dat 16100 groovy
  liquibase-standard/src/test/groovy/liquibase/changelog/ChangeLogIncludeAllTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/ChangeLogIncludeAllTest.java
Labels: skipReleaseNotes

#5793 move output file handling into factory pattern (DAT-17290)
  liquibase-cli/src/main/java/liquibase/integration/commandline/CommandRunner.java
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/io/OutputFileHandler.java
  liquibase-standard/src/main/java/liquibase/io/OutputFileHandlerFactory.java
  liquibase-standard/src/main/java/liquibase/io/StandardOutputFileHandler.java
Labels: TypeEnhancement

#5817 Improve coverage
  liquibase-standard/src/test/groovy/liquibase/change/ColumnConfigTest.groovy
Labels: skipReleaseNotes

#5804 DAT-16515
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5714 Introduce a method with a correct name of `StringUtil.randomIdentifer()`.
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/StringUtilTest.groovy
Labels: TypeEnhancement

#5780 Deprecate ThreadLocalScopeManager as it is no longer required
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-standard/src/main/java/liquibase/ThreadLocalScopeManager.java
Labels: TypeEnhancement

#5819 unignore and fix ChangeDefinitionTest (DAT-17344)
  liquibase-standard/src/test/groovy/liquibase/change/ChangeDefinitionTest.groovy
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: skipReleaseNotes

#5820 DAT-16515: fix the mv command
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5821 azure uber jar fix
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5823 DAT-16515: add missing v in the uber-jar creation
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5762 Feat/fossa test
  .github/workflows/fossa.yml
Labels: TypeEnhancement

#5799 Add new lifecycle methods for UpdateTestingRollbackCommandStep (DAT-15641)
  liquibase-standard/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateTestingRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java
Labels: TypeEnhancement

#5715 Add `@Deprecated` annotation.
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/wrapper/UnimplementedWrapper.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/change/Change.java
  liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-standard/src/main/java/liquibase/change/core/AbstractModifyDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/servlet/GenericServletListener.java
  liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/util/BooleanParser.java
  liquibase-standard/src/main/java/liquibase/util/BooleanUtils.java
  liquibase-standard/src/main/java/liquibase/util/JdbcUtils.java
  liquibase-standard/src/main/java/liquibase/util/NumberUtil.java
  liquibase-standard/src/main/java/liquibase/util/NumberUtils.java
  liquibase-standard/src/main/java/liquibase/util/StreamUtil.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/main/java/liquibase/util/file/FilenameUtils.java
Labels: TypeEnhancement

#5782 Update ChangeSetService to handle new ModifyChangeset creation (DAT-17322)
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changeset/ChangeSetService.java
  liquibase-standard/src/main/java/liquibase/changeset/StandardChangeSetService.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
Labels: TypeEnhancement

#5716 Fix typos
  CODE_OF_CONDUCT.md
  changelog.txt
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/test/java/org/liquibase/maven/MavenIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
  liquibase-standard/src/main/java/liquibase/change/Change.java
  liquibase-standard/src/main/java/liquibase/change/ChangeWithColumns.java
  liquibase-standard/src/main/java/liquibase/change/DatabaseChange.java
  liquibase-standard/src/main/java/liquibase/change/DatabaseChangeProperty.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/change/core/SQLFileChange.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChange.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSetStatus.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/AlreadyRanChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/command/AbstractCliWrapperCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/CleanUpCommandStep.java
  liquibase-standard/src/main/java/liquibase/configuration/ConfigurationDefinition.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/core/MariaDBDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SybaseASADatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SybaseDatabase.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/ColumnComparator.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/TableComparator.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/SingleColumnRowMapper.java
  liquibase-standard/src/main/java/liquibase/integration/ant/BaseLiquibaseTask.java
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
  liquibase-standard/src/main/java/liquibase/plugin/AbstractPluginFactory.java
  liquibase-standard/src/main/java/liquibase/resource/ResourceAccessor.java
  liquibase-standard/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-standard/src/main/java/liquibase/snapshot/CachedRow.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddForeignKeyConstraintGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGeneratorInformix.java
  liquibase-standard/src/main/java/liquibase/statement/DatabaseFunction.java
  liquibase-standard/src/main/java/liquibase/statement/SequenceNextValueFunction.java
  liquibase-standard/src/main/java/liquibase/statement/core/CreateTableStatement.java
  liquibase-standard/src/main/java/liquibase/structure/core/Column.java
  liquibase-standard/src/main/java/liquibase/util/BooleanUtil.java
Labels: TypeEnhancement

#5840 DAT-16954 DevOps :: Deprecate Postgres 11
  liquibase-integration-tests/src/test/resources/reference.json
  liquibase-integration-tests/src/test/resources/snapshot1.json
  liquibase-integration-tests/src/test/resources/snapshot2.json
  liquibase-integration-tests/src/test/resources/target.json
Labels: sdou, skipReleaseNotes

#5846 DAT-17566
  .github/workflows/create-release.yml
  .github/workflows/run-tests.yml
Labels: TypeBug

#5813 refactor AbstractFormattedChangeLogParser to improve reusability (DAT-16478)
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
Labels: skipReleaseNotes

#5831 Resolve Sign artifacts issue
  .github/util/re-version.sh
  .github/workflows/create-release.yml
  liquibase-cli/pom.xml
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: skipReleaseNotes

#5836 run integration tests against cloud Snowflake weekly (DAT-17037)
  .github/workflows/weekly-integration-tests.yml
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/SnowflakeTestSystem.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/snowflake/SnowflakeIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/object.quoting.strategy.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/snowflake/complete/included.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/snowflake/complete/renamed.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/snowflake/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/snowflake/rollback/rollbackable.changelog.xml
Labels: TypeTest

#5852 DAT-16515-v
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#5814 refactor ValidatingVisitor to use factory pattern, error if strict is set and defaults file does not exist (DAT-15920)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/StandardValidatingVisitorGenerator.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitorGenerator.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitorGeneratorFactory.java
  liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
  liquibase-standard/src/test/groovy/liquibase/exception/ValidationFailedExceptionTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/ChangeLogIteratorTest.java
Labels: TypeEnhancement

#5861 Update db2 docker location
  liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
Labels: skipReleaseNotes

#5860 chore: increasing test coverage
  liquibase-standard/src/test/groovy/liquibase/serializer/core/string/StringSnapshotSerializerReadableTest.groovy
  liquibase-standard/src/test/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializerTest.java
Labels: skipReleaseNotes
