Repository liquibase/liquibase, pull requests merged in 2024-09, with the labels that each got.

#6292 [DAT-18302] DevOps :: Add Dry Run capabilities to liquibase packages (updated docs)
  .github/workflows/README.md
  .github/workflows/create-release.yml
  .github/workflows/doc/img/dry-run.png
  .github/workflows/doc/img/ecr.png
  .github/workflows/doc/img/s3.png
Labels: sdou, skipReleaseNotes

#6241 For MariaDB, verify existence of the lock table a different way to suppress log message
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeBug

#6129 Support Hashicorp Vault settings in the Maven Plugin POM
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6249 Merge After 4.29.2 Release - do not SQUASH!
  .github/workflows/build-extension-jars.yml
  .github/workflows/release-published.yml
  changelog.txt
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/strict.changelog.xml
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
  liquibase-standard/src/main/java/liquibase/datatype/DataTypeFactory.java
  liquibase-standard/src/main/java/liquibase/license/LicenseService.java
  liquibase-standard/src/main/java/liquibase/license/LicenseServiceUtils.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.flowfile.yaml
  pom.xml
Labels: skipReleaseNotes, AI Generated Code

#6286 #6264 append the cause of the problem to thrown exception
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug, runFunctional&HarnessTests

#6222 fix: Handle command arguments static behavior
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibasecommandLineThreadingTest.groovy
  liquibase-cli/src/test/resources/changelog.xml
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
Labels: TypeBug, runFunctional&HarnessTests

#6300 Add method to reset command definitions cache in CommandFactory for testing
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
Labels: TypeEnhancement

#6301 🔧 DAT-18613: Fetch all tags from the remote
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#4668 Expand variables in the --sql argument to executeSql Github issue 4666
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/executeSql.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
Labels: TypeBug, runFunctional&HarnessTests

#6165 fix splitting SQL statements containing @begin or #begin
  liquibase-standard/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
  liquibase-standard/src/test/groovy/liquibase/util/StringUtilTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy
Labels: TypeBug

#6304 🔧 DAT-18281 : Ref branch to checkout for Released Publish
  .github/workflows/release-published.yml
Labels: TypeEnhancement, skipReleaseNotes

#6128 'MANUAL' MySQL reserved word added
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
Labels: TypeBug, runFunctional&HarnessTests

#6265 Dat 18350
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandWithIncludeAll.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter/test.sql
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/logicalFilePath.xml
  liquibase-integration-tests/src/test/resources/liquibase/changelog-with-includeAll-logical.xml
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIncludeAll.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement, runFunctional&HarnessTests

#6309 fix: Locale test fix
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeBug

#6314 Fix dry run slack users
  .github/workflows/dry-run-release.yml
Labels: sdou, skipReleaseNotes

#6327 Update changelog.txt
  .github/workflows/build.yml
  .github/workflows/cleanup-branch-builds.yml
  .github/workflows/dry-run-release.yml
  .github/workflows/release-published.yml
  .github/workflows/run-functional-tests.yml
  .github/workflows/run-tests.yml
  changelog.txt
  liquibase-cdi-jakarta/pom.xml
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibasecommandLineThreadingTest.groovy
  liquibase-cli/src/test/resources/changelog.xml
  liquibase-core/pom.xml
  liquibase-dist/pom.xml
  liquibase-extension-testing/pom.xml
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandWithIncludeAll.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter/test.sql
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/logicalFilePath.xml
  liquibase-integration-tests/src/test/resources/liquibase/changelog-with-includeAll-logical.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/executeSql.test.groovy
  liquibase-maven-plugin/pom.xml
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogIncludeAll.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/servicelocator/StandardServiceLocator.java
  liquibase-standard/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/StringUtilTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy
  pom.xml
Labels: TypeEnhancement, AI Generated Code, TypeTechDebt

#6317 make log level configurable for analytics and default to off (DAT-18577)
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsFactory.java
  liquibase-standard/src/main/java/liquibase/analytics/NoOpAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/SegmentAnalyticsConfiguration.java
Labels: skipReleaseNotes

#6298 record individual events for flow command (DAT-18448)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentBatch.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
Labels: skipReleaseNotes

#6334 fix userId not finding license owner correctly, include license key in userId (DAT-18653)
  liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentBatch.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentTrackEvent.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/SegmentAnalyticsConfiguration.java
  liquibase-standard/src/main/java/liquibase/license/LicenseService.java
Labels: skipReleaseNotes

#6333 Log the database platform when running generate changelog in mdc and analytics (DAT-18647)
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
Labels: TypeBug

#6308 Handle offline connection for Snowflake during diff DAT-18652
  liquibase-snowflake/src/main/java/liquibase/executor/jvm/SnowflakeJdbcExecutor.java
Labels: TypeBug

#6321 put integration details in scope when running via spring (DAT-18605)
  liquibase-standard/src/main/java/liquibase/integration/IntegrationDetails.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: skipReleaseNotes

#6318 Always add database information to MDC and analytics when running via maven (DAT-18630)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
Labels: TypeBug, runFunctional&HarnessTests

#6341 Fix sqlite hsqldb and environment variable tests (DAT-18646)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/EnvironmentVariableProviderForTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/StrictIntegrationTests.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/java/liquibase/dbtest/sqlite/SQLiteIntegrationTest.java
Labels: TypeBug

#6325 recognize when Liquibase is running in a docker container (DAT-18560)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
Labels: skipReleaseNotes

#6280 DAT-18538 :: Undeprecate StringUtil class
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeEnhancement, TypeTechDebt

#6349 upgrade to mssql 2022 for ITs
  liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
Labels: skipReleaseNotes

#6353 Fix possible NPE when constructing Event object
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
Labels: TypeBug

#6346 add Java API to liquibaseInterface field (DAT-18606)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
Labels: skipReleaseNotes

#6358 make global argument definitions static so that they are visible across all threads
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineThreadingTest.groovy
  liquibase-standard/src/main/java/liquibase/configuration/LiquibaseConfiguration.java
Labels: TypeBug

#6352 pretty-print request body to Segment (DAT-18702)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
Labels: skipReleaseNotes

#6347 handle when new properties are added to config endpoint (DAT-18723)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/configuration/RemoteAnalyticsConfiguration.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/SegmentAnalyticsConfiguration.java
Labels: skipReleaseNotes
