Repository liquibase/liquibase, pull requests merged in 2024-06, with the labels that each got.

#5974 fix weekly-integration-tests.yml slack notifications
  .github/workflows/weekly-integration-tests.yml
Labels: skipReleaseNotes

#5950 add default constructor + setters to `DatabaseChangeLogLock`
  liquibase-standard/src/main/java/liquibase/lockservice/DatabaseChangeLogLock.java
Labels: TypeEnhancement

#5977 fully qualify names of tables when snapshotting unique constraints in Snowflake (DAT-17880)
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/UniqueConstraintSnapshotGeneratorSnowflake.java
Labels: TypeBug

#5954 DAT-16824 DevOps :: Add ability to run tests against real cloud infrastructure
  .github/workflows/weekly-integration-tests.yml
Labels: sdou

#5980 DAT-17768 - Add new directory internal/ext to classpath
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-dist/src/main/archive/lib/README.txt
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: TypeEnhancement

#5957 retain original dbms string (DAT-17621)
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: skipReleaseNotes

#5979 DAT-17261
  .github/workflows/installer-build-check.yml
Labels: skipReleaseNotes

#5983 🛠️ fix/part-1: DAT-17797
  .github/workflows/fossa.yml
Labels: TypeEnhancement, skipReleaseNotes

#5774 Prevent spurious SET SEARCH_PATH SQL statements for Postgres during update-sql command. Fixes #5316
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
Labels: TypeBug

#5992 turn on DB2 integration tests (DAT-17759)
  .github/workflows/run-tests.yml
  liquibase-extension-testing/src/main/resources/liquibase.sdk.yaml
Labels: skipReleaseNotes

#5989 DAT-17896 Trigger functional and harness tests by request
  .github/workflows/build.yml
  .github/workflows/run-functional-tests.yml
  .github/workflows/run-test-harness.yml
Labels: TypeEnhancement, runFunctionalTests, runTestHarnessTests

#5911 Fix sequenceExists check that became case sensitive for Postgresql
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/precondition/core/SequenceExistsPrecondition.java
Labels: TypeBug, DBPostgres

#5986 fix incorrect line breaks and wrapping when generating table output (DAT-17891 and DAT-17288)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateCount.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateToTag.test.groovy
  liquibase-standard/src/main/java/liquibase/util/TableOutput.java
  liquibase-standard/src/test/groovy/liquibase/util/TableOutputTest.groovy
Labels: TypeBug

#5985 DAT-16264 DevOps :: liquibase build fails on Publish to Maven Central - Nexus
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#5982 DAT-17770 Package BQ commercial jar inside liquibase tar ball & zip
  .github/util/re-version.sh
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
Labels: sdou, skipReleaseNotes

#5766 Use lombok getter and setter.
  liquibase-standard/src/main/java/liquibase/change/AbstractTableChange.java
  liquibase-standard/src/main/java/liquibase/change/ChangeStatus.java
  liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-standard/src/main/java/liquibase/change/ConstraintsConfig.java
  liquibase-standard/src/main/java/liquibase/change/core/AbstractModifyDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddAutoIncrementChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddDefaultValueChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddForeignKeyConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddLookupTableChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddNotNullConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddPrimaryKeyChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AddUniqueConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/AlterSequenceChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateIndexChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateSequenceChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateViewChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropAllForeignKeyConstraintsChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropDefaultValueChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropForeignKeyConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropIndexChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropNotNullConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropPrimaryKeyChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropProcedureChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropSequenceChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropTableChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropUniqueConstraintChange.java
  liquibase-standard/src/main/java/liquibase/change/core/DropViewChange.java
  liquibase-standard/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-standard/src/main/java/liquibase/change/core/InsertDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataColumnConfig.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadUpdateDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/MergeColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/core/ModifyDataTypeChange.java
  liquibase-standard/src/main/java/liquibase/change/core/RawSQLChange.java
  liquibase-standard/src/main/java/liquibase/change/core/RenameColumnChange.java
  liquibase-standard/src/main/java/liquibase/change/core/RenameSequenceChange.java
  liquibase-standard/src/main/java/liquibase/change/core/RenameTableChange.java
  liquibase-standard/src/main/java/liquibase/change/core/RenameViewChange.java
  liquibase-standard/src/main/java/liquibase/change/core/SetColumnRemarksChange.java
  liquibase-standard/src/main/java/liquibase/change/core/SetTableRemarksChange.java
  liquibase-standard/src/main/java/liquibase/change/core/TagDatabaseChange.java
  liquibase-standard/src/main/java/liquibase/change/visitor/ChangeVisitorFactory.java
  liquibase-standard/src/main/java/liquibase/integration/ant/ChangeLogSyncTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/ChangeLogSyncToTagTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/DBDocTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/DatabaseRollbackTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/DatabaseUpdateTestingRollbackTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/DiffDatabaseTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/DiffDatabaseToChangeLogTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/DropAllTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/GenerateChangeLogTask.java
  liquibase-standard/src/main/java/liquibase/integration/ant/TagDatabaseTask.java
  liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java
  liquibase-standard/src/main/java/liquibase/logging/LogFormat.java
Labels: TypeEnhancement

#5993 Move ChangeLogParameters helper methods to ChangeLogParameters class (DAT-17883)
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeEnhancement, enhancement

#5929 add detached mode for running H2 (DAT-17654)
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/initstartH2.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/StartH2CommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/StopH2CommandStep.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.command.CommandStep
Labels: TypeEnhancement

#5988 High Level API (aka undeprecate Liquibase class)
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeEnhancement

#6010 Skip harness and functional tests instead of failing workflow, one trigger for harness and functional to avoid multiple triggers
  .github/workflows/run-functional-tests.yml
  .github/workflows/run-test-harness.yml
Labels: skipReleaseNotes

#6022 Changed condition to trigger tests
  .github/workflows/run-functional-tests.yml
  .github/workflows/run-test-harness.yml
Labels: runFunctional&HarnessTests

#5802 refactored data clumps
  liquibase-standard/src/main/java/liquibase/precondition/core/TableIsEmptyPrecondition.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddAutoIncrementStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddColumnStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddDefaultValueStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddPrimaryKeyStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/AddUniqueConstraintStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/CreateTableStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/DatabaseTableIdentifier.java
  liquibase-standard/src/main/java/liquibase/statement/core/DeleteStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/DropColumnStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/DropDefaultValueStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/DropPrimaryKeyStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/DropTableStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/DropUniqueConstraintStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/InsertSetStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/InsertStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/ModifyDataTypeStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/ReindexStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/RenameColumnStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/ReorganizeTableStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/SetColumnRemarksStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/SetNullableStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/SetTableRemarksStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/TableIsEmptyStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/TableRowCountStatement.java
  liquibase-standard/src/main/java/liquibase/statement/core/UpdateStatement.java
Labels: TypeEnhancement

#5925 feat: FastCheck refactoring
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandStepIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/fast.check.changelog.test.xml
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/changelog/FastCheckService.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: TypeEnhancement

#6017 Fix issue 5944
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/resources/liquibase/load-data.test.csv
Labels: TypeBug, runFunctional&HarnessTests

#6008 DAT-16650 Automate OWASP scanner
  .github/workflows/create-release.yml
  .github/workflows/owasp-scanner.yml
Labels: sdou, skipReleaseNotes

#6030 DAT-17939 Add ability to generate Liquibase zip with extensions for any PR
  .github/workflows/create-release.yml
  .github/workflows/create-standalone-zip.yml
Labels: sdou, skipReleaseNotes

#6032 DAT-17939 Add ability to generate Liquibase zip with extensions for any PR
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
  .github/workflows/create-standalone-zip.yml
  .github/workflows/run-tests.yml
Labels: sdou, skipReleaseNotes

#5704 Fix SQL execution issue with endDelimiter '/' and splitStatements
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeBug, DocNeeded, runFunctional&HarnessTests

#4115 PD-3256: STRICT=true description
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
Labels: skipReleaseNotes, runFunctional&HarnessTests

#5958 Clone system properties to prevent ConcurrentModificationException
  liquibase-standard/src/main/java/liquibase/configuration/core/ScopeValueProvider.java
  liquibase-standard/src/main/java/liquibase/configuration/core/SystemPropertyValueProvider.java
Labels: java-api, typeBug

#6034 feat: Add status command output + tests to make sure that ir runs at same time than update.
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgresThreadingTest.java
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/pg_sleep.sql
  liquibase-standard/src/main/java/liquibase/command/core/StatusCommandStep.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/SimpleStatus.java
Labels: runFunctional&HarnessTests, typeEnhancement

#6021 feat: Add dependencies for apache commons libraries that are being used
  liquibase-standard/pom.xml
  pom.xml
Labels: runFunctional&HarnessTests, typeEnhancement

#6042 Fix/windows value DAT-17704
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#5924 Optimize parsing big xml files
  liquibase-standard/src/main/java/liquibase/util/ObjectMethods.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/test/java/liquibase/util/ObjectMethodsTest.java
Labels: TypeEnhancement

#5966 Add support for NULL placeholders on loadData
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataColumnConfig.java
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataColumnConfigTest.groovy
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.with.nulls.csv
Labels: TypeEnhancement, runFunctional&HarnessTests

#6027 chore: allow slf4j library to be included in liquibase zip/installer
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: runFunctional&HarnessTests

#6055 🛞 DAT-16651: Update docs to latest OSS-PRO version
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6057 Update release-published.yml
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6058 DAT-16651: Fir minor issues with OSS/PRO version in files
  .github/workflows/release-published.yml
Labels: skipReleaseNotes
