Repository liquibase/liquibase, pull requests merged in 2024-08, with the labels that each got.

#6141 4.29.1 release
  .github/util/re-version.sh
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
  changelog.txt
  liquibase-cli/pom.xml
Labels: skipReleaseNotes, AI Generated Code

#6158 🔧 DAT-17914
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6132 optionally suppress Liquibase SQL for *-sql commands (DAT-18013)
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/updateSql.test.groovy
  liquibase-standard/src/main/java/liquibase/executor/LoggingExecutor.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6137 changes in support of globally setting stripComments option (DAT-17390)
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/changeset/ChangeSetService.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
Labels: skipReleaseNotes

#6114 Handle reporting of changes which are skipped due to license issues DAT-17659
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
  liquibase-standard/src/main/java/liquibase/util/ShowSummaryUtil.java
Labels: TypeEnhancement

#6094 [DAT-17993] Improve diffChangelog between MSSQL and Oracle
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotMSSQLIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/main/java/liquibase/diff/ObjectDifferences.java
  liquibase-standard/src/main/java/liquibase/diff/compare/core/DefaultDatabaseObjectComparator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangedPrimaryKeyChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/structure/core/PrimaryKey.java
Labels: TypeEnhancement, TypeBug, runFunctional&HarnessTests

#6162 DAT-18250 DevOps :: Clean up branch build not working
  .github/workflows/cleanup-branch-builds.yml
Labels: sdou, skipReleaseNotes

#6166 compare contents of zip file against baseline (DAT-18324)
  .github/workflows/build.yml
  liquibase-dist/expected-distribution-contents-targz.txt
  liquibase-dist/expected-distribution-contents-zip.txt
Labels: skipReleaseNotes

#6163 maven flag for suppressLiquibaseSql (DAT-18273)
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement

#6159 Append included labels to the changeset labels when matching DAT-16636
  liquibase-standard/src/main/java/liquibase/changelog/filter/LabelChangeSetFilter.java
  liquibase-standard/src/test/java/liquibase/changelog/filter/LabelChangeSetFilterTest.java
Labels: TypeBug, runFunctional&HarnessTests

#6119 chore: upgrade installer jdk version to 21.0.4+7
  liquibase-dist/src/main/install4j/liquibase.install4j
Labels: TypeEnhancement

#6118 Fix serialization of DatabaseChangeLog with 'preConditions' for yaml
  liquibase-integration-tests/src/test/resources/changelogs/yaml/common.tests.changelog.yaml
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/precondition/PreconditionLogic.java
  liquibase-standard/src/main/java/liquibase/precondition/core/PreconditionContainer.java
Labels: TypeBug, runFunctional&HarnessTests

#6067 Add additional duplicateFileMode options
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/resource/ResourceAccessor.java
  liquibase-standard/src/test/groovy/liquibase/resource/ResourceAccessorTest.groovy
Labels: TypeEnhancement, DocNeeded

#6168 Do not show update summary when using update-sql via maven plugin (DAT-18323)
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeBug

#6170 fix case where expiration date is null in --version output (DAT-18360)
  liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java
Labels: skipReleaseNotes, runFunctional&HarnessTests

#6080 RawSqlStatement Liquibase PRO Refactoring
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: TypeBug, PRAssociated, runFunctional&HarnessTests

#6073 fix mysql datetime type according to the column size
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
  liquibase-standard/src/test/groovy/liquibase/snapshot/jvm/ColumnSnapshotGeneratorTest.groovy
Labels: TypeBug, DBMySQL, runFunctional&HarnessTests

#6179 Make Scope ID RNG no longer use SecureRandom (fix #6178)
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeEnhancement

#6198 Use correct method for Maven updateSQL DAT-18142
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java
Labels: TypeBug

#6209 initial add of analytics tracking and supporting classes (DAT-17823)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsConfiguration.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsOutputDestination.java
  liquibase-standard/src/main/java/liquibase/analytics/CsvAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
  liquibase-standard/src/main/java/liquibase/analytics/NoOpAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/UsageAnalyticsFactory.java
  liquibase-standard/src/main/java/liquibase/analytics/UsageAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/IntegrationDetails.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/json/JsonChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlParser.java
  liquibase-standard/src/main/java/liquibase/util/Cache.java
  liquibase-standard/src/main/java/liquibase/util/ExceptionUtil.java
  liquibase-standard/src/main/java/liquibase/util/LiquibaseLauncherSettings.java
  liquibase-standard/src/main/java/liquibase/util/VersionUtils.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations
Labels: skipReleaseNotes

#6185 Fixes issue 6054: incorrect system table query on DB2 AS/400 platform
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug

#6143 Truncate Oracle PK names based on DB version
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/test/java/liquibase/database/core/OracleDatabaseTest.java
Labels: TypeEnhancement

#6224 initial add of Segment analytics integration (DAT-18462)
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsConfiguration.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentBatch.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentTrackEvent.java
  liquibase-standard/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
Labels: skipReleaseNotes

#6226 Do not throw exception if data type is not supported by database
  liquibase-standard/src/main/java/liquibase/datatype/DataTypeFactory.java
Labels: TypeBug

#6218 Do not release lock if not locked by this update DAT-18370
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
Labels: TypeBug

#6244 fix cleanup-branch-builds.yml
  .github/workflows/cleanup-branch-builds.yml
Labels: skipReleaseNotes

#6232 add method to LicenseService to allow custom invalid license message (DAT-18196)
  liquibase-standard/src/main/java/liquibase/license/LicenseService.java
  liquibase-standard/src/main/java/liquibase/license/LicenseServiceUtils.java
Labels: skipReleaseNotes

#6157 fix: EndDelimiter not working as expected since 4.29
  liquibase-integration-tests/src/test/java/liquibase/dbtest/oracle/OracleIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/strict.changelog.xml
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeBug, DocNeeded, runFunctional&HarnessTests

#6204 Changing Quality Checks -> Policy Checks
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/json/liquibase.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/sql/liquibase.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/xml/liquibase.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.advanced.flowfile.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.checks-package.yaml
  liquibase-standard/src/main/resources/liquibase/examples/yaml/liquibase.flowfile.yaml
Labels: TypeEnhancement

#6248 DAT-18301 DevOps :: Add Dry Run capabilities to liquibase
  .github/workflows/README.md
  .github/workflows/create-release.yml
  .github/workflows/doc/img/dry-run.png
  .github/workflows/doc/img/nexus.png
  .github/workflows/dry-run-relase.yml
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#6250 DAT-18301 DevOps :: Add Dry Run capabilities to liquibase
  .github/workflows/dry-run-relase.yml
Labels: sdou, skipReleaseNotes

#6255 DAT-18501 DevOps :: Clean up branch build not working
  .github/workflows/cleanup-branch-builds.yml
Labels: sdou, skipReleaseNotes

#6257 DAT-17957 DevOps :: Fix the “Cleanup on branch delete” job
  .github/workflows/cleanup-branch-builds.yml
Labels: sdou, skipReleaseNotes

#6259 reorganize and add enabled argument (DAT-18297)
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsConfiguration.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsOutputDestination.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/SegmentBatch.java
  liquibase-standard/src/main/java/liquibase/analytics/UsageAnalyticsFactory.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/telemetry/CsvAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/telemetry/Event.java
  liquibase-standard/src/main/java/liquibase/telemetry/NoOpAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/telemetry/SegmentBatch.java
  liquibase-standard/src/main/java/liquibase/telemetry/SegmentTelemetryListener.java
  liquibase-standard/src/main/java/liquibase/telemetry/SegmentTrackEvent.java
  liquibase-standard/src/main/java/liquibase/telemetry/TelemetryFactory.java
  liquibase-standard/src/main/java/liquibase/telemetry/TelemetryListener.java
  liquibase-standard/src/main/java/liquibase/telemetry/TelemetryOutputDestination.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/RemoteTelemetryConfiguration.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/SegmentTelemetryConfiguration.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryArgs.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryConfiguration.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryConfigurationFactory.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations
  liquibase-standard/src/test/groovy/liquibase/telemetry/TelemetryArgsTest.groovy
Labels: skipReleaseNotes

#6262 DAT-18302 DevOps :: Add Dry Run capabilities to liquibase packages
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#6269 Changelog for 4.29.2 + revert snowflake driver + slf4j versions
  changelog.txt
  liquibase-dist/pom.xml
  pom.xml
Labels: skipReleaseNotes

#6268 turn off pro by default/make pro opt-in (DAT-18297)
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryArgs.java
  liquibase-standard/src/test/groovy/liquibase/telemetry/TelemetryArgsTest.groovy
Labels: skipReleaseNotes

#6267 load telemetry configuration from remote server (DAT-18404)
  liquibase-standard/src/main/java/liquibase/telemetry/CsvAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/telemetry/SegmentTelemetryListener.java
  liquibase-standard/src/main/java/liquibase/telemetry/TelemetryOutputDestination.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/RemoteTelemetryConfiguration.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/SegmentTelemetryConfiguration.java
  liquibase-standard/src/main/java/liquibase/telemetry/configuration/TelemetryArgs.java
Labels: skipReleaseNotes

#6277 add telemetry integration test
  liquibase-integration-tests/pom.xml
  liquibase-integration-tests/src/test/groovy/liquibase/telemetry/TelemetryIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/telemetry/SegmentTrackEvent.java
Labels: skipReleaseNotes

#6278 DAT-18302 DevOps :: Add Dry Run capabilities to liquibase packages
  .github/workflows/create-release.yml
  .github/workflows/dry-run-release.yml
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#6279 release_4292_changelog
  changelog.txt
Labels: skipReleaseNotes

#6187 Update JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug

#6261 fix: do not throw an unchecked exception for SpringBoot
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: TypeBug

#6211 Update Postgres database major and minor versions.
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
Labels: TypeEnhancement

#5223 Improve empty check style by using isEmpty String method
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorSnowflake.java
  liquibase-standard/src/main/java/liquibase/change/core/ExecuteShellCommandChange.java
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/change/core/OutputChange.java
  liquibase-standard/src/main/java/liquibase/datatype/core/DateTimeType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/DateType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/TimeType.java
  liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXHandler.java
  liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertOrUpdateGeneratorHsql.java
  liquibase-standard/src/main/java/liquibase/util/StandardSqlParser.java
  liquibase-standard/src/main/java/liquibase/util/StringClauses.java
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/java/liquibase/verify/AbstractVerifyTest.java
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.csv
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.with.null.and.emptys.csv
Labels: TypeEnhancement

#6169 update-to-tag fixes when provided tag doesn't exist or there is not tagDatabaseChange in the changelog
  liquibase-integration-tests/src/test/groovy/liquibase/StrictIntegrationTests.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpdateToTagIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/liquibase/update-to-tag-changelog.xml
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagCommandStep.java
Labels: TypeEnhancement, DocNeeded

#6263 DAT-18148 - Fix generated column value for Databricks
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
Labels: TypeEnhancement

#6285 🔧 Ensure the workflow can read/write branches
  .github/workflows/build.yml
Labels: skipReleaseNotes
