Repository liquibase/liquibase, pull requests merged in 2024-12, with the labels that each got.

#6529 Do not propagate logical file path to included change sets from raw SQL changelogs DAT-19040
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
Labels: TypeBug

#6499 optionally suppress SQL in reports (DAT-17940)
  liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java
  liquibase-standard/src/main/java/liquibase/report/OperationInfo.java
  liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
  liquibase-standard/src/main/java/liquibase/report/UpdateRollbackReportParameters.java
Labels: skipReleaseNotes

#6557 Do not retrieve ran change sets if there is no database connection DAT-19095
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug

#6378 GenerateChangelogCommandStep must only report having written a Changelog file if it did so
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogEmptyIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/changelogs/update.changelog.sql
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
Labels: TypeEnhancement

#6254 Output calculated checksum to `stdout`.
  liquibase-standard/src/main/java/liquibase/command/AbstractCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
Labels: TypeBug

#5595 Add changeset execution time to output
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java
Labels: TypeEnhancement

#6523 Fix Sequence generator - cache size, data type - for various DBs
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
  liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createSequence/db2.sql
  liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/createSequence/db2i.sql
Labels: TypeEnhancement, runFunctional&HarnessTests, manuallyTested

#6556 feat(DAT-19013): Enhance History Command to filter changesets by tags
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/HistoryCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/command/HistoryCommandStepTest.groovy
Labels: TypeEnhancement, DocNeeded, runFunctional&HarnessTests, manuallyTested

#6469 Fix README workflow status
  .github/workflows/run-tests.yml
  README.md
Labels: TypeBug

#6565 Update changeset execution time to better practices
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: TypeEnhancement

#6571 fix breaking changes introduced in #6565
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: skipReleaseNotes

#6536 Implement copy method in FilesystemProjectCopier (DAT-18890)
  liquibase-standard/src/main/java/liquibase/command/copy/FileSystemProjectCopier.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InitCopyCommandStep.java
Labels: TypeEnhancement

#6328 Added a stub attribute to CommandStep interface so commands can be recognized as stubs
  liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
Labels: TypeBug

#6558 Added stub method in to handle duplicates in sub-commands DAT-19049
  liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/command/CommandStep.java
  liquibase-standard/src/main/java/liquibase/command/copy/FileSystemProjectCopier.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InitCopyCommandStep.java
Labels: TypeEnhancement

#6575 Set flag to turn off compatibility check for liquibase-checks in dropAll
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
Labels: TypeBug

#6519 Fix the XSD adding the nullPlaceholder attribute for loadData column
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/nullPlaceHolderTestData.csv
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/nullPlaceholder.test.changelog.xml
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: TypeBug, DocNeeded, manuallyTested

#6578 Fix fossa ai execution for contributed PRs
  .github/workflows/fossa_ai.yml
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#5653 Deployment ID enhancements and execution property
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupChangeLogSync.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupChangelogHistory.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupDatabaseStructure.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupRollbackCount.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupRunChangelog.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/update/UpdateIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/statementexecute/MarkChangeSetRanExecuteTest.java
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter/1.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter/2.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/main/java/liquibase/changelog/MockChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/OfflineChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeLogSyncVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractFutureRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/MarkNextChangesetRanCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/TagCommandStep.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-standard/src/test/groovy/liquibase/ScopeTest.groovy
  liquibase-standard/src/test/java/liquibase/changelog/OfflineChangeLogHistoryServiceTest.java
Labels: TypeEnhancement, notableChanges, DocNeeded, manuallyTested

#6570 Recognize flag to prevent exception in the case where a change type is not supported DAT-19074
  liquibase-standard/src/main/java/liquibase/change/ChangeFactory.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: TypeBug, runFunctional&HarnessTests

#6591 DAT-19268 Remove stubs, now trapping for a checks command in Main
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/command/CommandStep.java
Labels: TypeEnhancement

#6572 ignore individual AWS extension jars if combined jar is present (DAT-19091)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
Labels: notableChanges

#6595 chore: update deprecated action across all locations
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/installer-build-check.yml
  .github/workflows/run-pro-build-and-test.yml
  .github/workflows/run-tests.yml
  .github/workflows/weekly-integration-tests.yml
Labels: skipReleaseNotes

#6598 chore: remove references to branch DAT-19069
  .github/workflows/build.yml
  .github/workflows/run-pro-build-and-test.yml
Labels: skipReleaseNotes

#6599 chore: remove duplicated fossa config file
  .github/workflows/fossa_ai.yml
Labels: skipReleaseNotes

#6600 chore: bump download actions versions
  .github/workflows/build.yml
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6601 chore: use target to get access to tokens
  .github/workflows/run-pro-build-and-test.yml
  .gitignore
Labels: skipReleaseNotes

#6602 chore: use target to get access to tokens
  .github/workflows/run-functional-tests.yml
  .github/workflows/run-test-harness.yml
Labels: skipReleaseNotes

#6590 fix: Checksum for SQL changes containing dbms attributes can get different values if md5sum column is null
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/sqlchange.with.dbms.changelog.xml
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeBug, runFunctional&HarnessTests, manuallyTested, build&TestPro

#6593 expire analytics cache after 60 minutes (DAT-19278)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java
  liquibase-standard/src/main/java/liquibase/util/Cache.java
  liquibase-standard/src/test/groovy/liquibase/util/CacheTest.groovy
Labels: skipReleaseNotes
