Repository liquibase/liquibase, pull requests merged in 2024-11, with the labels that each got.

#6486 Update release-published.yml to get the previous version
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6490 🛞 DAT-18995: populate proper client_payload for dry_run
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6498 Change automated release file version to main
  .github/workflows/release-extensions.yml
Labels: skipReleaseNotes

#6497 🔧 DAT-18995: default dry_run value to false
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6481 chore: bump upload-artifacts to v4
  .github/workflows/fossa.yml
Labels: skipReleaseNotes

#6439 Fixed issue with fail on error changeset accounting
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
Labels: TypeBug, runFunctional&HarnessTests

#6472 Fail validation for blank changeset ids (DAT-18773)
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/test/groovy/liquibase/changelog/visitor/ValidatingVisitorTest.groovy
Labels: TypeBug

#6381 Add stripComments attribute to modifyChangeSets DAT-18328
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
  liquibase-standard/src/main/java/liquibase/changelog/ModifyChangeSets.java
  liquibase-standard/src/main/java/liquibase/changeset/ChangeSetService.java
  liquibase-standard/src/main/java/liquibase/changeset/StandardChangeSetService.java
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-standard/src/test/groovy/liquibase/parser/core/json/JsonChangelogParserTest.groovy
  liquibase-standard/src/test/resources/liquibase/parser/core/json/master_changelog.json
  liquibase-standard/src/test/resources/liquibase/parser/core/sql/changelog.sql
Labels: TypeEnhancement, runFunctional&HarnessTests

#6451 Migrate init project command to core (DAT-15504)
  liquibase-integration-tests/src/test/groovy/liquibase/util/SetupDefaultsFile.groovy
  liquibase-integration-tests/src/test/resources/changelogs/init/example-changelog.json
  liquibase-integration-tests/src/test/resources/changelogs/init/example-changelog.sql
  liquibase-integration-tests/src/test/resources/changelogs/init/example-changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/init/example-changelog.yaml
  liquibase-integration-tests/src/test/resources/liquibase.sample.properties
  liquibase-integration-tests/src/test/resources/liquibase.sql.properties
  liquibase-integration-tests/src/test/resources/liquibase.xml.properties
  liquibase-integration-tests/src/test/resources/liquibase.yaml.properties
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/initproject.test.groovy
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/command/copy/FileSystemProjectCopier.java
  liquibase-standard/src/main/java/liquibase/command/copy/ProjectCopier.java
  liquibase-standard/src/main/java/liquibase/command/copy/ProjectCopierFactory.java
  liquibase-standard/src/main/java/liquibase/command/core/init/AbstractCommandLineValueGetter.java
  liquibase-standard/src/main/java/liquibase/command/core/init/DirectoryGetter.java
  liquibase-standard/src/main/java/liquibase/command/core/init/EnumGetter.java
  liquibase-standard/src/main/java/liquibase/command/core/init/FilenameGetter.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InitCopyCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InitProjectCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InitProjectPromptingEnum.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InitProjectUtil.java
  liquibase-standard/src/main/java/liquibase/command/core/init/InteractivePromptingValueProvider.java
  liquibase-standard/src/main/java/liquibase/command/core/init/StringGetter.java
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.command.CommandStep
  liquibase-standard/src/test/groovy/liquibase/servicelocator/StandardServiceLocatorTest.groovy
Labels: TypeEnhancement, runFunctional&HarnessTests

#6514 ✨ DAT- 18995
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6515 recognize isIO environment variable for analytics (DAT-18906)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
Labels: skipReleaseNotes

#6509 replace slf4j-simple with slf4j-nop (DAT-18793)
  liquibase-dist/expected-distribution-contents-targz.txt
  liquibase-dist/expected-distribution-contents-zip.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: TypeBug

#6373 Report which codePoint is illegal for XML data export
  liquibase-standard/src/main/java/liquibase/serializer/core/xml/XMLChangeLogSerializer.java
Labels: TypeEnhancement

#6495 Fix Maven issue that produces an exception when it finds a .pom file.
  liquibase-standard/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java
Labels: TypeBug

#6512 Liquibase API :: Missing changeLogParameters argument added
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeBug

#6494 Make changelog and change set logical file path settings override the setting from includeAll - Github issue 6493
  liquibase-integration-tests/src/test/groovy/liquibase/command/update/UpdateIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/changelogs/subChangelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/master.xml
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug, manuallyTested

#6453 Fix FormattedSqlChangeLogSerializer so it includes logicalFilePath in change-set info comments
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
  liquibase-standard/src/test/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializerTest.java
Labels: TypeEnhancement

#6511 SQLFile :: Dbms validation check added
  liquibase-standard/src/main/java/liquibase/change/core/SQLFileChange.java
Labels: TypeBug

#6405 fix: ignore int sizes when diffing MSSQL
  liquibase-standard/src/main/java/liquibase/diff/compare/core/ColumnComparator.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java
Labels: TypeBug, runFunctional&HarnessTests

#6492 Fix(DAT-18813): classloader configuration in LiquibaseCommandLine
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/util/ParameterUtil.java
  liquibase-standard/src/main/java/liquibase/util/LiquibaseLauncherSettings.java
Labels: TypeBug, runFunctional&HarnessTests

#6343 FIX #6342 - Liquibase Output changeset executes twice
  liquibase-integration-tests/src/test/groovy/liquibase/command/update/UpdateIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/output.xml
  liquibase-standard/src/main/java/liquibase/change/core/OutputChange.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: TypeBug

#6528 revert refactoring which broke structured logging
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: skipReleaseNotes

#6516 feat: add new properties to Spring configuration (analytics Enabled and pro license)
  liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6535 fix: only set Spring analytics scope parameter if it's defined
  liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: TypeBug

#6306 chore: refactor build scripts to remove duplication
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/release-published.yml
  liquibase-standard/pom.xml
Labels: TypeEnhancement, TypeBug, runFunctional&HarnessTests

#6547 Fix build - remove empty space from string
  .github/workflows/build.yml
Labels: skipReleaseNotes

#6542 fix: always set column properties before calculating checksum
  liquibase-standard/src/main/java/liquibase/change/core/InsertDataChange.java
Labels: TypeBug, runFunctional&HarnessTests, manuallyTested

#6553 Added liquibase-checks property
  .github/workflows/build.yml
Labels: TypeEnhancement
