Repository liquibase/liquibase, pull requests merged in 2024-07, with the labels that each got.

#5965 Do not show message for bigquery database (DAT-17497)
  liquibase-standard/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java
Labels: TypeEnhancement

#6039 command argument aliases that can be printed to help (DAT-17870)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-standard/src/main/java/liquibase/command/CommandArgumentDefinition.java
Labels: TypeEnhancement

#6046 feat: add current java version to Banner
  liquibase-standard/src/main/java/liquibase/integration/commandline/Banner.java
  liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core.properties
  liquibase-standard/src/main/resources/liquibase/i18n/liquibase-core_de.properties
  liquibase-standard/src/test/groovy/liquibase/integration/commandline/CommandLineUtilsTest.groovy
Labels: TypeEnhancement, runFunctional&HarnessTests

#6070 DAT-17863: slack notification with workflow_file_name
  .github/workflows/weekly-integration-tests.yml
Labels: skipReleaseNotes

#6079 Fix sec issue forked pr gh token
  .github/workflows/build-branch.yml
Labels: TypeBug, sdou, skipReleaseNotes

#6081 Update extension naming (DAT-18032)
  .github/workflows/build.yml
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin-checks.xml
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: TypeEnhancement

#6084 Fix workflow for checks extension (DAT-18032)
  .github/workflows/build.yml
Labels: skipReleaseNotes

#6041 Rawsqlstatement refactoring fixes
  liquibase-standard/src/main/java/liquibase/change/AbstractSQLChange.java
  liquibase-standard/src/test/java/liquibase/change/AbstractSQLChangeTest.java
Labels: TypeBug, runFunctional&HarnessTests

#6015 Fix OSGi import for `org.apache.commons.io`
  liquibase-standard/pom.xml
Labels: TypeBug

#6074 DAT-18103 Include liquibase-scripting.jar in Liquibase zip/installer
  .github/util/package-install4j.sh
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
Labels: sdou, skipReleaseNotes

#6024 fix #6019 NullPointerException when using CharType or VarcharType with H2 database
  liquibase-standard/src/main/java/liquibase/datatype/core/CharType.java
Labels: TypeBug, DBH2

#6045 Add osgi.serverloader manifest header entries for liquibase.changelog.visitor.ValidatingVisitorGenerator #6040 fix
  liquibase-standard/pom.xml
Labels: TypeBug

#6099 chore: include slf4j-simple and pin version to allow dependabot to upgrade it for us
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: TypeEnhancement, runFunctional&HarnessTests

#5975 Update diff summary results in mdc to not be recalcuated (DAT-17725)
  liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-standard/src/main/java/liquibase/diff/core/StandardDiffGenerator.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6103 update actions/upload-artifact version to v4
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/create-release.yml
Labels: sdou

#6107 DAT-18195 only fail if tests are below expected count
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6108 Fix Attach Artifacts to Draft
  .github/workflows/create-release.yml
  .github/workflows/create-standalone-zip.yml
Labels: skipReleaseNotes

#6110 Remove checks from tar, remove profile, remove licensing (DAT-18153)
  .github/workflows/build.yml
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/licenses/commercial/README.txt
  liquibase-dist/src/main/archive/licenses/commercial/psf.txt
  liquibase-dist/src/main/archive/licenses/commercial/upl.txt
  liquibase-dist/src/main/assembly/assembly-bin-checks.xml
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
Labels: skipReleaseNotes

#6036 feat: allow setting row-level dependency tracking in the create table statement on Oracle Database
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/change/core/CreateTableChange.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-standard/src/main/java/liquibase/statement/core/CreateTableStatement.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: TypeEnhancement, DBOracle, DocNeeded, ReleaseMajor

#1379 Added liquibase:snapshot command to the liquibase-maven-plugin
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseSnapshotMojo.java
Labels: TypeEnhancement, ImpactMedium, Severity3, IntegrationMaven, DBAll, featureSnapshot

#6083 Fix defaultValueComputed inside addColumn producing bad SQL with Postgres
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddColumnGenerator.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/AddColumnGeneratorTest.java
Labels: TypeBug, DBPostgres

#6097 Fixed performance issue with valueBlobFile on Postgres databases introduced in v4.18.0
  liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
Labels: TypeBug, runFunctional&HarnessTests

#5850 Change visibility of useful methods to support custom checks (DAT-16671)
  .github/workflows/build.yml
  README.md
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-core/pom.xml
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/licenses/commercial/README.txt
  liquibase-dist/src/main/assembly/assembly-bin-common.xml
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
Labels: TypeEnhancement

#6117 Remove unneeded inclusion of commons-io in liquibase-core pom.xml
  liquibase-core/pom.xml
Labels: TypeBug

#6120 Liquibase 4.29.0 files
  changelog.txt
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.29.xsd
Labels: skipReleaseNotes

#6121 chore: reversion liquibase-cli
  .github/util/re-version.sh
Labels: skipReleaseNotes

#6127 core: add breaking change to changelog
  changelog.txt
Labels: skipReleaseNotes, AI Generated Code

#6144 DAT-18308 DevOps :: Extensions are built against liquibase 0-SNAPSHOT
  .github/util/re-version.sh
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
Labels: sdou, skipReleaseNotes

#6147 chore: Release notes
  changelog.txt
Labels: skipReleaseNotes, AI Generated Code
