Repository liquibase/liquibase, pull requests merged in 2024-03, with the labels that each got.

#5530 Use static final Pattern to avoid regexp compilation each time replaceAll is called
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
Labels: TypeEnhancement, performance

#5592 Bring update summary options to all update-related goals of the maven plugin
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseUpdateMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdate.java
Labels: TypeEnhancement, IntegrationMaven, DocNeeded

#5597 Format spring package.
  liquibase-standard/src/main/java/liquibase/integration/spring/MultiTenantSpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringResource.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java
Labels: TypeEnhancement

#5583 Add backwards compatibility for procedureBody in createProcedureChange
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/yaml/create.procedure.back.compatibility.changelog.yaml
  liquibase-standard/src/main/java/liquibase/change/AbstractChange.java
  liquibase-standard/src/main/java/liquibase/change/ChangeParameterMetaData.java
  liquibase-standard/src/main/java/liquibase/change/DatabaseChangeProperty.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
Labels: TypeBug

#5555 Fix unique constraint and primary key generator issues for Postgres and H2
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddPrimaryKeyGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddUniqueConstraintGenerator.java
  liquibase-standard/src/test/groovy/liquibase/sqlgenerator/core/AddPrimaryKeyGeneratorAllVariantsTest.groovy
  liquibase-standard/src/test/groovy/liquibase/sqlgenerator/core/AddUniqueConstraintGeneratorAllVariantsTest.groovy
Labels: TypeBug

#5456 Extended formatted sql preconditions by table-/viewExists
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeEnhancement, DocNeeded

#5651 add captureExtensions and captureSql params to maven plugin (DAT-16980)
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: TypeEnhancement

#5660 Default implementation of handleInvalidEmptyPreconditionCase added in AbtractFormattedChangeLogParser to avoid breaking extensions
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
Labels: TypeBug

#5647 Rework ExceptionDetails, update rollback parameters to handle exceptions (DAT-16922)
  liquibase-standard/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/ExceptionDetails.java
  liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java
Labels: TypeEnhancement

#5656 add command tests setup action to set Java System Property (DAT-16420)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupSystemProperty.groovy
Labels: skipReleaseNotes

#5661 Add deployment id and targetted changeset details to rollback report (DAT-17041)
  liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java
Labels: TypeEnhancement

#5652 Cleanup update report parameters imports, add deployment id (DAT-16568)
  liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
Labels: TypeEnhancement

#5665 fix: ClearChecksums should not throw Exception in empty databases
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/command/core/ClearChecksumsCommandStep.java
Labels: TypeBug

#5657 [DAT-16428] Reenable ChangelogSyncIntegrationTest tests
  liquibase-integration-tests/src/test/groovy/liquibase/command/ChangelogSyncIntegrationTest.groovy
Labels: TypeBug

#5626 Add support for SnakeYaml to be able to parse timestamps correctly when timezone is set or not
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/CustomConstructYamlTimestamp.java
  liquibase-standard/src/main/java/liquibase/parser/core/yaml/YamlChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/yaml/CustomConstructYamlTimestampTest.groovy
Labels: TypeBug, BreakingChange

#5629 Fix SQL generation when having a column defined with startWith and incrementBy in Postgres
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateTableGeneratorTest.java
Labels: TypeBug

#5680 Revert "Bump net.snowflake:snowflake-jdbc from 3.14.4 to 3.15.0"
  liquibase-dist/pom.xml
  pom.xml
Labels: skipReleaseNotes

#5668 load driver from global argument as well as command argument (DAT-16381)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: TypeBug

#5694 print message to console when interactive environment is not detected (DAT-17274)
  liquibase-standard/src/main/java/liquibase/ui/ConsoleUIService.java
Labels: skipReleaseNotes

#5670 5507-performance_improvements
  liquibase-standard/src/main/java/liquibase/util/StringUtil.java
Labels: TypeEnhancement

#5709 feat: add commons-lang3 as a required dependency for core
  liquibase-core/pom.xml
  pom.xml
Labels: TypeEnhancement

#5147 database changelog history record-keeping (DAT-16178)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/main/java/liquibase/integration/commandline/VersionUtils.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDbclHistoryMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDropAll.java
  liquibase-snowflake/src/main/java/liquibase/database/core/SnowflakeDatabase.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/ClobTypeSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
  liquibase-snowflake/src/test/java/liquibase/datatype/ClobTypeSnowflakeTest.java
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeLogSyncListener.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ChangeLogSyncVisitor.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/UpdateVisitor.java
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/command/CommandFailedException.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/ChangelogSyncCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/MarkNextChangesetRanCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/LiquibaseTableNames.java
  liquibase-standard/src/main/java/liquibase/database/LiquibaseTableNamesFactory.java
  liquibase-standard/src/main/java/liquibase/database/StandardLiquibaseTableNames.java
  liquibase-standard/src/main/java/liquibase/database/TempObjectQuotingStrategy.java
  liquibase-standard/src/main/java/liquibase/database/core/DB2Database.java
  liquibase-standard/src/main/java/liquibase/database/core/DatabaseUtils.java
  liquibase-standard/src/main/java/liquibase/database/core/H2Database.java
  liquibase-standard/src/main/java/liquibase/database/core/HsqlDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MariaDBDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/OracleDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
  liquibase-standard/src/main/java/liquibase/database/core/SQLiteDatabase.java
  liquibase-standard/src/main/java/liquibase/exception/ExitCodeException.java
  liquibase-standard/src/main/java/liquibase/exception/UnexpectedLiquibaseException.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/ChangelogJdbcMdcListener.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/MdcKey.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/MdcManager.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/NoOpMdcManager.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java
  liquibase-standard/src/main/java/liquibase/util/ExceptionUtil.java
  liquibase-standard/src/main/java/liquibase/util/HelpUtil.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
  liquibase-standard/src/main/java/liquibase/util/ValueHandlerUtil.java
  liquibase-standard/src/test/groovy/liquibase/ScopeTest.groovy
Labels: TypeEnhancement

#5649 Add CustomChangeChecksum interface
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeChecksum.java
  liquibase-standard/src/main/java/liquibase/change/custom/CustomChangeWrapper.java
  liquibase-standard/src/test/groovy/liquibase/change/custom/CustomChangeWrapperTest.groovy
  liquibase-standard/src/test/java/liquibase/change/custom/ExampleCustomSqlChangeWithChecksum.java
Labels: TypeEnhancement

#5686 add ignore property to includeAll XSD (DAT-14921)
  liquibase-integration-tests/src/test/resources/changelogs/common/includerelative/pathinclude1.ignored.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/update.test.groovy
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
Labels: TypeBug

#5696 use HelpUtil where possible (DAT-16569)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java
Labels: skipReleaseNotes

#5695 Handle empty or null schema for CreateView with replace option DAT-16446
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateViewGenerator.java
Labels: TypeBug

#5630 DAT-16798: Add new parameters to rollback report
  liquibase-standard/src/main/java/liquibase/changelog/visitor/DefaultChangeExecListener.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/AbstractRollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/RollbackCountCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/RollbackToDateCommandStep.java
  liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/ExceptionDetails.java
  liquibase-standard/src/main/java/liquibase/report/RollbackReportParameters.java
  liquibase-standard/src/main/java/liquibase/report/UpdateReportParameters.java
Labels: TypeEnhancement

#5692 Add force option to dropAll DAT-16418
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/dropAll.test.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/command/core/DropAllCommandStep.java
Labels: TypeEnhancement

#5707 [DAT-16135] add new scope flag for modifyChangeSet flow
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug

#5737 Fix/released published
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5739 fix: we don't have maven wrapper here
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#5728 automatically unroll Spock tests
  pom.xml
Labels: TypeTest

#5705 upgrade groovy, spock and mockito to later versions (DAT-10403)
  liquibase-extension-testing/pom.xml
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotH2IntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotMSSQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcSnapshotSerializerIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
  liquibase-standard/src/main/java/liquibase/sql/visitor/AppendSqlIfNotPresentVisitor.java
  liquibase-standard/src/test/groovy/liquibase/change/ChangeDefinitionTest.groovy
  liquibase-standard/src/test/groovy/liquibase/servicelocator/StandardServiceLocatorTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/FilenameUtilTest.groovy
  liquibase-standard/src/test/java/liquibase/database/AbstractJdbcDatabaseTest.java
  liquibase-standard/src/test/java/liquibase/database/core/MSSQLDatabaseTest.java
  pom.xml
Labels: TypeTest

#5744 Revert "automatically unroll Spock tests"
  pom.xml
Labels: skipReleaseNotes
