Repository liquibase/liquibase, pull requests merged in 2025-07, with the labels that each got.

#7085 fix: do not snapshot index type for cockroach DB as indexes behave different on this database and we don't know wher eto find it.
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug

#7091 chore: update changelog for version 4.33.0 release with notable changes and enhancements + XSD file
  changelog.txt
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.33.xsd
Labels: skipReleaseNotes

#7109 chore: remove liquibase-commercial references and dependencies from project
  .github/util/re-version.sh
  .github/workflows/README.md
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/fossa.yml
  .github/workflows/release-published.yml
  .github/workflows/run-functional-tests.yml
  .github/workflows/run-pro-build-and-test.yml
  .github/workflows/run-tests.yml
  .github/workflows/weekly-integration-tests.yml
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-dist/expected-distribution-contents-minimal.txt
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/licenses/commercial/FDHUT.txt
  liquibase-dist/src/main/archive/licenses/commercial/Liquibase Pro EULA Software License Subscription and Support Agreement.txt
  liquibase-dist/src/main/archive/licenses/commercial/README.txt
  liquibase-dist/src/main/archive/licenses/commercial/apache-2.0.txt
  liquibase-dist/src/main/archive/licenses/commercial/bsd-3-clause.txt
  liquibase-dist/src/main/archive/licenses/commercial/mit.txt
  liquibase-dist/src/main/assembly/assembly-bin-pro-minimal.xml
  liquibase-dist/src/main/assembly/assembly-bin-pro.xml
  liquibase-dist/src/main/assembly/assembly-bin.xml
  liquibase-dist/src/main/assembly/component-additional-deps.xml
  liquibase-dist/src/main/assembly/component-minimal-deps.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/checksum-changelog-tag.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/checksum-changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/common/rows-affected.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/checksum/dbms-filter-changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/rollback.different.contexts.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/rollback.sql.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/simple.changelog.with.id.xml
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/sql.change.dbms.filtered.should.not.be.deployed.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/init/example-changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/testBlob.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/testFkPkDependencies.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/rollback/rollback-to-tag-changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/update/createProcedureReplaceIfExists.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/update/showSummaryWithExecuteCommand.xml
  liquibase-integration-tests/src/test/resources/changelogs/sequenceExists-h2.xml
  liquibase-integration-tests/src/test/resources/changelogs/threading/changelog-1.xml
  liquibase-integration-tests/src/test/resources/changelogs/uniqueConstraint-mysql.xml
  liquibase-integration-tests/src/test/resources/changelogs/uniqueConstraint-postgres.xml
  liquibase-integration-tests/src/test/resources/changelogs/uniqueConstraint.xml
  liquibase-maven-plugin/pom.xml
  liquibase-maven-plugin/src/main/maven/release.pom.xml
  liquibase-standard/src/main/resources/liquibase/examples/xml/blank-changelog.xml
  liquibase-standard/src/main/resources/liquibase/examples/xml/example-changelog.xml
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
  liquibase-standard/src/test/resources/liquibase/registered-changelog.xml
  liquibase-standard/src/test/resources/liquibase/test-changelog-clob-types.xml
  liquibase-standard/src/test/resources/liquibase/test-changelog-empty.xml
  liquibase-standard/src/test/resources/liquibase/test-changelog-fast-check-to-not-deploy.xml
  liquibase-standard/src/test/resources/liquibase/test-changelog-fast-check.xml
  liquibase-standard/src/test/resources/liquibase/test-changelog.xml
  pom.xml
Labels: TypeEnhancement

#7110 chore: remove database drivers from distribution
  liquibase-dist/expected-distribution-contents.txt
  liquibase-dist/pom.xml
  liquibase-dist/src/main/archive/licenses/oss/README.txt
  liquibase-dist/src/main/archive/licenses/oss/bsd-2-clause.txt
  liquibase-dist/src/main/archive/licenses/oss/bsd-3-clause.txt
  liquibase-dist/src/main/archive/licenses/oss/cddl1.1.txt
  liquibase-dist/src/main/archive/licenses/oss/edl-1.0.txt
  liquibase-dist/src/main/archive/licenses/oss/futc.txt
  liquibase-dist/src/main/archive/licenses/oss/ipla.txt
  liquibase-dist/src/main/archive/licenses/oss/lgpl-2.1.txt
  liquibase-dist/src/main/archive/licenses/oss/lgpl-3.0.txt
  liquibase-dist/src/main/archive/licenses/oss/mit.txt
  liquibase-dist/src/main/assembly/component-additional-deps.xml
  liquibase-dist/src/main/assembly/component-minimal-deps.xml
Labels: TypeEnhancement

#7117 Add Spring Framework 6.x to dependabot ignore list
  .github/dependabot.yml
Labels: sdou

#7119 Fix dependabot.yml version syntax error
  .github/dependabot.yml
Labels: sdou

#7079 feat: add logic to exclude resources from liquibaseHomeUri/internal in resource processing for includeAll
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug

#7101 fix: prevent rawDateValue from being used for checksum calculations
  liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java
Labels: TypeBug, manuallyTested

#7126 fix: exclude H2 updates in dependabot config due to Java 11 requirement
  .github/dependabot.yml
Labels: skipReleaseNotes

#7118 Honor strip comments flag passed in scope in executeSql command DAT-20417
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
Labels: TypeEnhancement

#7141 Rollback OpenCSV version to 5.10 and address CSV loading issue
  liquibase-dist/pom.xml
  liquibase-standard/pom.xml
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.with.blank.line.csv
  pom.xml
Labels: TypeBug

#6920 fix: Change the rename column query for mysql v8 and later using rename column to
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
  liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameColumn/mariadb.sql
  liquibase-standard/src/test/resources/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/renameColumn/mysql.sql
Labels: TypeBug
