Repository liquibase/liquibase, pull requests merged in 2025-02, with the labels that each got.

#6675 recursively check for overrides of the override command step (DAT-19485)
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
Labels: skipReleaseNotes

#6640 Make sure original SQL statement is logged DAT-18763
  liquibase-standard/src/main/java/liquibase/executor/AbstractExecutor.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: TypeBug, AI Generated Code, runFunctional&HarnessTests

#6689 Only set fetch size for Oracle database
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: TypeBug, runFunctional&HarnessTests, build&TestPro

#6682 ✨ feat: DAT-19341:publish_assets_to_internal_nexus repo.liquibase.net
  .github/workflows/release-published.yml
Labels: TypeEnhancement, skipReleaseNotes

#6636 Added option to skip referenced objects during diff DAT-19220
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diff.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DiffArgumentsCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/util/ObjectUtil.java
Labels: TypeEnhancement

#6698 🔧 DAT-19341: publish oss released assets to s3
  .github/workflows/release-published.yml
Labels: TypeEnhancement, skipReleaseNotes

#6686 Fixes #6685 Performance issue of v4.30.0
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeBug, runFunctional&HarnessTests, build&TestPro

#6703 DAT-19476: generate minimal tar.gz and zip for OSS
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6714 🔧 DAT-19574: git checkout a specific branch from input parameter
  .github/workflows/build-extension-jars.yml
Labels: skipReleaseNotes

#6712 fix filename that was incorrect generated during 4.31.0
  liquibase-integration-tests/src/test/groovy/liquibase/changeType/ChangeLogIncludeTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/changelogs/changeType/logicalfilepath/changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/changeType/logicalfilepath/included.xml
  liquibase-standard/src/main/java/liquibase/changelog/AbstractChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/changelog/visitor/ValidatingVisitor.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/UpdateChangeSetFilenameGenerator.java
  liquibase-standard/src/main/java/liquibase/statement/core/UpdateChangeSetFilenameStatement.java
  liquibase-standard/src/main/java/liquibase/util/ValidatingVisitorUtil.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Labels: TypeBug

#6719 ✨ Add matching branch logic to workflow for dynamic branch handling
  .github/workflows/build-extension-jars.yml
Labels: TypeEnhancement, skipReleaseNotes

#6721 🔧 Fix syntax for branch comparison in workflow script
  .github/workflows/build-extension-jars.yml
Labels: skipReleaseNotes

#6713 remove recursive checking for multiple overrides of command steps (DAT-17162)
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
Labels: skipReleaseNotes

#6722 🔧 Refactor matching branch logic in workflow for PRO repo
  .github/workflows/build-extension-jars.yml
Labels: skipReleaseNotes

#6659 fix(postgres): DEFERRABLE keyword must appear after USING INDEX TABLE SPACE clause
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddUniqueConstraintGenerator.java
  liquibase-standard/src/test/groovy/liquibase/sqlgenerator/core/AddUniqueConstraintGeneratorAllVariantsTest.groovy
Labels: TypeBug, manuallyTested

#6697 Add reserved words for MySQL 8.0
  liquibase-standard/src/main/java/liquibase/database/core/MySQLDatabase.java
  liquibase-standard/src/test/java/liquibase/database/core/MySQLDatabaseTest.java
Labels: TypeEnhancement

#6723 fix: release build
  .github/workflows/build-extension-jars.yml
Labels: skipReleaseNotes

#6702 Warn on duplicate jars when added via classpath (DAT-19275)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseLauncher.java
Labels: TypeEnhancement

#6718 switch to new mysql driver (DAT-19393)
  liquibase-dist/pom.xml
  pom.xml
Labels: TypeEnhancement

#6741 🔧 Fix/generate-oss-pro-sbom-reports
  .github/workflows/release-published.yml
Labels: sdou

#6663 Close ResultSet to prevent leaking it
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
Labels: TypeBug, runFunctional&HarnessTests, build&TestPro

#6692 Snapshot all configuration values for Oracle sequences
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
Labels: TypeBug, runFunctional&HarnessTests, manuallyTested, build&TestPro

#6706 Only report rows affected for DML statements
  liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/resources/changelogs/common/rows-affected.xml
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/main/java/liquibase/executor/jvm/JdbcExecutor.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement

#6560 Add DiffOutputControl support for specifying a data directory argument
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogH2IntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/loaDataTestData.csv
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/loadData.test.changelog.xml
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/diffChangelog.test.groovy
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DiffOutputControlCommandStep.java
  liquibase-standard/src/main/java/liquibase/diff/output/DiffOutputControl.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/ChangeGeneratorFactory.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeBug, DocNeeded, build&TestPro

#6695 Fix BIT column type handling for Postgres
  liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
  liquibase-standard/src/test/groovy/liquibase/datatype/core/BooleanTypeTest.groovy
Labels: TypeBug, PRAssociated, manuallyTested

#6742 support default values for time, datetime, and timestamp types in Snowflake (DAT-17524)
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-snowflake/src/main/java/liquibase/datatype/core/DateTypeSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/TimeTypeSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/TimestampNTZTypeSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/TimestampTypeSnowflake.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType
  liquibase-snowflake/src/test/java/liquibase/datatype/TimestampNTZTypeTest.java
Labels: TypeEnhancement

#6761 Revert "Fix BIT column type handling for Postgres"
  liquibase-standard/src/main/java/liquibase/datatype/core/BooleanType.java
  liquibase-standard/src/test/groovy/liquibase/datatype/DataTypeFactoryTest.groovy
  liquibase-standard/src/test/groovy/liquibase/datatype/core/BooleanTypeTest.groovy
Labels: skipReleaseNotes

#6750 DAT-18499 Log level changed when specifying driver on the CLI
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
Labels: TypeBug

#6727 improve/fix snowflake view generation SQL
  liquibase-snowflake/src/main/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorSnowflake.java
  liquibase-snowflake/src/test/java/liquibase/sqlgenerator/core/GetViewDefinitionGeneratorSnowflakeTest.java
Labels: TypeBug, manuallyTested

#6770 Revert weld-se-core upgrade
  liquibase-cdi-jakarta/pom.xml
Labels: TypeBug

#6674 Fix concurrency issues in multithread environments
  liquibase-integration-tests/src/test/java/liquibase/threading/LiquibaseTest.java
  liquibase-integration-tests/src/test/java/liquibase/threading/LiquibaseThreadingTest.java
  liquibase-integration-tests/src/test/java/liquibase/threading/MemoryDatabase.java
  liquibase-integration-tests/src/test/resources/changelogs/threading/changelog-1.xml
  liquibase-integration-tests/src/test/resources/changelogs/threading/changelog.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
Labels: TypeBug, manuallyTested

#6679 Improves MDC logging by database-specific command formatting
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/statement/SqlStatement.java
Labels: TypeEnhancement

#6780 Added method to return the original path for a Resource
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogH2IntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java
Labels: TypeEnhancement

#6752 Fix LoadData issues for CLOB Values Containing Invalid File Path Characters
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.for.clob.types.csv
Labels: TypeBug, runFunctional&HarnessTests

#6596 Make the logChannels property work DAT-19296
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/logging/core/JavaLogService.java
Labels: TypeBug
