Repository liquibase/liquibase, pull requests merged in 2025-09, with the labels that each got.

#7187 Fixed: #7186 - Liquibase creates too short VARCHAR and CHAR fields on MS SQL databases using multi-byte encodings, effectively leading to data truncation eventually
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
  liquibase-standard/src/main/java/liquibase/datatype/core/CharType.java
  liquibase-standard/src/main/java/liquibase/datatype/core/VarcharType.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations
Labels: TypeEnhancement, TypeBug

#7216 Deprecate Java 8/11
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
  .github/workflows/run-tests.yml
  liquibase-dist/src/main/archive/liquibase
  liquibase-dist/src/main/archive/liquibase.bat
  liquibase-maven-plugin/pom.xml
  liquibase-standard/src/main/java/liquibase/resource/ZipResourceAccessor.java
  pom.xml
Labels: TypeEnhancement, TypeTechDebt

#7257 INT-1416: Updated handling of complex UnwrappedLiquibaseSerializables
  liquibase-standard/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
Labels: TypeBug, runFunctional&HarnessTests

#7292 Remove update-docs-oss-pro-version job
  .github/workflows/release-published.yml
Labels: sdou

#7282 Fix OSS license validation to prevent NPEs and silent failures
  liquibase-standard/src/main/java/liquibase/command/core/DiffCommandStep.java
  liquibase-standard/src/main/java/liquibase/license/LicenseServiceUtils.java
  liquibase-standard/src/main/java/liquibase/license/OSSLicenseService.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/formattedsql/InvalidFormattedSqlPatternsForOssUtil.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.license.LicenseService
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
  liquibase-standard/src/test/java/liquibase/license/OSSLicenseServiceTest.java
Labels: TypeBug

#7300 Updated changelog.txt
  changelog.txt
Labels: skipReleaseNotes

#7303 Updated the links
  changelog.txt
Labels: AI Generated Code
