Repository liquibase/liquibase, pull requests merged in 2025-01, with the labels that each got.

#6597 Handle absence or older version of checks JAR DAT-19289
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChecksMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksRunMojo.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseChecksShowMojo.java
Labels: TypeEnhancement, runFunctional&HarnessTests, build&TestPro

#6616 🛠️ DAT-19292: fix Attach Artifacts to Draft Release failures
  .github/util/re-version.sh
Labels: skipReleaseNotes

#6540 Fix null value handling when loading resources
  liquibase-standard/src/main/java/liquibase/change/core/LoadDataChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/LoadDataChangeTest.groovy
  liquibase-standard/src/test/resources/liquibase/change/core/sample.data.for.clob.types.csv
Labels: TypeBug, runFunctional&HarnessTests, manuallyTested, build&TestPro

#6617 feat(DAT-19258): should only verify test count if base branch is master
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6623 fix: test counts in master
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6624 chore: rollback test count changes as they are failing for master
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6621 DAT-19082: Fix issue with losing changed datatype attributes when one datatype is an int and the other is not
  liquibase-standard/src/main/java/liquibase/diff/compare/core/ColumnComparator.java
Labels: TypeBug

#6628 liquibase-maven-plugin: Allow `null` arguments to `ConfiguredValueModifierFactory.override(String)`
  liquibase-standard/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java
Labels: TypeBug

#6629 undo UUID-ing of deployment ID (DAT-19367)
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/execution-parameter.xml
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateDatabaseChangeLogTableGeneratorSybase.java
Labels: TypeEnhancement

#6626 DAT-18331 PRO: integrate checks extension into tarball/zip, not mac os dmg installer
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
Labels: sdou

#6630 Handle @ symbol when executing PostgreSQL SET SEARCH_PATH
  liquibase-extension-testing/.gitignore
  liquibase-standard/src/main/java/liquibase/database/core/DatabaseUtils.java
Labels: TypeEnhancement

#6637 chore: FILES FOR 4.31.0 RELEASE
  changelog.txt
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.31.xsd
Labels: skipReleaseNotes

#6642 DAT-19398 DevOps :: Fix Liquibase Checks versioning in the tarball to match the Liquibase Checks repository
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
Labels: sdou, skipReleaseNotes, AI Generated Code

#6635 🔧 fix cleanup branch builds
  .github/workflows/cleanup-branch-builds.yml
  .github/workflows/cleanup-master-builds.yml
Labels: TypeEnhancement, skipReleaseNotes

#6651 fix: add missing name tag to poms
  liquibase-cdi-jakarta/pom.xml
  liquibase-cdi/pom.xml
Labels: TypeBug

#6652 FIx tag for release-extensions.yml file
  .github/workflows/release-extensions.yml
Labels: skipReleaseNotes

#6653 fix: move name from maven file to pom.xml
  liquibase-cdi-jakarta/pom.xml
  liquibase-cdi-jakarta/src/main/maven/liquibase-deployment-pom.xslt
  liquibase-cdi/pom.xml
  liquibase-cdi/src/main/maven/liquibase-deployment-pom.xslt
Labels: skipReleaseNotes

#6654 🔧 DAT-19419: previous_version was returning the wrong value
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6604 OSS PR template updated with required test actions
  .github/pull_request_template.md
Labels: TypeEnhancement

#6552 Fix a typo in comment
  liquibase-standard/src/main/java/liquibase/datatype/core/DateTimeType.java
Labels: TypeBug

#6587 Don't add minValue change twice
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangedSequenceChangeGenerator.java
Labels: TypeBug

#6657 DAT-18516 Set correct version in pom.properties file for liquibase-commercial.jar
  .github/util/re-version.sh
Labels: sdou

#6658 Code review for extensions after 4.31.0 release
  liquibase-standard/src/main/java/liquibase/exception/PreconditionFailedException.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RawParameterizedSqlGenerator.java
Labels: skipReleaseNotes, runFunctional&HarnessTests, build&TestPro

#6665 🔧 DAT-19374
  .github/workflows/create-release.yml
  .github/workflows/dry-run-release.yml
Labels: skipReleaseNotes

#6645 refactoring and fixes associated with DBCL-history changes (DAT-16488)
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/serializer/core/yaml/YamlSerializer.java
  liquibase-standard/src/test/groovy/liquibase/serializer/core/yaml/YamlSerializerTest.groovy
Labels: skipReleaseNotes

#6671 fix flaky test
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogPostgresqlIntegrationTest.groovy
Labels: skipReleaseNotes

#6668 DAT-18993 DevOps :: Populate the triggered job link in a step
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#6676 🔧 DAT-19341: Add check for existing OSS release tag to prevent duplicate artifacts
  .github/workflows/create-release.yml
Labels: TypeEnhancement, skipReleaseNotes

#6622 DAT-19285: Enhance xml parsing exception to mention custom change types
  liquibase-standard/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java
Labels: TypeEnhancement

#6649 fix mysql uuid load data issue
  liquibase-integration-tests/src/test/java/liquibase/dbtest/mysql/MySQLIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/datafiles/uuid-data.csv
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/uuid.changelog.xml
  liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
Labels: TypeBug, manuallyTested

#6664 Don't ignore logicalFilePath when including changelogs
  liquibase-integration-tests/src/test/groovy/liquibase/changeType/ChangeLogIncludeTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-level3.xml
  liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-mid.xml
  liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-pages.xml
  liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-teams.xml
  liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog-users.xml
  liquibase-integration-tests/src/test/resources/changelogs/changeType/include/changelog.xml
  liquibase-standard/src/main/java/liquibase/changelog/DatabaseChangeLog.java
Labels: TypeBug, manuallyTested, build&TestPro
