Repository liquibase/liquibase, pull requests merged in 2025-04, with the labels that each got.

#6855 add timeout to license tracking HTTP request (DAT-19866)
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java
Labels: skipReleaseNotes

#6869 Test fixes for path issue
  liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/fkep.test.changelog.xml
Labels: TypeBug

#6868 remove setup-python and localstack infra code that isn't used
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6859 improve parameter stripping logic for LLU (DAT-19793)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/test/groovy/liquibase/command/core/helpers/DbUrlConnectionCommandStepTest.groovy
Labels: skipReleaseNotes

#6865 add licenseUtilityEnabled flag to maven plugin (DAT-19825)
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java
Labels: skipReleaseNotes

#6883 fix concurrent modification error in BufferedLogService
  liquibase-standard/src/main/java/liquibase/logging/core/BufferedLogService.java
Labels: skipReleaseNotes

#6835 feat: new tagDatabase parameter to keep tag on rollback
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/RollbackIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/common/test.tag.not.removed.by.rollback.xml
  liquibase-standard/src/main/java/liquibase/change/core/TagDatabaseChange.java
  liquibase-standard/src/main/java/liquibase/changelog/filter/AfterTagChangeSetFilter.java
  liquibase-standard/src/main/java/liquibase/command/core/RollbackCommandStep.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/java/liquibase/changelog/filter/AfterTagChangeSetFilterTest.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: TypeEnhancement, DocNeeded, manuallyTested, XSD Change

#6879 IO-2503 Self Hosted Runner :: minimal docker container
  .github/workflows/release-published.yml
Labels: sdou, skipReleaseNotes

#6846 change default value for license tracking URL (DAT-19874)
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java
Labels: skipReleaseNotes

#6873 remove threads for analytics timeouts, use native API instead (DAT-19744)
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java
Labels: TypeEnhancement

#6807 [DAT-19654] made fields in AbstractFormattedChangeLogParser constansts to reuse in util classes
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
Labels: TypeEnhancement

#6867 fix: resource path resolution inside JAR files
  liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java
  liquibase-standard/src/test/groovy/liquibase/resource/URIResourceAccessorTest.groovy
Labels: TypeBug, build&TestPro

#6872 fix: change String[] to List<String> in COMMAND_DEFINITIONS cache
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/test/groovy/liquibase/command/CommandFactoryTest.groovy
Labels: TypeBug

#6893 hide license tracking args (DAT-20001)
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java
Labels: skipReleaseNotes

#6886 remove unnecessary calls to dropAll in tests (DAT-19865)
  liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/spock/LiquibaseIntegrationMethodInterceptor.java
  liquibase-integration-tests/src/test/groovy/liquibase/LiquibaseTestIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/ChangelogSyncIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandWithIncludeAll.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ClearCheckSumsIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/DbDocPostgresIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogDb2IntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMySQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogPostgresqlIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/MssqlIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/RollbackIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpdateTestingRollbackCommandsIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/UpgradeChecksumVersionIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/diff/DiffIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/update/UpdateIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/command/util/CommandUtil.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/IndexWithDescendingColumnSnapshotIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/snapshot/JdbcDatabaseSnapshotMSSQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/util/ShowSummaryUtilCommandTest.groovy
Labels: skipReleaseNotes

#6875 Fix Oracle regression from splitStatements:false change DAT-19983
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
Labels: TypeBug

#6866 feat: add support for default value sequence next to hsqldb
  liquibase-integration-tests/src/test/resources/changelogs/common/common.tests.changelog.xml
  liquibase-standard/src/main/java/liquibase/database/core/HsqlDatabase.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/AddDefaultValueGeneratorHsqldb.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertGenerator.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Labels: TypeEnhancement, manuallyTested, build&TestPro

#6798 Database support custom method `escapeForLike`
  liquibase-standard/src/main/java/liquibase/database/Database.java
  liquibase-standard/src/main/java/liquibase/database/core/SQLiteDatabase.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeEnhancement

#6903 DAT-19917: Refactor analytics setup to prepare for pro analytics
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsFactory.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/NoOpAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/analytics/configuration/AnalyticsArgs.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/test/groovy/liquibase/analytics/AnalyticsArgsTest.groovy
Labels: skipReleaseNotes

#6838 Upon Evaluation of changeLogPropertyDefinied precondition also include local properties of nested changesets.
  liquibase-standard/src/main/java/liquibase/changelog/ChangeLogParameters.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ChangeLogPropertyDefinedPrecondition.java
  liquibase-standard/src/test/groovy/liquibase/precondition/core/ChangeLogPropertyDefinedPreconditionTest.groovy
Labels: TypeBug

#6905 feat: Rename misleading update methods in Liquibase class
  liquibase-integration-tests/src/test/groovy/liquibase/command/UpdateCommandsIntegrationTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseUpdateSQL.java
  liquibase-standard/src/main/java/liquibase/Liquibase.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeEnhancement

#6899 feat: Improve Command Definition Internal Status Inheritance
  liquibase-standard/src/main/java/liquibase/command/CommandFactory.java
  liquibase-standard/src/main/java/liquibase/command/CommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractArgumentCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractHelperCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java
  liquibase-standard/src/main/java/liquibase/util/HelpUtil.java
Labels: TypeEnhancement, runFunctional&HarnessTests

#6910 CommandTests: add assertEquals method (DAT-18275)
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: skipReleaseNotes

#6906 feat: Override isInternal method to return false in InitCopyCommandStep
  liquibase-standard/src/main/java/liquibase/command/core/init/InitCopyCommandStep.java
Labels: skipReleaseNotes

#6912 replace username and password in host part of JDBC URL with empty string (DAT-20016)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/jvm/ConnectionPatterns.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnectionPatterns.java
  liquibase-standard/src/test/groovy/liquibase/database/jvm/JdbcConnectionTest.groovy
Labels: skipReleaseNotes
