Repository liquibase/liquibase, pull requests merged in 2025-03, with the labels that each got.

#6764 Do not include size on user defined types (DAT-19150)
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/user.defined.types.sql
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
Labels: TypeBug

#6789 🔧 Update GitHub Actions workflow to use Ubuntu 22.04
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6252 docs: add issue triage instructions to repo
  ISSUE_TRIAGE.md
Labels: skipReleaseNotes

#6775 refactor InsertGenerator so that it can be overridden more easily (DAT-19678)
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/InsertGenerator.java
Labels: skipReleaseNotes

#6774 Use hasIgnoreNested method for all database preconditions
  liquibase-integration-tests/src/test/groovy/liquibase/diffchangelog/DiffChangelogIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/precondition/core/ColumnExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/IndexExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/PrimaryKeyExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/SequenceExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/TableExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/UniqueConstraintExistsPrecondition.java
  liquibase-standard/src/main/java/liquibase/precondition/core/ViewExistsPrecondition.java
Labels: TypeEnhancement

#6744 6743: support the Arabic character "Kasra"
  liquibase-standard/src/main/javacc/liquibase/util/grammar/SimpleSqlGrammar.jj
Labels: TypeEnhancement

#6781 gzip log files if log-file parameter ends in .gz (DAT-18971)
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/integration/commandline/LiquibaseCommandLineConfiguration.java
Labels: TypeEnhancement

#6753 fix liquibase-cli dependencies when deploying to Maven Central
  liquibase-cli/pom.xml
  liquibase-cli/src/main/java/liquibase/integration/commandline/CommandLineArgumentValueProvider.java
Labels: TypeBug

#6745 Fix foreignKeyConstraintExists precondition when constraint already exists in the DB
  liquibase-integration-tests/src/test/groovy/MySQLTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/MssqlTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/OracleTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/PostgresTest.groovy
  liquibase-integration-tests/src/test/java/liquibase/dbtest/AbstractIntegrationTest.java
  liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/fkep.test.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/fkep_test.sql
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/fkep.test.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/fkep_test.sql
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/fkep.test.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/sql/fkep_test.sql
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/fkep.test.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/fkep_test.sql
  liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java
Labels: TypeBug

#6787 For SQL Server, sync up the backing index for PK and UC to the one that is auto-generated DAT-19267
  liquibase-standard/src/main/java/liquibase/command/core/SnapshotCommandStep.java
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java
Labels: TypeBug

#6802 Fix snapshot for MSSQL decimal sequences (DAT-19504)
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogMSSQLIntegrationTest.groovy
  liquibase-integration-tests/src/test/resources/changelogs/mssql/issues/decimal.sequence.sql
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/SequenceSnapshotGenerator.java
Labels: TypeBug, DBMSSQLServer, runFunctional&HarnessTests

#6806 DAT - 19691 :: Code refactorings to fix sonar issues
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/LiquibaseDbclHistoryMojo.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/BinaryTypeSnowflake.java
  liquibase-snowflake/src/main/java/liquibase/datatype/core/DoubleDataTypeSnowflake.java
  liquibase-standard/src/main/java/liquibase/integration/commandline/Main.java
Labels: TypeEnhancement, TypeBug, runFunctional&HarnessTests, build&TestPro

#6801 reduce number of API calls for analytics by caching events (DAT-19789)
  liquibase-integration-tests/src/test/groovy/liquibase/analytics/AnalyticsIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsBatch.java
  liquibase-standard/src/main/java/liquibase/analytics/AnalyticsTrackEvent.java
  liquibase-standard/src/main/java/liquibase/analytics/Event.java
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/integration/spring/SpringLiquibase.java
Labels: TypeEnhancement

#6785 send license usage tracking information to license utility (DAT-17920)
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/Scope.java
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
  liquibase-standard/src/main/java/liquibase/command/CommandScope.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/database/DatabaseConnection.java
  liquibase-standard/src/main/java/liquibase/database/jvm/JdbcConnection.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrack.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackList.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingFactory.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingListener.java
  liquibase-standard/src/main/resources/META-INF/services/liquibase.configuration.AutoloadedConfigurations
Labels: skipReleaseNotes

#6795 readd headers to *-sql commands (DAT-18306)
  liquibase-standard/src/main/java/liquibase/command/core/MarkNextChangesetRanSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateCountSqlCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/UpdateToTagSqlCommandStep.java
Labels: TypeBug

#6824 include additional info in LicenseInfo (DAT-19766)
  liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java
Labels: skipReleaseNotes

#6829 change parameter to tracking-id (DAT-19783)
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/license/LicenseTrack.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingArgs.java
Labels: skipReleaseNotes

#6694 Show message and exit if user attempts to use Azure without extension DAT-19430
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
  liquibase-standard/src/main/java/liquibase/Scope.java
Labels: TypeEnhancement

#6832 fix: during sonar refactoring the wrong parameter was used here - fixing it.
  liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java
Labels: skipReleaseNotes, runFunctional&HarnessTests

#6825 fix multiline select statements in execute-sql (DAT-19722)
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/ExecuteSqlPostgresIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/command/core/ExecuteSqlCommandStep.java
Labels: TypeBug

#6826 fix #5197: Ensure contexts from properties object are not ignored
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeBug, manuallyTested, build&TestPro

#6830 fix: exclude duplicated dependencies provided by opencsv
  liquibase-dist/pom.xml
Labels: TypeBug, build&TestPro

#6755 Fix handling of PostgreSQL uppercase catalog names after v42.7.5 driver changes
  liquibase-dist/pom.xml
  liquibase-standard/src/main/java/liquibase/database/core/PostgresDatabase.java
  pom.xml
Labels: TypeBug, build&TestPro

#5775 feat: improve snapshot generation for NOSQL databases
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/JdbcSnapshotGenerator.java
  liquibase-standard/src/test/groovy/liquibase/snapshot/SnapshotGeneratorChainTest.groovy
Labels: TypeEnhancement, manuallyTested

#6796 Add static method to generate tag dbcl record (DAT-19432)
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
  liquibase-standard/src/main/java/liquibase/command/core/TagCommandStep.java
Labels: skipReleaseNotes

#6800 Pass CHANGELOG_ARG to scope of changelogSync command
  liquibase-standard/src/main/java/liquibase/Liquibase.java
Labels: TypeBug

#6808 Date with timezone formats added.
  liquibase-integration-tests/src/test/resources/changelogs/h2/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mssql/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/mysql/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/oracle/complete/root.changelog.xml
  liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml
  liquibase-standard/src/main/java/liquibase/util/ISODateFormat.java
  liquibase-standard/src/test/groovy/liquibase/util/ISODateFormatTest.groovy
Labels: TypeBug, manuallyTested

#6842 Fix regression issue from 6808
  liquibase-standard/src/main/java/liquibase/util/ISODateFormat.java
  liquibase-standard/src/test/groovy/liquibase/util/ISODateFormatTest.groovy
Labels: skipReleaseNotes, runFunctional&HarnessTests

#6847 fix: class should override replaces method
  liquibase-snowflake/src/main/java/liquibase/snapshot/jvm/SchemaSnapshotGeneratorSnowflake.java
Labels: skipReleaseNotes

#6848 improve license tracking error message (DAT-19864)
  liquibase-standard/src/main/java/liquibase/license/LicenseTrackingFactory.java
Labels: skipReleaseNotes

#6845 track issued date in LicenseInfo (DAT-19875)
  liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java
Labels: skipReleaseNotes

#6833 Default splitStatements to false for formatted SQL generation DAT-19702
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
  liquibase-standard/src/test/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializerTest.java
Labels: TypeBug
