Repository liquibase/liquibase, pull requests merged in 2025-06, with the labels that each got.

#6916 Added new argument to AbstractFormattedChangeLogParser.handleAdditionalLines method
  liquibase-standard/src/main/java/liquibase/executor/ExecutorService.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/report/ChangesetInfo.java
  liquibase-standard/src/main/java/liquibase/report/IndividualChangesetInfo.java
Labels: TypeEnhancement

#6947 DAT-20186 Update run-tests.yml
  .github/workflows/run-tests.yml
Labels: skipReleaseNotes

#6844 Exclude static fields from changelog serialization
  liquibase-standard/src/main/java/liquibase/serializer/ReflectionSerializer.java
  liquibase-standard/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
Labels: TypeBug, AI Generated Code

#6840 Comments field from CreateProcedure change renamed to 'comment'
  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java
  liquibase-standard/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy
  liquibase-standard/src/test/java/liquibase/serializer/core/xml/XMLChangeLogSerializerTest.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: TypeEnhancement, manuallyTested

#7024 DAT-20044 DevOps :: OSS sonatype service will reach end-of-life on June 30th, 2025
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#7031 Added property for disabling command tests at runtime
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: TypeEnhancement

#7037 Enhancement for #6827 - Error message updated when trying to parse an empty file
  liquibase-standard/src/main/java/liquibase/parser/core/sql/SqlChangeLogParser.java
  liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXParser.java
  liquibase-standard/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy
Labels: TypeEnhancement, skipReleaseNotes

#6995 feat(DEVX-12): Removal of liquibase-cdi and liquibase-cdi-jakarta modules
  .github/util/re-version.sh
  .github/workflows/build.yml
  .github/workflows/cleanup-branch-builds.yml
  .github/workflows/cleanup-master-builds.yml
  .github/workflows/release-published.yml
  .github/workflows/run-tests.yml
  liquibase-cdi-jakarta/pom.xml
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/CDIBootstrap.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/CDILiquibase.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/CDILiquibaseConfig.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/SchemesCDIConfigBuilder.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/SchemesTreeBuilder.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/annotations/Liquibase.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/annotations/LiquibaseSchema.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/annotations/LiquibaseType.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/exceptions/CyclicDependencyException.java
  liquibase-cdi-jakarta/src/main/java/liquibase/integration/jakarta/cdi/exceptions/DependencyNotFoundException.java
  liquibase-cdi-jakarta/src/main/maven/liquibase-deployment-pom.xslt
  liquibase-cdi-jakarta/src/main/resources/META-INF/beans.xml
  liquibase-cdi-jakarta/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
  liquibase-cdi-jakarta/src/main/resources/schema.template.xml
  liquibase-cdi-jakarta/src/test/groovy/README.txt
  liquibase-cdi-jakarta/src/test/java/liquibase/integration/jakarta/cdi/CDILiquibaseTest.java
  liquibase-cdi-jakarta/src/test/java/liquibase/integration/jakarta/cdi/CDITestProducer.java
  liquibase-cdi-jakarta/src/test/java/liquibase/integration/jakarta/cdi/SchemesCDIConfigBuilderTest.java
  liquibase-cdi-jakarta/src/test/java/liquibase/integration/jakarta/cdi/SchemesTreeBuilderTest.java
  liquibase-cdi-jakarta/src/test/resources/META-INF/beans.xml
  liquibase-cdi/pom.xml
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDIBootstrap.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibase.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/CDILiquibaseConfig.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesCDIConfigBuilder.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/SchemesTreeBuilder.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/Liquibase.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/LiquibaseSchema.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/annotations/LiquibaseType.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/exceptions/CyclicDependencyException.java
  liquibase-cdi/src/main/java/liquibase/integration/cdi/exceptions/DependencyNotFoundException.java
  liquibase-cdi/src/main/maven/liquibase-deployment-pom.xslt
  liquibase-cdi/src/main/resources/META-INF/beans.xml
  liquibase-cdi/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  liquibase-cdi/src/main/resources/schema.template.xml
  liquibase-cdi/src/test/groovy/README.txt
  liquibase-cdi/src/test/java/liquibase/integration/cdi/CDILiquibaseTest.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/CDITestProducer.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/SchemesCDIConfigBuilderTest.java
  liquibase-cdi/src/test/java/liquibase/integration/cdi/SchemesTreeBuilderTest.java
  liquibase-cdi/src/test/resources/META-INF/beans.xml
  pom.xml
Labels: TypeEnhancement

#7052 feat: Remove liquibase-cdi and liquibase-cdi-jakarta from release artifacts
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#7036 Complain and throw an exception when multiple header lines are found in a formatted SQL changelog DAT-20244
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeEnhancement

#7046 feat: add rawDateValue field to store unprocessed date input in ColumnConfig
  liquibase-standard/src/main/java/liquibase/change/ColumnConfig.java
  liquibase-standard/src/test/groovy/liquibase/change/ColumnConfigTest.groovy
Labels: TypeEnhancement

#7049 fix: resolve inconsistency in StandardLockService by ensuring table snapshot is validated before processing changes
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: TypeBug, runFunctional&HarnessTests

#7058 Skip running functional tests when a Dependabot PR is merged
  .github/workflows/build.yml
Labels: TypeEnhancement, github_actions

#7062 Fix issue in DBMS skip check that caused a regression
  liquibase-integration-tests/src/test/groovy/liquibase/util/ShowSummaryUtilCommandTest.groovy
  liquibase-standard/src/main/java/liquibase/changelog/ChangeSet.java
Labels: TypeBug

#7056 fix: update snapshot logic to handle null snapshot returns
  liquibase-standard/src/main/java/liquibase/snapshot/SnapshotGeneratorChain.java
Labels: TypeBug

#7063 do not count DBCL queries in rows affected message (DAT-20282)
  liquibase-standard/src/main/java/liquibase/changelog/StandardChangeLogHistoryService.java
Labels: TypeBug

#7071 Pass the database instance in scope when parsing the changelog DAT-20378
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
Labels: TypeBug

#6990 Add application name to JDBC properties for Snowflake
  liquibase-snowflake/src/main/java/liquibase/database/jvm/SnowflakeJdbcConnection.java
  liquibase-snowflake/src/main/resources/META-INF/services/liquibase.database.DatabaseConnection
Labels: TypeEnhancement
