Repository liquibase/liquibase, pull requests merged in 2025-05, with the labels that each got.

#6921 INT-1249: refactored StringSnapshotSerializerReadable to be able to extend expandable and skipped object types from Pro and Extensions.
  liquibase-standard/src/main/java/liquibase/serializer/core/string/StringSnapshotSerializerReadable.java
Labels: TypeEnhancement

#6930 DAT-20082: analytics: don't needlessly call isEnabled method when determining priority
  liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
Labels: TypeBug

#6932 make all command names public
  liquibase-standard/src/main/java/liquibase/command/core/CalculateChecksumCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/TagCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/TagExistsCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/AbstractDatabaseConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ChangeExecListenerCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DatabaseChangelogCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/PreCompareCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ReferenceDbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/command/core/helpers/ShowSummaryArgument.java
Labels: TypeBug

#6934 fix: Integration-Tests - Groovy - Wrong variable names
  liquibase-integration-tests/src/test/groovy/MySQLTest.groovy
  liquibase-integration-tests/src/test/groovy/liquibase/MssqlTest.groovy
Labels: TypeBug

#6889 fix toString exception when JDBC connection is closed (DAT-19849)
  liquibase-standard/src/main/java/liquibase/database/AbstractJdbcDatabase.java
Labels: TypeBug

#6945 Revert of junit-platform-suite to v1.11.4
  liquibase-extension-testing/pom.xml
Labels: TypeBug

#6946 Added property on CommandTests to allow skipping at runtime
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
Labels: TypeEnhancement

#6914 feat: Add getDescription method to provide source description
  liquibase-standard/src/main/java/liquibase/configuration/AbstractMapConfigurationValueProvider.java
Labels: skipReleaseNotes

#6939 DAT-20127 DevOps :: Audit and Harden Tokens used in Liquibot Automation
  .github/workflows/build-azure-uber-jar.yml
  .github/workflows/build-extension-jars.yml
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  .github/workflows/dry-run-release.yml
  .github/workflows/fossa.yml
  .github/workflows/release-published.yml
  .github/workflows/run-tests.yml
  .github/workflows/weekly-integration-tests.yml
Labels: sdou, skipReleaseNotes

#6937 Display the "Waiting for changelog lock" message to console as well as the log
  liquibase-standard/src/main/java/liquibase/lockservice/StandardLockService.java
Labels: TypeEnhancement

#6794 Added option to force schema attributes to be included if they are default
  liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy
  liquibase-standard/src/main/java/liquibase/GlobalConfiguration.java
  liquibase-standard/src/main/java/liquibase/structure/core/Schema.java
  liquibase-standard/src/test/groovy/liquibase/structure/core/SchemaTest.groovy
Labels: TypeEnhancement

#6901 feat: Add PostgreSQL Index Function Support via USING Clause
  liquibase-integration-tests/src/test/java/liquibase/dbtest/pgsql/PostgreSQLIntegrationTest.java
  liquibase-standard/src/main/java/liquibase/change/core/CreateIndexChange.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangedIndexChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/MissingIndexChangeGenerator.java
  liquibase-standard/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java
  liquibase-standard/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateIndexGenerator.java
  liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateIndexGeneratorPostgres.java
  liquibase-standard/src/main/java/liquibase/statement/core/CreateIndexStatement.java
  liquibase-standard/src/main/java/liquibase/structure/core/Index.java
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
  liquibase-standard/src/test/java/liquibase/sqlgenerator/core/CreateIndexGeneratorPostgresTest.java
  liquibase-standard/src/test/resources/liquibase/change/ChangeDefinitionTest.yaml
Labels: TypeEnhancement, build&TestPro, XSD Change

#6956 readd constructor removed in LLU merge (DAT-20238)
  liquibase-standard/src/main/java/liquibase/license/LicenseInfo.java
Labels: skipReleaseNotes

#6954 DAT-20211
  .github/workflows/build-extension-jars.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6957 4.32.0: Release prep
  changelog.txt
  liquibase-dist/src/main/install4j/liquibase.install4j
  liquibase-standard/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.32.xsd
Labels: skipReleaseNotes

#6962 Update changelog.txt
  changelog.txt
Labels: skipReleaseNotes

#6963 Update release notes
  changelog.txt
Labels: skipReleaseNotes, AI Generated Code

#6966 ♻️ (release-published.yml): update permissions to allow write access for issues and adjust GitHub App token permissions
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6968 ♻️ DAT-20252: add GitHub App token retrieval for access token
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6970 DAT-20252: use Github App Token
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6971 🔧 DAT-20252: get latest_version and previous_version for OSS
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#6953 Small test fixes for issues that I found in another ticket
  liquibase-integration-tests/src/test/resources/changelogs/h2/update/logicalFilePath.xml
  liquibase-standard/src/test/groovy/liquibase/changelog/ExpressionExpanderTest.groovy
Labels: TypeBug

#6974 Handle possible NPE in getPlug() method
  liquibase-standard/src/main/java/liquibase/executor/ExecutorService.java
Labels: TypeBug
