Repository liquibase/liquibase, pull requests merged in 2025-08, with the labels that each got.

#7167 Update CODEOWNERS for better maintainability
  .github/CODEOWNERS
Labels: skipReleaseNotes

#7158 Handle situation that occurs when generateChangeLog is run with diffTypes=data
  liquibase-integration-tests/src/test/groovy/liquibase/command/core/GenerateChangeLogPostgresqlIntegrationTest.groovy
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
Labels: TypeBug

#7168 Use missing objects instead of changed objects in test DAT-20536
  liquibase-standard/src/main/java/liquibase/command/core/GenerateChangelogCommandStep.java
Labels: TypeBug

#7144 Refactored to allow creation of a ChangelogPrintService for use by generateChangeLog and diffChangeLog operations
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/command/CommandTests.groovy
  liquibase-extension-testing/src/main/groovy/liquibase/extension/testing/setup/SetupCleanResources.groovy
  liquibase-standard/pom.xml
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangelogPrintService.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/ChangelogPrintServiceFactory.java
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/core/StandardChangelogPrintService.java
  liquibase-standard/src/main/java/liquibase/serializer/core/formattedsql/FormattedSqlChangeLogSerializer.java
Labels: TypeEnhancement

#7177 [7176]: Mapped tag in History.Changeset
  liquibase-standard/src/main/java/liquibase/logging/mdc/customobjects/History.java
Labels: TypeEnhancement

#7211 include database product name in license tracking data (DAT-20592)
  liquibase-standard/src/main/java/liquibase/command/core/helpers/DbUrlConnectionCommandStep.java
  liquibase-standard/src/main/java/liquibase/license/LicenseTrack.java
Labels: TypeEnhancement

#7208 Handle overwrite flag for formatted SQL correctly in generateChangelog
  liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/generateChangelog.test.groovy
  liquibase-standard/src/main/java/liquibase/diff/output/changelog/DiffToChangeLog.java
Labels: TypeBug

#7200 Remove duplicate header check for formatted SQL and add log message
  liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java
  liquibase-standard/src/main/java/liquibase/parser/AbstractFormattedChangeLogParser.java
  liquibase-standard/src/test/groovy/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParserTest.groovy
Labels: TypeBug

#7221 DAT-20693: Remove repository dispatch step for updating pom.xml for aws-license-service
  .github/workflows/release-published.yml
Labels: skipReleaseNotes

#7230 DAT-16042: Add test cases for SQL injection and HTML content pattern validation in `SimpleSqlGrammarTest` and `StringUtilTest`
  liquibase-standard/src/test/groovy/liquibase/util/StringUtilTest.groovy
  liquibase-standard/src/test/groovy/liquibase/util/grammar/SimpleSqlGrammarTest.groovy
Labels: TypeEnhancement
